import test from 'node:test';
import assert from 'node:assert/strict';
import {createAttributionEngine,createGrowthDirector} from '../lib/index.mjs';

const scope={organizationId:'org',workspaceId:'growth',tenantId:'tenant-a'};

test('position based attribution traces revenue to channel and content',()=>{const engine=createAttributionEngine({scope,model:'POSITION_BASED',windowDays:90,clock:()=> '2026-08-26T12:00:00Z'});engine.recordTouch({leadId:'lead-1',channel:'TIKTOK',campaignId:'c1',contentId:'video-1',occurredAt:'2026-08-01T00:00:00Z'});engine.recordTouch({leadId:'lead-1',channel:'WEBSITE',campaignId:'c1',contentId:'landing-1',occurredAt:'2026-08-10T00:00:00Z'});engine.recordTouch({leadId:'lead-1',channel:'EMAIL',campaignId:'c2',contentId:'followup-1',occurredAt:'2026-08-20T00:00:00Z'});const result=engine.attribute({leadId:'lead-1',conversionId:'order-1',amount:100000,currency:'USD',convertedAt:'2026-08-25T00:00:00Z'});assert.deepEqual(result.allocations.map(x=>x.attributedAmount),[40000,20000,40000]);assert.equal(engine.summarize().attributedRevenue,100000);assert.equal(engine.summarize().byChannel.TIKTOK,40000)});

test('growth director optimizes qualified pipeline and revenue rather than vanity metrics',()=>{const director=createGrowthDirector({scope,objectives:{qualifiedPipeline:20,revenue:200000,maxCac:1000}});const decision=director.analyze({channels:[{channel:'TIKTOK',spend:10000,leads:100,qualified:20,revenue:180000},{channel:'OTHER',spend:3000,leads:80,qualified:0,revenue:0}],markets:[{marketId:'m1'}],funnel:{qualifiedPipeline:15,revenue:180000}});assert.ok(decision.recommendations.some(x=>x.type==='SCALE_CHANNEL'&&x.channel==='TIKTOK'));assert.ok(decision.recommendations.some(x=>x.type==='REDUCE_OR_FIX_CHANNEL'&&x.channel==='OTHER'));assert.ok(decision.recommendations.some(x=>x.type==='RUN_MARKET_ICP_EXPERIMENT'));assert.throws(()=>director.createExperiment({hypothesis:'more likes',primaryMetric:'LIKES',variants:[{id:'a'},{id:'b'}]}),/vanity/);const experiment=director.createExperiment({hypothesis:'localized RFQ content improves qualified pipeline',primaryMetric:'QUALIFIED_PIPELINE',variants:[{id:'a'},{id:'b'}]});assert.equal(experiment.status,'DRAFT')});
