import test from 'node:test';
import assert from 'node:assert/strict';
import {defineTenantPack,createContentBrief,approveContentBrief,createContentProductionJob,createPublishingService,createMockPublishingAdapter} from '../lib/index.mjs';

const scope={organizationId:'org',workspaceId:'growth',tenantId:'tenant-a'};
const pack=defineTenantPack({...scope,name:'Tenant',brands:[{id:'brand',name:'Brand'}],markets:[{id:'market',country:'US'}],icps:[{id:'icp',name:'Buyer'}],channelPolicies:{MOCK:{enabled:true,allowedCapabilities:['PUBLISH_CONTENT'],requiresApproval:['PUBLISH_CONTENT'],dailyWriteLimit:5}},contentPolicy:{humanApprovalBeforePublish:true,forbidUnverifiedClaims:true}});

test('content brief blocks unverified claims and bridges to existing factory',()=>{assert.throws(()=>createContentBrief({...scope,brandId:'brand',marketId:'market',icpId:'icp',objectives:['PIPELINE'],claims:[{text:'unsupported',verified:false}],contentPolicy:pack.contentPolicy}),/unverified/);const brief=createContentBrief({...scope,brandId:'brand',marketId:'market',icpId:'icp',objectives:['PIPELINE'],claims:[{text:'verified',verified:true,evidenceRef:'kb:1'}],contentPolicy:pack.contentPolicy,locales:['en','zh-CN'],contentFormats:['SHORT_VIDEO']});assert.throws(()=>createContentProductionJob({brief}),/approval/);const approved=approveContentBrief(brief,{reviewerId:'reviewer'});const job=createContentProductionJob({brief:approved});assert.equal(job.factory,'VIDEO_FACTORY');assert.equal(job.variants.length,2)});

test('publish plan is approval gated, idempotent and retry bounded',async()=>{const adapter=createMockPublishingAdapter({channel:'MOCK',failuresBeforeSuccess:1});const service=createPublishingService({scope,tenantPack:pack,adapter,maxAttempts:3});const plan=service.createPlan({assetRef:'asset:1'});assert.equal(plan.status,'WAITING_APPROVAL');await assert.rejects(()=>service.execute(plan.planId),/not executable/);assert.throws(()=>service.approve(plan.planId,{reviewerId:'reviewer'}),/approvalRef/);assert.throws(()=>service.approve(plan.planId,{reviewerId:'reviewer',approvalRef:'token=plaintext'}),/invalid/);service.approve(plan.planId,{reviewerId:'reviewer',approvalRef:'approval:publish-1'});let result=await service.execute(plan.planId);assert.equal(result.status,'RETRYABLE');result=await service.execute(plan.planId);assert.equal(result.status,'COMPLETED');assert.equal(adapter.getAttempts(),2);const replay=await service.execute(plan.planId);assert.equal(replay.resultRef,result.resultRef);assert.equal(adapter.getAttempts(),2)});
