import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {defineTenantPack} from '../lib/tenant-kit.mjs';
import {assessGrowthPilotReadiness} from '../lib/pilot-readiness.mjs';

const kingturf=defineTenantPack(JSON.parse(await readFile(new URL('../examples/kingturf.tenant-pack.json',import.meta.url),'utf8'))),snapshot=JSON.parse(await readFile(new URL('../examples/kingturf.pilot-readiness.json',import.meta.url),'utf8'));
const activated={connectors:snapshot.connectors.map(item=>({...item,credentialReferenceConfigured:true,health:'HEALTHY'})),governance:{...snapshot.governance,dataOwnerApproval:true,productionFeatureFlag:true,runtimeActivationGatePassed:true,explicitProductionAuthorization:true},operations:snapshot.operations};

test('KingTurf implementation readiness does not claim production activation',()=>{const report=assessGrowthPilotReadiness({tenantPack:kingturf,...snapshot});assert.equal(report.status,'PILOT_ACTIVATION_BLOCKED');assert.equal(report.implementationReady,true);assert.equal(report.activationReady,false);for(const blocker of ['WEBSITE_CREDENTIAL_REFERENCE','PUBLISHING_CREDENTIAL_REFERENCE','BUSINESS_CREDENTIAL_REFERENCE','CONNECTOR_HEALTH','DATA_OWNER_APPROVAL','PRODUCTION_FEATURE_FLAG','RUNTIME_ACTIVATION_GATE','EXPLICIT_PRODUCTION_AUTHORIZATION'])assert.ok(report.blockers.includes(blocker));assert.deepEqual(report.safety,{externalWritesPerformed:false,productionChanged:false,runtimeEnabledByAssessment:false});assert.doesNotMatch(JSON.stringify(report),/vault|token|secret/i);});

test('activation readiness requires every production gate explicitly proven',()=>{const ready=assessGrowthPilotReadiness({tenantPack:kingturf,...activated});assert.equal(ready.status,'PILOT_ACTIVATION_READY');assert.equal(ready.blockers.length,0);const missing=assessGrowthPilotReadiness({tenantPack:kingturf,...activated,governance:{...activated.governance,explicitProductionAuthorization:false}});assert.equal(missing.status,'PILOT_ACTIVATION_BLOCKED');assert.deepEqual(missing.blockers,['EXPLICIT_PRODUCTION_AUTHORIZATION']);});

test('unrelated tenant uses the same readiness model without a Core fork',()=>{const tenant=defineTenantPack({organizationId:'other-org',workspaceId:'growth',tenantId:'saas-tenant',name:'SaaS Tenant',brands:[{id:'saas',name:'SaaS',domains:['saas.example']}],markets:[{id:'eu',country:'DE'}],icps:[{id:'it',name:'IT Buyer',roles:['CTO'],industries:['SOFTWARE'],markets:['eu']}],productRefs:[{externalSystem:'billing',productFamily:'SUBSCRIPTION'}],channelPolicies:{WEBSITE:{enabled:true,allowedCapabilities:['RECEIVE_WEBHOOK'],requiresApproval:[]},LINKEDIN:{enabled:true,allowedCapabilities:['PUBLISH_CONTENT'],requiresApproval:['PUBLISH_CONTENT']},EMAIL:{enabled:true,allowedCapabilities:['SEND_MESSAGE'],requiresApproval:['SEND_MESSAGE']}}});const report=assessGrowthPilotReadiness({tenantPack:tenant,...activated});assert.equal(report.status,'PILOT_ACTIVATION_READY');assert.equal(report.tenantId,'saas-tenant');assert.deepEqual(report.implementation.find(item=>item.id==='PILOT_CHANNEL_SCOPE').evidence.externalChannels,['LINKEDIN','EMAIL']);});
