import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ProfessionalRunnerCapabilityRegistry } from "../lib/professional-runner-capabilities.mjs";
import { ProfessionalRunnerExecutionService } from "../lib/professional-runner-execution.mjs";
import { createProfessionalMediaAdapters, implementedProfessionalAdapterIds } from "../lib/professional-media-adapters.mjs";

test("professional runner inventory distinguishes installed skills, tools and credential references", async () => {
  const root = await mkdtemp(join(tmpdir(), "runner-capabilities-")), skillsRoot = join(root, "skills"), bin = join(root, "bin"), registryPath = join(root, "registry.json");
  await mkdir(join(skillsRoot, "video-use"), { recursive: true }); await mkdir(bin);
  await writeFile(join(skillsRoot, "video-use", "SKILL.md"), "---\nname: video-use\n---\n");
  await writeFile(join(bin, "ffmpeg"), "#!/bin/sh\necho ffmpeg-test\n", { mode: 0o755 });
  await writeFile(registryPath, JSON.stringify({ schema_version: 1, registry_id: "test", profiles: [{ profile_id: "editor", display_name: "Editor", runner_class: "FOOTAGE_EDITOR", skill_types: ["video_editing"], skill_packages: ["video-use"], tool_dependencies: [{ command: "ffmpeg", version_args: ["-version"] }], credential_references: ["speech-ref"], allowed_commands: [], blocked_commands: [], allowed_output_roots: [], network_policy: "DENY", side_effect_policy: "ARTIFACT_WRITE_ONLY", max_runtime_seconds: 60, max_parallel_tasks: 1, risk_level: "LOW" }] }));
  const blocked = new ProfessionalRunnerCapabilityRegistry({ registryPath, skillsRoot, env: { PATH: bin } });
  assert.equal((await blocked.resolve("video_editing")).status, "BLOCKED");
  const ready = new ProfessionalRunnerCapabilityRegistry({ registryPath, skillsRoot, env: { PATH: bin }, credentialReferenceIds: ["speech-ref"] });
  const result = await ready.resolve("video_editing"); assert.equal(result.status, "READY"); assert.equal(result.selected_profile_id, "editor");
});

test("unknown professional skill fails closed", async () => {
  const registry = new ProfessionalRunnerCapabilityRegistry();
  const result = await registry.resolve("unknown_media_skill");
  assert.equal(result.status, "BLOCKED"); assert.deepEqual(result.blocked_reasons, ["NO_RUNNER_PROFILE:unknown_media_skill"]);
});

test("installed capability remains non-executable until node activation",async()=>{const root=await mkdtemp(join(tmpdir(),"runner-gate-")),skillsRoot=join(root,"skills"),bin=join(root,"bin"),registryPath=join(root,"registry.json");await mkdir(join(skillsRoot,"video-skill"),{recursive:true});await mkdir(bin);await writeFile(join(skillsRoot,"video-skill","SKILL.md"),"---\nname: video-skill\n---\n");await writeFile(join(bin,"render-tool"),"#!/bin/sh\necho 1.2.3\n",{mode:0o755});const profile={profile_id:"render",capability_version:"1.2.0",adapter_id:"render-v1",activation:{required:true,environment_variable:"TEST_RENDER_ENABLED",default:false},display_name:"Render",runner_class:"VIDEO",skill_types:["video_generation"],skill_packages:["video-skill"],tool_dependencies:[{command:"render-tool",version_args:["--version"]}],credential_references:[],allowed_commands:["render"],blocked_commands:["git push"],allowed_output_roots:["runtime/artifacts/media"],network_policy:"DENY",side_effect_policy:"ARTIFACT_WRITE_ONLY",max_runtime_seconds:60,max_parallel_tasks:1,risk_level:"LOW"};await writeFile(registryPath,JSON.stringify({schema_version:1,registry_id:"test",profiles:[profile]}));const registry=new ProfessionalRunnerCapabilityRegistry({registryPath,skillsRoot,env:{PATH:bin},registeredAdapterIds:["render-v1"]}),inventory=await registry.inventory();assert.equal(inventory.profiles[0].installation_readiness,"READY");assert.equal(inventory.profiles[0].execution_readiness,"NOT_EXECUTABLE");assert.match(inventory.profiles[0].evidence_hash,/^[a-f0-9]{64}$/);const blocked=await registry.preflight({profileId:"render",skillType:"video_generation",taskId:"t1",attemptId:"a1",fencingToken:"f1",artifactRoot:"runtime/artifacts/media",command:"render"});assert.equal(blocked.status,"BLOCKED");assert.deepEqual(blocked.blocked_reasons,["RUNNER_NOT_ACTIVATED:render"]);});

test("execution gate writes hashed artifacts and chained audit without exposing fencing",async()=>{const root=await mkdtemp(join(tmpdir(),"runner-execution-")),skillsRoot=join(root,"skills"),bin=join(root,"bin"),registryPath=join(root,"registry.json");await mkdir(join(skillsRoot,"video-skill"),{recursive:true});await mkdir(bin);await writeFile(join(skillsRoot,"video-skill","SKILL.md"),"skill");await writeFile(join(bin,"render-tool"),"#!/bin/sh\necho 1.2.3\n",{mode:0o755});await writeFile(registryPath,JSON.stringify({schema_version:1,registry_id:"test",profiles:[{profile_id:"render",capability_version:"1.2.0",adapter_id:"render-v1",activation:{required:true,environment_variable:"TEST_RENDER_ENABLED",default:false},display_name:"Render",runner_class:"VIDEO",skill_types:["video_generation"],skill_packages:["video-skill"],tool_dependencies:[{command:"render-tool"}],credential_references:[],allowed_commands:["render"],blocked_commands:[],allowed_output_roots:["runtime/artifacts/media"],network_policy:"DENY",side_effect_policy:"ARTIFACT_WRITE_ONLY",max_runtime_seconds:60,max_parallel_tasks:1,risk_level:"LOW"}]}));const registry=new ProfessionalRunnerCapabilityRegistry({registryPath,skillsRoot,env:{PATH:bin,TEST_RENDER_ENABLED:"true"},registeredAdapterIds:["render-v1"]}),service=new ProfessionalRunnerExecutionService({registry,repoRoot:root,now:()=>new Date("2026-07-21T00:00:00Z"),adapters:{render:async()=>({artifacts:[{name:"result.txt",mediaType:"text/plain",content:"rendered"}]})}}),result=await service.execute({executionId:"exec-1",profileId:"render",workerProfileId:"render",skillType:"video_generation",taskId:"task-1",attemptId:"attempt-1",fencingToken:"secret-fence",artifactRoot:"runtime/artifacts/media",command:"render"});assert.equal(result.status,"SUCCEEDED");assert.equal(result.manifest.capabilityVersion,"1.2.0");assert.match(result.artifacts[0].sha256,/^[a-f0-9]{64}$/);const audit=await readFile(join(root,"runtime/artifacts/media/exec-1/audit-events.json"),"utf8");assert.match(audit,/professional\.execution\.started/);assert.match(audit,/professional\.execution\.succeeded/);assert.doesNotMatch(audit,/secret-fence/);});

test("media task routing selects the specific registered Skill and never upgrades installation to execution",async()=>{const registry=new ProfessionalRunnerCapabilityRegistry(),matrix=await registry.matchTask({id:"media-1",title:"生成短视频矩阵和渠道变体"});assert.equal(matrix.rule.rule_id,"RULE-VIDEO-MATRIX");assert.equal(matrix.rule.skill_type,"video_matrix_generation");assert.equal(matrix.status,"INSTALLED_MATCH");assert.equal(matrix.capability.execution_readiness,"NOT_EXECUTABLE");assert.ok(matrix.capability.blocked_reasons.some(reason=>reason.startsWith("RUNNER_NOT_ACTIVATED")));});

test("implemented FFprobe adapter accepts only isolated media inputs and returns sanitized QA evidence",async()=>{const root=await mkdtemp(join(tmpdir(),"media-adapter-")),media=join(root,"runtime/artifacts/media");await mkdir(media,{recursive:true});await writeFile(join(media,"input.mp4"),"fixture");const calls=[],adapters=createProfessionalMediaAdapters({repoRoot:root,run:(command,args)=>{calls.push({command,args});return{status:0,stdout:JSON.stringify({format:{format_name:"mp4",duration:"1.0"},streams:[{index:0,codec_type:"video",codec_name:"h264",width:1920,height:1080,secret:"drop"}]})};}}),result=await adapters["media-quality-control"]({request:{inputPath:"runtime/artifacts/media/input.mp4"}});assert.deepEqual(implementedProfessionalAdapterIds,["ffmpeg-quality-adapter-v1"]);assert.equal(calls[0].command,"ffprobe");assert.match(result.artifacts[0].content,/"codecName": "h264"/);assert.doesNotMatch(result.artifacts[0].content,/secret/);await writeFile(join(root,"outside.mp4"),"fixture");await assert.rejects(()=>adapters["media-quality-control"]({request:{inputPath:"outside.mp4"}}),error=>error.code==="MEDIA_INPUT_PATH_BLOCKED");});
