import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ProfessionalRunnerCapabilityRegistry } from "../lib/professional-runner-capabilities.mjs";
import { ProfessionalRunnerExecutionService } from "../lib/professional-runner-execution.mjs";
import { createProfessionalMediaAdapters, implementedProfessionalAdapterIds } from "../lib/professional-media-adapters.mjs";
import { createHyperframesArtifactAdapter } from "../lib/hyperframes-artifact-adapter.mjs";
import { ProfessionalRunnerKernelBridge } from "../lib/professional-runner-kernel-bridge.mjs";
import { projectProfessionalArtifacts } from "../lib/professional-artifact-projection.mjs";

test("professional runner inventory distinguishes installed skills, tools and credential references", async () => {
  const root = await mkdtemp(join(tmpdir(), "runner-capabilities-")), skillsRoot = join(root, "skills"), bin = join(root, "bin"), registryPath = join(root, "registry.json");
  await mkdir(join(skillsRoot, "video-use"), { recursive: true }); await mkdir(bin);
  await writeFile(join(skillsRoot, "video-use", "SKILL.md"), "---\nname: video-use\n---\n");
  await writeFile(join(bin, "ffmpeg"), "#!/bin/sh\necho ffmpeg-test\n", { mode: 0o755 });
  await writeFile(registryPath, JSON.stringify({ schema_version: 1, registry_id: "test", profiles: [{ profile_id: "editor", display_name: "Editor", runner_class: "FOOTAGE_EDITOR", skill_types: ["video_editing"], skill_packages: ["video-use"], tool_dependencies: [{ command: "ffmpeg", version_args: ["-version"] }], credential_references: ["speech-ref"], allowed_commands: [], blocked_commands: [], allowed_output_roots: [], network_policy: "DENY", side_effect_policy: "ARTIFACT_WRITE_ONLY", max_runtime_seconds: 60, max_parallel_tasks: 1, risk_level: "LOW" }] }));
  const blocked = new ProfessionalRunnerCapabilityRegistry({ registryPath, skillsRoot, env: { PATH: bin } });
  assert.equal((await blocked.resolve("video_editing")).status, "BLOCKED");
  const ready = new ProfessionalRunnerCapabilityRegistry({ registryPath, skillsRoot, env: { PATH: bin }, credentialReferenceIds: ["speech-ref"] });
  const result = await ready.resolve("video_editing"); assert.equal(result.status, "READY"); assert.equal(result.selected_profile_id, "editor");
});

test("unknown professional skill fails closed", async () => {
  const registry = new ProfessionalRunnerCapabilityRegistry();
  const result = await registry.resolve("unknown_media_skill");
  assert.equal(result.status, "BLOCKED"); assert.deepEqual(result.blocked_reasons, ["NO_RUNNER_PROFILE:unknown_media_skill"]);
});

test("installed capability remains non-executable until node activation",async()=>{const root=await mkdtemp(join(tmpdir(),"runner-gate-")),skillsRoot=join(root,"skills"),bin=join(root,"bin"),registryPath=join(root,"registry.json");await mkdir(join(skillsRoot,"video-skill"),{recursive:true});await mkdir(bin);await writeFile(join(skillsRoot,"video-skill","SKILL.md"),"---\nname: video-skill\n---\n");await writeFile(join(bin,"render-tool"),"#!/bin/sh\necho 1.2.3\n",{mode:0o755});const profile={profile_id:"render",capability_version:"1.2.0",adapter_id:"render-v1",activation:{required:true,environment_variable:"TEST_RENDER_ENABLED",default:false},display_name:"Render",runner_class:"VIDEO",skill_types:["video_generation"],skill_packages:["video-skill"],tool_dependencies:[{command:"render-tool",version_args:["--version"]}],credential_references:[],allowed_commands:["render"],blocked_commands:["git push"],allowed_output_roots:["runtime/artifacts/media"],network_policy:"DENY",side_effect_policy:"ARTIFACT_WRITE_ONLY",max_runtime_seconds:60,max_parallel_tasks:1,risk_level:"LOW"};await writeFile(registryPath,JSON.stringify({schema_version:1,registry_id:"test",profiles:[profile]}));const registry=new ProfessionalRunnerCapabilityRegistry({registryPath,skillsRoot,env:{PATH:bin},registeredAdapterIds:["render-v1"]}),inventory=await registry.inventory();assert.equal(inventory.profiles[0].installation_readiness,"READY");assert.equal(inventory.profiles[0].execution_readiness,"NOT_EXECUTABLE");assert.match(inventory.profiles[0].evidence_hash,/^[a-f0-9]{64}$/);const blocked=await registry.preflight({profileId:"render",skillType:"video_generation",taskId:"t1",attemptId:"a1",fencingToken:"f1",artifactRoot:"runtime/artifacts/media",command:"render"});assert.equal(blocked.status,"BLOCKED");assert.deepEqual(blocked.blocked_reasons,["RUNNER_NOT_ACTIVATED:render"]);});

test("execution gate writes hashed artifacts and chained audit without exposing fencing",async()=>{const root=await mkdtemp(join(tmpdir(),"runner-execution-")),skillsRoot=join(root,"skills"),bin=join(root,"bin"),registryPath=join(root,"registry.json");await mkdir(join(skillsRoot,"video-skill"),{recursive:true});await mkdir(bin);await writeFile(join(skillsRoot,"video-skill","SKILL.md"),"skill");await writeFile(join(bin,"render-tool"),"#!/bin/sh\necho 1.2.3\n",{mode:0o755});await writeFile(registryPath,JSON.stringify({schema_version:1,registry_id:"test",profiles:[{profile_id:"render",capability_version:"1.2.0",adapter_id:"render-v1",activation:{required:true,environment_variable:"TEST_RENDER_ENABLED",default:false},display_name:"Render",runner_class:"VIDEO",skill_types:["video_generation"],skill_packages:["video-skill"],tool_dependencies:[{command:"render-tool"}],credential_references:[],allowed_commands:["render"],blocked_commands:[],allowed_output_roots:["runtime/artifacts/media"],network_policy:"DENY",side_effect_policy:"ARTIFACT_WRITE_ONLY",max_runtime_seconds:60,max_parallel_tasks:1,risk_level:"LOW"}]}));const registry=new ProfessionalRunnerCapabilityRegistry({registryPath,skillsRoot,env:{PATH:bin,TEST_RENDER_ENABLED:"true"},registeredAdapterIds:["render-v1"]}),service=new ProfessionalRunnerExecutionService({registry,repoRoot:root,now:()=>new Date("2026-07-21T00:00:00Z"),adapters:{render:async()=>({artifacts:[{name:"result.txt",mediaType:"text/plain",content:"rendered"}]})}}),result=await service.execute({executionId:"exec-1",profileId:"render",workerProfileId:"render",skillType:"video_generation",taskId:"task-1",attemptId:"attempt-1",fencingToken:"secret-fence",artifactRoot:"runtime/artifacts/media",command:"render"});assert.equal(result.status,"SUCCEEDED");assert.equal(result.manifest.capabilityVersion,"1.2.0");assert.match(result.artifacts[0].sha256,/^[a-f0-9]{64}$/);const audit=await readFile(join(root,"runtime/artifacts/media/exec-1/audit-events.json"),"utf8");assert.match(audit,/professional\.execution\.started/);assert.match(audit,/professional\.execution\.succeeded/);assert.doesNotMatch(audit,/secret-fence/);});

test("media task routing selects the specific registered Skill and never upgrades installation to execution",async()=>{const registry=new ProfessionalRunnerCapabilityRegistry(),matrix=await registry.matchTask({id:"media-1",title:"生成短视频矩阵和渠道变体"});assert.equal(matrix.rule.rule_id,"RULE-VIDEO-MATRIX");assert.equal(matrix.rule.skill_type,"video_matrix_generation");assert.equal(matrix.status,"INSTALLED_MATCH");assert.equal(matrix.capability.execution_readiness,"NOT_EXECUTABLE");assert.ok(matrix.capability.blocked_reasons.some(reason=>reason.startsWith("RUNNER_NOT_ACTIVATED")));});

test("implemented FFprobe adapter accepts only isolated media inputs and returns sanitized QA evidence",async()=>{const root=await mkdtemp(join(tmpdir(),"media-adapter-")),media=join(root,"runtime/artifacts/media");await mkdir(media,{recursive:true});await writeFile(join(media,"input.mp4"),"fixture");const calls=[],adapters=createProfessionalMediaAdapters({repoRoot:root,run:(command,args)=>{calls.push({command,args});return{status:0,stdout:JSON.stringify({format:{format_name:"mp4",duration:"1.0"},streams:[{index:0,codec_type:"video",codec_name:"h264",width:1920,height:1080,secret:"drop"}]})};}}),result=await adapters["media-quality-control"]({request:{inputPath:"runtime/artifacts/media/input.mp4"}});assert.deepEqual(implementedProfessionalAdapterIds,["hyperframes-artifact-adapter-v1","ffmpeg-quality-adapter-v1"]);assert.equal(calls[0].command,"ffprobe");assert.match(result.artifacts[0].content,/"codecName": "h264"/);assert.doesNotMatch(result.artifacts[0].content,/secret/);await writeFile(join(root,"outside.mp4"),"fixture");await assert.rejects(()=>adapters["media-quality-control"]({request:{inputPath:"outside.mp4"}}),error=>error.code==="MEDIA_INPUT_PATH_BLOCKED");});

test("HyperFrames adapter gates check and render with pinned project and consumed approval",async()=>{const root=await mkdtemp(join(tmpdir(),"hyperframes-adapter-")),project=join(root,"runtime/workspaces/media/project-1"),output=join(root,"runtime/artifacts/media/exec-1");await mkdir(project,{recursive:true});await mkdir(output,{recursive:true});await writeFile(join(project,"BRIEF.md"),"---\nworkflow: motion-graphics\nflow: automation\nstoryboard: no\n---\n");await writeFile(join(project,"index.html"),"<html></html>");await writeFile(join(project,"package.json"),JSON.stringify({devDependencies:{hyperframes:"0.7.65"}}));const calls=[],run=async(_binary,args)=>{calls.push(args);if(args[0]==="check")return{code:0,stdout:JSON.stringify({ok:true,lint:{errors:[]}}),stderr:""};await writeFile(args.at(-1),"video");return{code:0,stdout:"",stderr:""};},adapter=createHyperframesArtifactAdapter({repoRoot:root,run}),base={projectRoot:"runtime/workspaces/media/project-1",taskId:"task-1",attemptId:"attempt-1",profileId:"media-generative-hyperframes",maxRuntimeMs:1000};const checked=await adapter({request:{...base,operation:"CHECK"},outputRoot:output});assert.equal(checked.status,"CHECKED_AWAITING_RENDER_APPROVAL");assert.equal(calls[0][0],"check");await assert.rejects(()=>adapter({request:{...base,operation:"RENDER"},outputRoot:output}),error=>error.code==="HYPERFRAMES_RENDER_APPROVAL_REQUIRED");const rendered=await adapter({request:{...base,operation:"RENDER",renderApproval:{status:"CONSUMED",taskId:"task-1",attemptId:"attempt-1",profileId:"media-generative-hyperframes"}},outputRoot:output});assert.equal(rendered.status,"SUCCEEDED");assert.equal(rendered.artifacts[0].sourcePath,join(output,"render.mp4"));});

test("HyperFrames deny-by-default adapter rejects external resources",async()=>{const root=await mkdtemp(join(tmpdir(),"hf-network-")),project=join(root,"runtime/workspaces/media/project"),output=join(root,"runtime/artifacts/media/out");await mkdir(project,{recursive:true});await mkdir(output,{recursive:true});await writeFile(join(project,"BRIEF.md"),"# brief");await writeFile(join(project,"package.json"),JSON.stringify({scripts:{render:"hyperframes@0.7.65 render"}}));await writeFile(join(project,"index.html"),'<script src="https://example.com/a.js"></script>');const adapter=createHyperframesArtifactAdapter({repoRoot:root,run:async()=>({code:0,stdout:'{"ok":true}',stderr:""})});await assert.rejects(()=>adapter({request:{projectRoot:"runtime/workspaces/media/project",operation:"CHECK"},outputRoot:output}),error=>error.code==="HYPERFRAMES_EXTERNAL_RESOURCE_BLOCKED");});

test("kernel bridge preserves existing lease and fencing authority",async()=>{let current=true,released=null;const kernel={assertCurrent:async()=>{if(!current)throw Object.assign(new Error("FENCING_REJECTED"),{code:"FENCING_REJECTED"});},releaseLease:async(proof,result)=>{released={proof,result};}},executionService={execute:async()=>({status:"SUCCEEDED",executionId:"exec-1",manifest:{artifacts:[{name:"render.mp4"}]}})},bridge=new ProfessionalRunnerKernelBridge({kernel,executionService}),claim={taskId:"t",attemptId:"a",leaseId:"l",leaseToken:"lease-secret",fencingToken:7,workerId:"w",sessionId:"s",expectedVersion:1};const result=await bridge.execute({claim,request:{profileId:"media-generative-hyperframes"}});assert.equal(result.status,"SUCCEEDED");assert.equal(released.result.validationResult.fencingValidated,true);assert.equal(released.result.taskStatus,"SUCCEEDED");current=false;await assert.rejects(()=>bridge.execute({claim,request:{}}),error=>error.code==="FENCING_REJECTED");});

test("artifact projection exposes sanitized console evidence only",async()=>{const root=await mkdtemp(join(tmpdir(),"artifact-projection-")),dir=join(root,"runtime/artifacts/media/exec-1");await mkdir(dir,{recursive:true});await writeFile(join(dir,"artifact-manifest.json"),JSON.stringify({executionId:"exec-1",taskId:"task-1",profileId:"media-generative-hyperframes",capabilityVersion:"1.0.0",status:"SUCCEEDED",completedAt:"2026-07-21T00:00:00Z",artifacts:[{name:"render.mp4",mediaType:"video/mp4",bytes:10,sha256:"abc",relativePath:"secret/path"}]}));const projection=await projectProfessionalArtifacts({repoRoot:root});assert.equal(projection.summary.succeeded,1);assert.equal(projection.items[0].artifacts[0].name,"render.mp4");assert.equal("relativePath" in projection.items[0].artifacts[0],false);});
