import test from "node:test"; import assert from "node:assert/strict"; import { readFile } from "node:fs/promises"; import { PostgresAutonomousKernelStore } from "../../lib/autonomous-kernel/postgres-store.mjs";
function pool(handler){const queries=[];return {queries,connect:async()=>({query:async(sql,args=[])=>{queries.push({sql,args});return handler(sql,args,queries);},release(){queries.push({sql:"RELEASE"});}})};}
test("transaction commits and rollback propagates",async()=>{const ok=pool(()=>({rows:[]}));const store=new PostgresAutonomousKernelStore(ok);await store.transaction(async()=>42);assert.deepEqual(ok.queries.map(x=>x.sql),["BEGIN","COMMIT","RELEASE"]);const bad=pool((sql)=>{if(sql==="SELECT fail")throw new Error("boom");return{rows:[]};});await assert.rejects(new PostgresAutonomousKernelStore(bad).transaction(c=>c.query("SELECT fail")),/boom/);assert.ok(bad.queries.some(x=>x.sql==="ROLLBACK"));});
test("Goal create uses Studio scope, fingerprint, transaction and outbox",async()=>{const p=pool((sql)=>sql.startsWith("SELECT * FROM ad_goal")?{rows:[]}:{rows:sql.startsWith("INSERT INTO ad_goal")?[{id:"G",request_fingerprint:"x"}]:[]});await new PostgresAutonomousKernelStore(p).createGoal({organizationId:"O",workspaceId:"W",projectId:"P"},{title:"Goal",description:"D",source:"console",idempotencyKey:"K"});assert.ok(p.queries.some(x=>x.sql.includes("organization_id")));assert.ok(p.queries.some(x=>x.sql.includes("ad_outbox_event")));});
test("claim SQL preserves SKIP LOCKED, capability filter, atomic Attempt+Lease and CAS",async()=>{const responses=[{rows:[{id:"W",status:"IDLE",active_claims:0,max_concurrency:1}]},{rows:[{id:"S"}]},{rows:[{id:"T",goal_id:"G",project_id:"P",version:2,max_attempts:3}]},{rows:[{value:1}]},{rows:[{value:4}]},{rows:[]},{rows:[]},{rows:[]},{rows:[{version:3}],rowCount:1},{rows:[]},{rows:[]},{rows:[]}];let i=0;const p=pool((sql)=>["BEGIN","COMMIT"].includes(sql)?{rows:[]}:responses[i++]??{rows:[]});const result=await new PostgresAutonomousKernelStore(p).claimNext({organizationId:"O",workspaceId:"W",workerId:"00000000-0000-4000-8000-000000000001",sessionId:"00000000-0000-4000-8000-000000000002",capabilities:["backend"]});assert.equal(result.fencingToken,4);const text=p.queries.map(x=>x.sql).join("\n");assert.match(text,/SKIP LOCKED/);assert.match(text,/required_capabilities <@/);assert.match(text,/ad_task_attempt/);assert.match(text,/ad_task_lease/);assert.match(text,/version=version\+1/);});
test("fenced updates reject stale ownership",async()=>{const p=pool((sql)=>sql.startsWith("SELECT * FROM ad_task_lease")?{rows:[{status:"ACTIVE",expires_at:new Date(Date.now()+10000),lease_token:"new",fencing_token:2,worker_id:"W",session_id:"S",version:1}]}:{rows:[]});await assert.rejects(new PostgresAutonomousKernelStore(p).fencedUpdate({leaseId:"L",leaseToken:"old",fencingToken:1,workerId:"W",sessionId:"S",expectedVersion:1},async()=>{}),/FENCING_REJECTED/);});
test("worker, scheduler and lease lifecycle protocols are present",()=>{const methods=Object.getOwnPropertyNames(PostgresAutonomousKernelStore.prototype);for(const name of ["submitPlan","registerWorker","openSession","heartbeat","setDrain","schedulerTick","reapExpired","renewLease","releaseLease"])assert.ok(methods.includes(name),name);});
test("Kernel rejects an invalid Planner graph before opening a transaction",async()=>{const p=pool(()=>({rows:[]}));await assert.rejects(new PostgresAutonomousKernelStore(p).submitPlan("G",{plannerVersion:"P",tasks:[{taskKey:"A",title:"A"},{taskKey:"A",title:"B"}],dependencies:[]}),/INVALID_TASK_GRAPH:DUPLICATE_TASK_KEY/);assert.equal(p.queries.length,0);});
test("Kernel atomically persists a standard Planner Task Graph",async()=>{const p=pool((sql)=>sql.startsWith("SELECT * FROM ad_planner_submission")?{rows:[]}:sql.startsWith("SELECT * FROM ad_goal")?{rows:[{id:"G",organization_id:"O",workspace_id:"W",project_id:"P",version:1}]}:sql.startsWith("INSERT INTO ad_planner_submission")?{rows:[{id:"PS"}]}:{rows:[]});const submission=await new PostgresAutonomousKernelStore(p).submitPlan("G",{plannerVersion:"rule-v1",tasks:[{taskKey:"A",title:"Analyze"},{taskKey:"B",title:"Build"}],dependencies:[{taskKey:"B",dependsOnTaskKey:"A",dependencyType:"SUCCESS_REQUIRED",requiredStatus:"SUCCEEDED"}]});assert.equal(submission.id,"PS");assert.equal(p.queries.filter(q=>q.sql.startsWith("INSERT INTO ad_task(")).length,2);assert.equal(p.queries.filter(q=>q.sql.startsWith("INSERT INTO ad_task_dependency")).length,1);assert.ok(p.queries.some(q=>q.sql==="COMMIT"));});
test("scheduler consumes the persisted depends_on_task_id schema",async()=>{const p=pool((sql)=>sql.startsWith("SELECT t.*")?{rows:[{id:"T",goal_id:"G",project_id:"P",status:"PENDING",version:1}]}:sql.includes("depends_on_task_id")?{rows:[]}:sql.startsWith("UPDATE ad_task SET")?{rows:[{version:2}],rowCount:1}:{rows:[]});const result=await new PostgresAutonomousKernelStore(p).schedulerTick({dryRun:false});assert.equal(result.changed[0].next,"READY");assert.ok(p.queries.some(q=>q.sql.includes("d.depends_on_task_id")));});
test("scheduler does not let unchanged historical BLOCKED tasks starve runnable work",async()=>{const p=pool(()=>({rows:[]}));await new PostgresAutonomousKernelStore(p).schedulerTick({dryRun:true});const query=p.queries.find(value=>value.sql.startsWith("SELECT t.*"))?.sql??"";assert.match(query,/CASE t\.status WHEN 'READY'/);assert.match(query,/t\.status='BLOCKED' AND NOT EXISTS/);assert.match(query,/p\.status<>'SUCCEEDED'/);});
test("migration is reversible and retains all uniqueness invariants",async()=>{const up=await readFile(new URL("../../migrations/001_autonomous_kernel.up.sql",import.meta.url),"utf8");const down=await readFile(new URL("../../migrations/001_autonomous_kernel.down.sql",import.meta.url),"utf8");for(const pattern of [/organization_id/,/UNIQUE\(goal_id,task_key\)/,/UNIQUE\(task_id,attempt_number\)/,/ad_task_one_active_lease/,/UNIQUE\(goal_id,id\)/,/ad_outbox_event/,/ad_state_transition/])assert.match(up,pattern);assert.match(down,/DROP TABLE IF EXISTS ad_goal/);});
