import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {renderConsolePage} from "./render.mjs";import {consoleWebRoutes} from "./routes.mjs";import {enterpriseApplications} from "../../../packages/domain-center/lib/enterprise-applications.mjs";
const owner={authenticated:true,user:{user_id:"owner",display_name:"Owner"},capabilities:["*"],project_allowlist:["*"]};
test("business applications have independent conventional endpoints",async()=>{const routes=new Map(consoleWebRoutes.map(route=>[route.path,route.id]));for(const app of enterpriseApplications){assert.equal(routes.get(app.path),app.routeId);const html=await renderConsolePage(app.path,owner);if(app.path==="/development")assert.match(html,/真实自主开发/);else{assert.match(html,/业务台账/);assert.match(html,/新建业务记录/);assert.match(html,/Runtime 关闭时/);}}assert.equal(routes.get("/cockpit"),"cockpit");assert.equal(routes.get("/work"),"work");});
test("application route permission fails closed for the wrong persona",async()=>{const strategyUser={authenticated:true,user:{user_id:"strategy-user"},capabilities:["console.access","work.read","strategy.read"],project_allowlist:["*"]};assert.match(await renderConsolePage("/strategy",strategyUser),/战略执行平台/);const denied=await renderConsolePage("/finance",strategyUser);assert.match(denied,/当前账号未开通此模块/);assert.match(denied,/finance\.read/);});
test("strategy, HR and finance render domain-specific conventional forms",async()=>{const strategy=await renderConsolePage("/strategy",owner),hr=await renderConsolePage("/hr",owner),finance=await renderConsolePage("/finance",owner);assert.match(strategy,/战略周期/);assert.match(strategy,/责任中心/);assert.match(hr,/用人部门/);assert.match(hr,/招聘岗位/);assert.match(hr,/候选人引用编号/);assert.match(hr,/个人信息授权/);assert.match(hr,/人工选择决定编号/);assert.match(hr,/受控录用文件编号/);assert.match(hr,/最小权限模板编号/);assert.match(finance,/费用日期/);assert.match(finance,/预算科目/);for(const html of [strategy,hr,finance]){assert.match(html,/data-business-field/);assert.match(html,/data-transition/);assert.match(html,/availableTransitions/);assert.match(html,/上下游业务链/);assert.match(html,/data-create-relation/);assert.match(html,/创建下游业务单据/);assert.match(html,/data-create-related-record/);assert.match(html,/data-related-field/);}});
test("growth, manufacturing and Smart Park render operational domain forms",async()=>{const growth=await renderConsolePage("/growth-sales",owner),manufacturing=await renderConsolePage("/manufacturing",owner),park=await renderConsolePage("/smart-park",owner);assert.match(growth,/线索来源/);assert.match(growth,/联系授权/);assert.match(growth,/赢单概率/);assert.match(growth,/产品主张证据编号/);assert.match(growth,/版权与肖像授权编号/);assert.match(growth,/凭据引用编号/);assert.match(growth,/发布模式/);assert.match(manufacturing,/计划数量/);assert.match(manufacturing,/BOM/);assert.match(manufacturing,/工艺路线与 SOP/);assert.match(manufacturing,/组件需求/);assert.match(manufacturing,/受控作业指导书编号/);assert.match(manufacturing,/严重度/);assert.match(park,/服务企业/);assert.match(park,/统一社会信用代码/);assert.match(park,/计量倍率/);});
test("group cockpit renders source-backed business chain counts",async()=>{const html=await renderConsolePage("/",owner);assert.match(html,/businessChains/);assert.match(html,/业务链/);});
test("group cockpit renders an idempotent source-backed action feed",async()=>{const html=await renderConsolePage("/",owner);for(const value of ["行动提醒","/api/business/notifications","关键异常","需要审批","没有虚构“未读”状态"])assert.match(html,new RegExp(value));});
test("group cockpit searches authoritative records across only visible applications",async()=>{const html=await renderConsolePage("/",owner);for(const value of ["查找业务记录","/api/business/search","编号、标题或负责人","打开记录","business-search-results"])assert.match(html,new RegExp(value));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["searchRecords","applicationIds","ownerId","evaluateConsoleRouteAccess"])assert.match(source,new RegExp(value));});
test("business record detail renders authoritative Skill Agent Runner Attempt and sanitized Runtime evidence",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["executionEvidence","businessSkillId","skillType","agentId","runner?.workerKey","runtimeType","Attempt","runtimeResult","Result"]){assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));}assert.doesNotMatch(html,/leaseToken/);});
test("business record detail supports versioned edits only when the source object is editable",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["编辑业务记录","data-save-business-record","data-edit-field","expectedVersion","method:'PATCH'","business-edit-owner"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["business-record-update","updateRecord","request.method===\"PATCH\""])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("business record detail adds version-bound audited notes through the existing timeline",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["添加处理备注","business-record-note","data-add-business-note","写入时间线","/notes","expectedVersion"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["business-record-note","addRecordNote","/notes$"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("business workbenches use server-filtered paginated authoritative record lists",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["business-filter-query","business-filter-type","business-filter-status","business-filter-owner","data-business-page","pagination.total","URLSearchParams","offset"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["recordPage","url.searchParams.get(\"q\")","url.searchParams.get(\"ownerId\")","url.searchParams.get(\"offset\")"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("Agent delegation shows an exact-version Workflow Skill Agent Runner preflight",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["Agent Delegation Preflight","business-delegation-dialog","delegation-preview","通用流程 Agent · Skill · Runner","专业业务 Agent · Runner","expectedObjectVersion","executionRuntime","确认委派","委派方案已确认","business.work.delegation-approved"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["buildBusinessDelegationPreview","businessDelegationPreview","BUSINESS_DELEGATION_BLOCKED","BUSINESS_CAPABILITY_CHANGED_REAPPROVAL_REQUIRED","approvedContractHash","currentContractHash","expectedObjectVersion","BUSINESS_RECORD_VERSION_CONFLICT","delegationPlan"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});
test("approved Agent plans are visibly projected from immutable audit evidence",async()=>{const finance=await renderConsolePage("/finance",owner),work=await renderConsolePage("/work",owner);for(const value of ["已批准智能执行方案","delegationPlan.domainId","delegationPlan.workflowDefinitionId","delegationPlan.stages","delegationPlan.executionRuntime","不可变委派审计"])assert.match(finance+work,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const html of [finance,work]){assert.doesNotMatch(html,/leaseToken/);assert.doesNotMatch(html,/fencingToken/);}});
test("business users see a Kernel-backed online execution projection",async()=>{const finance=await renderConsolePage("/finance",owner),work=await renderConsolePage("/work",owner),asset=await readFile(new URL("./assets/business-work-execution.js",import.meta.url),"utf8"),projection=await readFile(new URL("../../../packages/domain-center/lib/business-work-execution.mjs",import.meta.url),"utf8");for(const value of ["在线执行状态","Agent 在线执行","business-work-execution.js","work-execution-live","execution.phase","execution.progress","AUTONOMOUS_KERNEL","自动刷新"])assert.match(finance+work+asset+projection,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const source of [finance,work,asset,projection]){assert.doesNotMatch(source,/leaseToken/);assert.doesNotMatch(source,/fencingToken/);}});
test("My Work hides Agent controls from approval-only users and exposes workspace management to owners",async()=>{const reviewer={authenticated:true,user:{user_id:"finance-reviewer"},capabilities:["console.access","work.read","finance.read","business.operate","proposal.approve"],project_allowlist:["*"]},reviewerHtml=await renderConsolePage("/work",reviewer),ownerHtml=await renderConsolePage("/work",owner);assert.match(reviewerHtml,/#work-list \[data-work-action\]\{display:none\}/);assert.match(ownerHtml,/工作区工作/);assert.doesNotMatch(ownerHtml,/#work-list \[data-work-action\]\{display:none\}/);});
test("My Work exposes the source-backed cross-application exception center",async()=>{const html=await renderConsolePage("/work",owner);for(const value of ["异常与阻塞","/api/business/exceptions","Agent 阻塞","打开单据","work-exceptions"])assert.match(html,new RegExp(value));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["/api/business/exceptions","businessExceptions","applicationIds","canOperate","canControl"])assert.match(source,new RegExp(value));});
test("business APIs expose scoped PostgreSQL records and atomically governed assignment without a second scheduler",async()=>{const server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),executor=await readFile(new URL("../../../packages/domain-center/lib/persistent-business-work-executor.mjs",import.meta.url),"utf8"),source=server+executor;for(const route of ["/api/business/applications","/api/business/reports","/api/work","business-record-create","business-record-relate","business-related-record-create","related-records","createRelation","createRelatedRecord","business-work-assign","business-work-control","business.manage","canManageBusiness","business.work.control","canControl","includeAll:canManage","business-approval-request","business-approval-decision","approvalInbox","applicationReport","controlWorkItem","expectedWorkVersion","PersistentDomainWorkflowService","createBusinessTaskBinding","createBusinessApplicationRuntime","completeWorkflow","organizationId","workspaceId","record.schema.workflowDomainId","BUSINESS_RECORD_NOT_READY_FOR_AGENT"])assert.match(source,new RegExp(route.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(source,/class BusinessScheduler|new BusinessScheduler|domains\?\.\[0\]/);});
test("Agent assignment returns a durable queue response and a resident runner resumes it",async()=>{const server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),runner=await readFile(new URL("../../../packages/domain-center/lib/resident-business-work-runner.mjs",import.meta.url),"utf8");for(const value of ["enqueueBusinessWork","?\"QUEUED\"","sendJson(response,202","ResidentBusinessWorkRunner","businessWorkRunner.start()","businessWorkRunner.stop()","pg_try_advisory_lock","runnableAgentWorkItems"])assert.match(server+runner,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(server,/await service\.runDaemon\(\{pollMs:5,idleTimeoutMs:50/);});

test("business runner fleet is persistent, RBAC-governed and safely projected",async()=>{const server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),runner=await readFile(new URL("../../../packages/domain-center/lib/resident-business-work-runner.mjs",import.meta.url),"utf8"),registry=await readFile(new URL("../../../packages/domain-center/lib/business-runner-registry.mjs",import.meta.url),"utf8"),asset=await readFile(new URL("./assets/business-work-execution.js",import.meta.url),"utf8"),projection=await readFile(new URL("../../../packages/domain-center/lib/business-work-execution.mjs",import.meta.url),"utf8");for(const value of ["PostgresBusinessRunnerRegistry","business-runner-control","/api/business/runners","expectedVersion","DRAINING","runnerFleet","Resident Runner Fleet","Morning Report","morningReport"])assert.match(server+runner+registry+asset+projection,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const source of [runner,registry,asset,projection]){assert.doesNotMatch(source,/leaseToken/);assert.doesNotMatch(source,/fencingToken/);}});

test("business surfaces distinguish execution evidence from real professional outcomes",async()=>{const render=await readFile(new URL("./render.mjs",import.meta.url),"utf8"),asset=await readFile(new URL("./assets/business-work-execution.js",import.meta.url),"utf8"),result=await readFile(new URL("../../../packages/domain-center/lib/business-work-result.mjs",import.meta.url),"utf8");for(const value of ["EXECUTION_EVIDENCE","businessOutcomeProduced","仅执行证据","尚未生成专业业务结论","CONNECT_PROFESSIONAL_SKILL_RUNNER"])assert.match(render+asset+result,new RegExp(value));for(const source of [render,asset,result]){assert.doesNotMatch(source,/rawLog/);assert.doesNotMatch(source,/fencingToken/);}});

test("finance endpoint exposes the registered professional Skill Agent Runner result",async()=>{const render=await readFile(new URL("./render.mjs",import.meta.url),"utf8"),runner=await readFile(new URL("../../../packages/domain-center/lib/professional-business-skill-runner.mjs",import.meta.url),"utf8"),result=await readFile(new URL("../../../packages/domain-center/lib/business-work-result.mjs",import.meta.url),"utf8");for(const value of ["finance-expense-rule-runner-v1","financial_control_validation","finance-control-agent","FINANCE_EXPENSE_BUDGET_CHECK","PROFESSIONAL_RULE_ENGINE","SUBMIT_FOR_HUMAN_APPROVAL"])assert.match(render+runner+result,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(runner,/remainingBudget\s*:/);});

test("manufacturing endpoint exposes BOM SOP WMS evidence and the shared professional Runner",async()=>{const html=await renderConsolePage("/manufacturing",owner),runner=await readFile(new URL("../../../packages/domain-center/lib/professional-business-skill-runner.mjs",import.meta.url),"utf8"),relations=await readFile(new URL("../../../packages/domain-center/lib/business-relation-definitions.mjs",import.meta.url),"utf8"),result=await readFile(new URL("../../../packages/domain-center/lib/business-work-result.mjs",import.meta.url),"utf8"),source=html+runner+relations+result;for(const value of ["routing_sop","componentRequirements","USED_BY","GOVERNS","ALLOCATED_TO","manufacturing-work-order-readiness-runner-v1","production_release_readiness","manufacturing-readiness-agent","MANUFACTURING_WORK_ORDER_READINESS_CHECK","SUBMIT_WORK_ORDER_RELEASE_FOR_HUMAN_APPROVAL"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const value of ["reserve stock","release the work order automatically"])assert.match(runner,new RegExp(value));});

test("HR endpoint exposes the governed candidate-to-onboarding chain and non-decision Runner boundary",async()=>{const html=await renderConsolePage("/hr",owner),runner=await readFile(new URL("../../../packages/domain-center/lib/professional-business-skill-runner.mjs",import.meta.url),"utf8"),relations=await readFile(new URL("../../../packages/domain-center/lib/business-relation-definitions.mjs",import.meta.url),"utf8"),executor=await readFile(new URL("../../../packages/domain-center/lib/persistent-business-work-executor.mjs",import.meta.url),"utf8"),source=html+runner+relations+executor;for(const value of ["candidate_application","employment_offer","CONSIDERS","RECEIVES","INITIATES","AUTHORIZES","hr-onboarding-readiness-runner-v1","onboarding_administrative_readiness","hr-onboarding-control-agent","HR_ONBOARDING_ADMINISTRATIVE_READINESS_CHECK","SUBMIT_ONBOARDING_READINESS_FOR_HUMAN_APPROVAL"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const value of ["does not rank candidates","make an employment decision","Does not provision accounts"])assert.match(runner,new RegExp(value,"i"));assert.match(executor,/current\.path\.length>=3/);});

test("growth endpoint exposes product-grounded content and a non-publishing professional Runner",async()=>{const html=await renderConsolePage("/growth-sales",owner),runner=await readFile(new URL("../../../packages/domain-center/lib/professional-business-skill-runner.mjs",import.meta.url),"utf8"),relations=await readFile(new URL("../../../packages/domain-center/lib/business-relation-definitions.mjs",import.meta.url),"utf8"),result=await readFile(new URL("../../../packages/domain-center/lib/business-work-result.mjs",import.meta.url),"utf8"),source=html+runner+relations+result;for(const value of ["content_asset","channel_account","publish_plan","GROUNDS","PRODUCES","SCHEDULES","INCLUDES","AUTHORIZES","growth-publish-readiness-runner-v1","controlled_publish_readiness","growth-publishing-control-agent","GROWTH_CONTROLLED_PUBLISH_READINESS_CHECK","SUBMIT_PUBLISH_PLAN_FOR_HUMAN_APPROVAL"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const value of ["Does not register accounts","publish content","contact customers","PASS is not publication authorization"])assert.match(runner,new RegExp(value,"i"));assert.doesNotMatch(result,/credentialReferenceId:text/);});

test("strategy endpoint exposes evidence dates, corrective actions and its governed professional Runner",async()=>{const html=await renderConsolePage("/strategy",owner),runner=await readFile(new URL("../../../packages/domain-center/lib/professional-business-skill-runner.mjs",import.meta.url),"utf8"),relations=await readFile(new URL("../../../packages/domain-center/lib/business-relation-definitions.mjs",import.meta.url),"utf8"),result=await readFile(new URL("../../../packages/domain-center/lib/business-work-result.mjs",import.meta.url),"utf8"),source=html+runner+relations+result;for(const value of ["数据截止日","实际值证据编号","当前进度","纠偏动作","证据截止日","EVIDENCED_IN","ASSESSED_IN","RESULTS_IN","CORRECTED_BY","strategy-review-evidence-runner-v1","strategy_review_evidence_validation","strategy-review-control-agent","STRATEGY_REVIEW_EVIDENCE_CHECK","SUBMIT_STRATEGY_REVIEW_FOR_HUMAN_APPROVAL"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const value of ["does not verify the external source","Does not invent actual values","approve a strategy conclusion","execute corrective actions"])assert.match(runner,new RegExp(value,"i"));assert.doesNotMatch(result,/actualEvidenceRef:text/);});

test("Smart Park endpoint exposes SLA completion evidence and its non-dispatching professional Runner",async()=>{const html=await renderConsolePage("/smart-park",owner),runner=await readFile(new URL("../../../packages/domain-center/lib/professional-business-skill-runner.mjs",import.meta.url),"utf8"),result=await readFile(new URL("../../../packages/domain-center/lib/business-work-result.mjs",import.meta.url),"utf8"),source=html+runner+result;for(const value of ["受理时间","优先级","责任班组","处理结果","完工证据编号","完成时间","park-service-completion-runner-v1","park_service_completion_validation","park-service-control-agent","PARK_SERVICE_COMPLETION_CHECK","SUBMIT_SERVICE_COMPLETION_FOR_HUMAN_APPROVAL"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const value of ["Does not verify external evidence content","dispatch field staff","mark the order resolved","notify a tenant","create a charge"])assert.match(runner,new RegExp(value,"i"));assert.doesNotMatch(result,/completionEvidenceRef:text/);});

test("cockpit and My Work expose one scoped persistent professional result center",async()=>{const cockpit=await renderConsolePage("/cockpit",owner),work=await renderConsolePage("/work",owner),server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),store=await readFile(new URL("../../../packages/domain-center/lib/postgres-business-application-store.mjs",import.meta.url),"utf8"),source=cockpit+work+server+store;for(const value of ["专业业务结果","/api/business/results","professionalResults","applicationIds","evaluateConsoleRouteAccess","规则通过","需人工复核","证据阻塞","不使用任务完成数冒充业务成果"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(work,/保留来源、检查项和人工决策边界/);});

test("My Work exposes one validated Workflow Skill Agent Runner capability protocol",async()=>{const work=await renderConsolePage("/work",owner),server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),preview=await readFile(new URL("../../../packages/domain-center/lib/business-delegation-preview.mjs",import.meta.url),"utf8"),protocol=await readFile(new URL("../../../packages/domain-center/lib/business-capability-protocol.mjs",import.meta.url),"utf8"),source=work+server+preview+protocol;for(const value of ["智能能力协议","通用流程 Agent","专业业务 Agent","/api/business/capabilities","buildBusinessCapabilityProtocol","validateBusinessCapabilityProtocol","contractHash","skillContractId","requiredCapabilities","PROFESSIONAL_BUSINESS_OUTCOME","EXECUTION_EVIDENCE_ONLY"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(work,/人(?:工)?审批/);});
