import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {renderConsolePage} from "./render.mjs";import {consoleWebRoutes} from "./routes.mjs";import {enterpriseApplications} from "../../../packages/domain-center/lib/enterprise-applications.mjs";
const owner={authenticated:true,user:{user_id:"owner",display_name:"Owner"},capabilities:["*"],project_allowlist:["*"]};
test("business applications have independent conventional endpoints",async()=>{const routes=new Map(consoleWebRoutes.map(route=>[route.path,route.id]));for(const app of enterpriseApplications){assert.equal(routes.get(app.path),app.routeId);const html=await renderConsolePage(app.path,owner);if(app.path==="/development")assert.match(html,/真实自主开发/);else{assert.match(html,/业务台账/);assert.match(html,/新建业务记录/);assert.match(html,/Runtime 关闭时/);}}assert.equal(routes.get("/cockpit"),"cockpit");assert.equal(routes.get("/work"),"work");});
test("application route permission fails closed for the wrong persona",async()=>{const strategyUser={authenticated:true,user:{user_id:"strategy-user"},capabilities:["console.access","work.read","strategy.read"],project_allowlist:["*"]};assert.match(await renderConsolePage("/strategy",strategyUser),/战略执行平台/);const denied=await renderConsolePage("/finance",strategyUser);assert.match(denied,/当前账号未开通此模块/);assert.match(denied,/finance\.read/);});
test("strategy, HR and finance render domain-specific conventional forms",async()=>{const strategy=await renderConsolePage("/strategy",owner),hr=await renderConsolePage("/hr",owner),finance=await renderConsolePage("/finance",owner);assert.match(strategy,/战略周期/);assert.match(strategy,/责任中心/);assert.match(hr,/用人部门/);assert.match(hr,/招聘岗位/);assert.match(finance,/费用日期/);assert.match(finance,/预算科目/);for(const html of [strategy,hr,finance]){assert.match(html,/data-business-field/);assert.match(html,/data-transition/);assert.match(html,/availableTransitions/);assert.match(html,/上下游业务链/);assert.match(html,/data-create-relation/);assert.match(html,/创建下游业务单据/);assert.match(html,/data-create-related-record/);assert.match(html,/data-related-field/);}});
test("growth, manufacturing and Smart Park render operational domain forms",async()=>{const growth=await renderConsolePage("/growth-sales",owner),manufacturing=await renderConsolePage("/manufacturing",owner),park=await renderConsolePage("/smart-park",owner);assert.match(growth,/线索来源/);assert.match(growth,/联系授权/);assert.match(growth,/赢单概率/);assert.match(manufacturing,/计划数量/);assert.match(manufacturing,/BOM/);assert.match(manufacturing,/严重度/);assert.match(park,/服务企业/);assert.match(park,/统一社会信用代码/);assert.match(park,/计量倍率/);});
test("group cockpit renders source-backed business chain counts",async()=>{const html=await renderConsolePage("/",owner);assert.match(html,/businessChains/);assert.match(html,/业务链/);});
test("group cockpit renders an idempotent source-backed action feed",async()=>{const html=await renderConsolePage("/",owner);for(const value of ["行动提醒","/api/business/notifications","关键异常","需要审批","没有虚构“未读”状态"])assert.match(html,new RegExp(value));});
test("group cockpit searches authoritative records across only visible applications",async()=>{const html=await renderConsolePage("/",owner);for(const value of ["查找业务记录","/api/business/search","编号、标题或负责人","打开记录","business-search-results"])assert.match(html,new RegExp(value));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["searchRecords","applicationIds","ownerId","evaluateConsoleRouteAccess"])assert.match(source,new RegExp(value));});
test("business record detail renders authoritative Skill Agent Runner Attempt and sanitized Runtime evidence",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["executionEvidence","businessSkillId","skillType","agentId","runner?.workerKey","runtimeType","Attempt","runtimeResult","Result"]){assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));}assert.doesNotMatch(html,/leaseToken/);});
test("business record detail supports versioned edits only when the source object is editable",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["编辑业务记录","data-save-business-record","data-edit-field","expectedVersion","method:'PATCH'","business-edit-owner"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["business-record-update","updateRecord","request.method===\"PATCH\""])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("business record detail adds version-bound audited notes through the existing timeline",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["添加处理备注","business-record-note","data-add-business-note","写入时间线","/notes","expectedVersion"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["business-record-note","addRecordNote","/notes$"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("business workbenches use server-filtered paginated authoritative record lists",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["business-filter-query","business-filter-type","business-filter-status","business-filter-owner","data-business-page","pagination.total","URLSearchParams","offset"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["recordPage","url.searchParams.get(\"q\")","url.searchParams.get(\"ownerId\")","url.searchParams.get(\"offset\")"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});

test("Agent delegation shows an exact-version Workflow Skill Agent Runner preflight",async()=>{const html=await renderConsolePage("/finance",owner);for(const value of ["Agent Delegation Preflight","business-delegation-dialog","delegation-preview","Workflow · Skill · Agent · Runner","expectedObjectVersion","executionRuntime","确认委派","委派方案已确认","business.work.delegation-approved"])assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["buildBusinessDelegationPreview","businessDelegationPreview","BUSINESS_DELEGATION_BLOCKED","expectedObjectVersion","BUSINESS_RECORD_VERSION_CONFLICT","delegationPlan"])assert.match(source,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));});
test("approved Agent plans are visibly projected from immutable audit evidence",async()=>{const finance=await renderConsolePage("/finance",owner),work=await renderConsolePage("/work",owner);for(const value of ["已批准智能执行方案","delegationPlan.domainId","delegationPlan.workflowDefinitionId","delegationPlan.stages","delegationPlan.executionRuntime","不可变委派审计"])assert.match(finance+work,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const html of [finance,work]){assert.doesNotMatch(html,/leaseToken/);assert.doesNotMatch(html,/fencingToken/);}});
test("business users see a Kernel-backed online execution projection",async()=>{const finance=await renderConsolePage("/finance",owner),work=await renderConsolePage("/work",owner),asset=await readFile(new URL("./assets/business-work-execution.js",import.meta.url),"utf8"),projection=await readFile(new URL("../../../packages/domain-center/lib/business-work-execution.mjs",import.meta.url),"utf8");for(const value of ["在线执行状态","Agent 在线执行","business-work-execution.js","work-execution-live","execution.phase","execution.progress","AUTONOMOUS_KERNEL","自动刷新"])assert.match(finance+work+asset+projection,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const source of [finance,work,asset,projection]){assert.doesNotMatch(source,/leaseToken/);assert.doesNotMatch(source,/fencingToken/);}});
test("My Work hides Agent controls from approval-only users and exposes workspace management to owners",async()=>{const reviewer={authenticated:true,user:{user_id:"finance-reviewer"},capabilities:["console.access","work.read","finance.read","business.operate","proposal.approve"],project_allowlist:["*"]},reviewerHtml=await renderConsolePage("/work",reviewer),ownerHtml=await renderConsolePage("/work",owner);assert.match(reviewerHtml,/#work-list \[data-work-action\]\{display:none\}/);assert.match(ownerHtml,/工作区工作/);assert.doesNotMatch(ownerHtml,/#work-list \[data-work-action\]\{display:none\}/);});
test("My Work exposes the source-backed cross-application exception center",async()=>{const html=await renderConsolePage("/work",owner);for(const value of ["异常与阻塞","/api/business/exceptions","Agent 阻塞","打开单据","work-exceptions"])assert.match(html,new RegExp(value));const source=await readFile(new URL("./server.mjs",import.meta.url),"utf8");for(const value of ["/api/business/exceptions","businessExceptions","applicationIds","canOperate","canControl"])assert.match(source,new RegExp(value));});
test("business APIs expose scoped PostgreSQL records and atomically governed assignment without a second scheduler",async()=>{const server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),executor=await readFile(new URL("../../../packages/domain-center/lib/persistent-business-work-executor.mjs",import.meta.url),"utf8"),source=server+executor;for(const route of ["/api/business/applications","/api/business/reports","/api/work","business-record-create","business-record-relate","business-related-record-create","related-records","createRelation","createRelatedRecord","business-work-assign","business-work-control","business.manage","canManageBusiness","business.work.control","canControl","includeAll:canManage","business-approval-request","business-approval-decision","approvalInbox","applicationReport","controlWorkItem","expectedWorkVersion","PersistentDomainWorkflowService","createBusinessTaskBinding","createBusinessApplicationRuntime","completeWorkflow","organizationId","workspaceId","record.schema.workflowDomainId","BUSINESS_RECORD_NOT_READY_FOR_AGENT"])assert.match(source,new RegExp(route.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(source,/class BusinessScheduler|new BusinessScheduler|domains\?\.\[0\]/);});
test("Agent assignment returns a durable queue response and a resident runner resumes it",async()=>{const server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),runner=await readFile(new URL("../../../packages/domain-center/lib/resident-business-work-runner.mjs",import.meta.url),"utf8");for(const value of ["enqueueBusinessWork","?\"QUEUED\"","sendJson(response,202","ResidentBusinessWorkRunner","businessWorkRunner.start()","businessWorkRunner.stop()","pg_try_advisory_lock","runnableAgentWorkItems"])assert.match(server+runner,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(server,/await service\.runDaemon\(\{pollMs:5,idleTimeoutMs:50/);});

test("business runner fleet is persistent, RBAC-governed and safely projected",async()=>{const server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),runner=await readFile(new URL("../../../packages/domain-center/lib/resident-business-work-runner.mjs",import.meta.url),"utf8"),registry=await readFile(new URL("../../../packages/domain-center/lib/business-runner-registry.mjs",import.meta.url),"utf8"),asset=await readFile(new URL("./assets/business-work-execution.js",import.meta.url),"utf8"),projection=await readFile(new URL("../../../packages/domain-center/lib/business-work-execution.mjs",import.meta.url),"utf8");for(const value of ["PostgresBusinessRunnerRegistry","business-runner-control","/api/business/runners","expectedVersion","DRAINING","runnerFleet","Resident Runner Fleet","Morning Report","morningReport"])assert.match(server+runner+registry+asset+projection,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const source of [runner,registry,asset,projection]){assert.doesNotMatch(source,/leaseToken/);assert.doesNotMatch(source,/fencingToken/);}});
