import test from "node:test";
import assert from "node:assert/strict";
import { buildBusinessCapabilityProtocol, validateBusinessCapabilityProtocol, validateCompiledWorkflowAgainstProtocol } from "../lib/business-capability-protocol.mjs";
import { compileDomainWorkflow, domainCenterSummary, loadDomainRuntimeRegistry } from "../lib/domain-center.mjs";
import { getEnterpriseApplication } from "../lib/enterprise-applications.mjs";

const cases=[
  ["enterprise-strategy-platform","strategy-execution","strategy_review","strategy-review-evidence-runner-v1"],
  ["human-resources-platform","human-resources","onboarding_case","hr-onboarding-readiness-runner-v1"],
  ["finance-platform","finance-management","expense","finance-expense-rule-runner-v1"],
  ["ai-growth-sales-platform","publishing-distribution","publish_plan","growth-publish-readiness-runner-v1"],
  ["intelligent-manufacturing-erp","production-planning","work_order","manufacturing-work-order-readiness-runner-v1"],
  ["smart-park-platform","tenant-service-workflow","service_order","park-service-completion-runner-v1"]
];

test("six business workflows bind generic execution roles to distinct professional Agent Runner contracts",async()=>{const registry=await loadDomainRuntimeRegistry(),catalog=domainCenterSummary();for(const [applicationId,domainId,objectType,runnerId] of cases){const application=getEnterpriseApplication(applicationId),domain=catalog.applications.find(item=>item.id===applicationId).domains.find(item=>item.id===domainId),protocol=buildBusinessCapabilityProtocol({application,domain,record:{objectType},registry});validateBusinessCapabilityProtocol(protocol);assert.equal(protocol.status,"READY",`${applicationId}:${protocol.errors}`);assert.equal(protocol.outcomeMode,"PROFESSIONAL_BUSINESS_OUTCOME");assert.equal(protocol.professionalStage.runnerId,runnerId);assert.equal(protocol.professionalStage.humanApprovalRequired,true);assert.equal(protocol.stages.length,4);assert.ok(protocol.stages.every(stage=>stage.agent.agentId&&stage.runner.workerKey&&stage.implementationSkill.skillId));assert.notEqual(protocol.professionalStage.agentId,protocol.stages[0].agent.agentId);}});

test("capability protocol fails closed when an implementation Skill loses Agent or Runner capacity",async()=>{const base=await loadDomainRuntimeRegistry(),registry={...base,agentRegistry:{...base.agentRegistry,agents:[]},workerRegistry:{...base.workerRegistry,workers:[]}},catalog=domainCenterSummary(),application=getEnterpriseApplication("finance-platform"),domain=catalog.applications.find(item=>item.id===application.id).domains.find(item=>item.id==="finance-management"),protocol=buildBusinessCapabilityProtocol({application,domain,record:{objectType:"expense"},registry});assert.equal(protocol.status,"BLOCKED");assert.ok(protocol.errors.some(item=>item.includes("NO_ACTIVE_AGENT")));assert.ok(protocol.errors.some(item=>item.includes("NO_AVAILABLE_WORKER")));assert.throws(()=>validateBusinessCapabilityProtocol(protocol),error=>error.code==="BUSINESS_CAPABILITY_PROTOCOL_BLOCKED");});

test("objects without a professional runner remain honestly execution-evidence-only",async()=>{const registry=await loadDomainRuntimeRegistry(),catalog=domainCenterSummary(),application=getEnterpriseApplication("finance-platform"),domain=catalog.applications.find(item=>item.id===application.id).domains.find(item=>item.id==="finance-management"),protocol=buildBusinessCapabilityProtocol({application,domain,record:{objectType:"receivable"},registry});assert.equal(protocol.status,"READY");assert.equal(protocol.outcomeMode,"EXECUTION_EVIDENCE_ONLY");assert.equal(protocol.professionalStage,null);assert.deepEqual(protocol.warnings,["NO_PROFESSIONAL_OUTCOME_RUNNER:receivable"]);});

test("capability protocol hash rejects a modified Agent or Runner assignment",async()=>{const registry=await loadDomainRuntimeRegistry(),catalog=domainCenterSummary(),application=getEnterpriseApplication("finance-platform"),domain=catalog.applications.find(item=>item.id===application.id).domains.find(item=>item.id==="finance-management"),protocol=buildBusinessCapabilityProtocol({application,domain,record:{objectType:"expense"},registry}),tampered={...protocol,stages:protocol.stages.map((stage,index)=>index?stage:{...stage,agent:{...stage.agent,agentId:"unapproved-agent"}})};assert.throws(()=>validateBusinessCapabilityProtocol(tampered),error=>error.code==="BUSINESS_CAPABILITY_PROTOCOL_HASH_MISMATCH");});

test("compiled Kernel Task assignments must match the approved capability protocol",async()=>{const registry=await loadDomainRuntimeRegistry(),catalog=domainCenterSummary(),application=getEnterpriseApplication("finance-platform"),domain=catalog.applications.find(item=>item.id===application.id).domains.find(item=>item.id==="finance-management"),protocol=buildBusinessCapabilityProtocol({application,domain,record:{objectType:"expense"},registry}),workflow=compileDomainWorkflow("审核费用",registry,{explicitDomainId:domain.id,goalId:"capability-goal"});assert.equal(validateCompiledWorkflowAgainstProtocol(workflow,protocol),workflow);const changed={...workflow,tasks:workflow.tasks.map((task,index)=>index?task:{...task,metadata:{...task.metadata,workerKey:"changed-worker"}})};assert.throws(()=>validateCompiledWorkflowAgainstProtocol(changed,protocol),error=>error.code==="BUSINESS_CAPABILITY_ASSIGNMENT_MISMATCH");});
