import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { createTestPool, ensurePostgresFixture } from "../../orchestrator-core/lib/postgres-fixture.mjs";
import { PersistentNightShiftService } from "../../orchestrator-core/lib/persistent-night-shift.mjs";
import { createBusinessApplicationRuntime } from "../lib/business-database.mjs";
import { loadDomainRuntimeRegistry } from "../lib/domain-center.mjs";
import { PersistentBusinessWorkExecutor } from "../lib/persistent-business-work-executor.mjs";
import { ResidentBusinessWorkRunner } from "../lib/resident-business-work-runner.mjs";

test("two resident runners persist three cross-application professional outcomes exactly once and survive restart",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`portfolio-fixture-org-${suffix}`,workspaceId:`portfolio-fixture-workspace-${suffix}`,projectId:"enterprise-portfolio-fixture",userId:"portfolio-operator"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,registry=await loadDomainRuntimeRegistry(),night=new PersistentNightShiftService(pool),specs=[
      {applicationId:"intelligent-manufacturing-erp",objectType:"manufacturing_cost",reviewState:"CALCULATING",agentId:"manufacturing-cost-control-agent",title:"P-001 七月制造成本",fields:{costPeriod:"2026-07",productCode:"P-001",plant:"一号工厂",materialCost:1000,laborCost:300,overheadCost:200,quantity:100,ledgerRef:"LEDGER-2026-07-P001"},outcomeType:"MANUFACTURING_COST_VALIDATION_CHECK",nextAction:"SUBMIT_MANUFACTURING_COST_FOR_HUMAN_APPROVAL"},
      {applicationId:"ai-growth-sales-platform",objectType:"transaction_handoff",reviewState:"VALIDATING",agentId:"growth-transaction-control-agent",title:"客户 A 交易交接",fields:{opportunityRef:"OPP-001",customerRef:"CUS-001",productCode:"P-001",quotedAmount:50000,currency:"CNY",commercialTermsRef:"TERMS-001",humanDecisionRef:"HUMAN-DEAL-001",targetSystem:"制造 ERP"},outcomeType:"TRANSACTION_HANDOFF_READINESS_CHECK",nextAction:"SUBMIT_TRANSACTION_HANDOFF_FOR_HUMAN_APPROVAL"},
      {applicationId:"smart-park-platform",objectType:"operating_review",reviewState:"ANALYZING",agentId:"park-operating-review-agent",title:"园区七月经营复盘",fields:{period:"2026-07",occupancyRate:91,collectionRate:96,serviceSlaRate:98,evidenceRef:"PARK-OPS-2026-07"},outcomeType:"PARK_OPERATING_REVIEW_CHECK",nextAction:"SUBMIT_PARK_OPERATING_REVIEW_FOR_HUMAN_APPROVAL"}
    ],attached=[];
    const advance=async(applicationId,record,statuses)=>{let current=record;for(const status of statuses)current=await store.transitionRecord(applicationId,current.id,{expectedVersion:current.version,status},scope);return current;},approve=async(applicationId,record,status)=>{const approval=await store.requestApproval(applicationId,record.id,{expectedVersion:record.version,requestedStatus:status},scope);return(await store.decideApproval(applicationId,approval.id,{decision:"APPROVED"},{...scope,userId:"portfolio-reviewer"})).record;};
    for(const [index,spec] of specs.entries()){
      const draft=await store.createRecord(spec.applicationId,{objectType:spec.objectType,title:spec.title,displayKey:`CROSS-${index+1}-${suffix}`,fields:spec.fields},scope),record=await store.transitionRecord(spec.applicationId,draft.id,{expectedVersion:draft.version,status:spec.reviewState},scope);
      if(spec.objectType==="manufacturing_cost"){const workOrderDraft=await store.createRecord(spec.applicationId,{objectType:"work_order",title:"P-001 完工工单",displayKey:`WO-${suffix}`,fields:{productCode:"P-001",quantity:100,unit:"台",dueDate:"2026-07-31",plant:"一号工厂",priority:"普通"}},scope),workOrder=await advance(spec.applicationId,workOrderDraft,["PLANNED","MATERIAL_CHECK","READY","RELEASED","IN_PRODUCTION","COMPLETED"]);await store.createRelation(spec.applicationId,workOrder.id,{targetRecordId:record.id,relationType:"COSTED_BY"},scope);}
      if(spec.objectType==="transaction_handoff"){const productWaiting=await advance(spec.applicationId,await store.createRecord(spec.applicationId,{objectType:"product",title:"P-001 产品",displayKey:`PROD-${suffix}`,fields:{productCode:"P-001",category:"工业产品",targetAudience:"制造企业",price:50000,evidence:"SPEC-P001"}},scope),["REVIEWING","WAITING_APPROVAL"]),product=await approve(spec.applicationId,productWaiting,"ACTIVE"),customer=await advance(spec.applicationId,await store.createRecord(spec.applicationId,{objectType:"customer",title:"客户 A",displayKey:"CUS-001",fields:{customerType:"企业",industry:"制造业",owner:"销售负责人",contactPreference:"仅人工联系",consentStatus:"已授权"}},scope),["ACTIVE"]),opportunityWaiting=await advance(spec.applicationId,await store.createRecord(spec.applicationId,{objectType:"opportunity",title:"客户 A 商机",displayKey:"OPP-001",fields:{customerName:"客户 A",productCode:"P-001",estimatedAmount:50000,probability:90,expectedCloseDate:"2026-07-31",owner:"销售负责人"}},scope),["DISCOVERY","PROPOSAL","WAITING_APPROVAL"]),negotiation=await approve(spec.applicationId,opportunityWaiting,"NEGOTIATION"),opportunity=await advance(spec.applicationId,negotiation,["WON"]);await store.createRelation(spec.applicationId,opportunity.id,{targetRecordId:record.id,relationType:"HANDS_OFF"},scope);await store.createRelation(spec.applicationId,customer.id,{targetRecordId:record.id,relationType:"PARTY_TO"},scope);await store.createRelation(spec.applicationId,product.id,{targetRecordId:record.id,relationType:"SOLD_AS"},scope);}
      if(spec.objectType==="operating_review"){const billWaiting=await advance(spec.applicationId,await store.createRecord(spec.applicationId,{objectType:"settlement_bill",title:"七月园区结算",displayKey:`BILL-${suffix}`,fields:{enterpriseName:"客户 A",billingPeriod:"2026-07",rentAmount:10000,energyAmount:1000,serviceAmount:500,currency:"CNY",contractRef:"LEASE-001"}},scope),["CALCULATING","WAITING_APPROVAL"]),billApproved=await approve(spec.applicationId,billWaiting,"APPROVED"),bill=await advance(spec.applicationId,billApproved,["ISSUED"]),serviceWaiting=await advance(spec.applicationId,await store.createRecord(spec.applicationId,{objectType:"service_order",title:"七月服务工单",displayKey:`SERVICE-${suffix}`,fields:{enterpriseName:"客户 A",serviceType:"企业服务",location:"A1",requestedAt:"2026-07-01T08:00",slaHours:8,priority:"一般",assignedTeam:"园区服务组",description:"例行服务",resolutionSummary:"按计划完成",completionEvidenceRef:"SERVICE-EVIDENCE-001",resolvedAt:"2026-07-01T12:00"}},scope),["OPEN","DISPATCHED","IN_PROGRESS","WAITING_APPROVAL"]),service=await approve(spec.applicationId,serviceWaiting,"RESOLVED");await store.createRelation(spec.applicationId,bill.id,{targetRecordId:record.id,relationType:"SUMMARIZED_IN"},scope);await store.createRelation(spec.applicationId,service.id,{targetRecordId:record.id,relationType:"ASSESSED_IN"},scope);}
      const work=await store.createWorkItem({applicationId:spec.applicationId,businessObjectId:record.id,assignmentType:"AGENT",assigneeId:spec.agentId,idempotencyKey:`cross-application:${suffix}:${index}`},scope),sessionKey=`cross-application-${suffix}-${index}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:spec.title,scope}),running=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version});attached.push({spec,record,work:running,session});
    }
    const executor=new PersistentBusinessWorkExecutor({store,registry,acquirePool:async()=>({pool,ownsPool:false})}),runnerStore={getWorkItemForRunner:id=>store.getWorkItemForRunner(id),runnableAgentWorkItems:async()=>{const items=await Promise.all(attached.map(item=>store.getWorkItemForRunner(item.work.id)));return items.filter(item=>item?.status==="RUNNING");}},first=new ResidentBusinessWorkRunner({store:runnerStore,pool,nodeKey:`cross-a-${suffix}`,executeWork:item=>executor.execute(item)}),second=new ResidentBusinessWorkRunner({store:runnerStore,pool,nodeKey:`cross-b-${suffix}`,executeWork:item=>executor.execute(item)});await Promise.all([first.tick(),second.tick()]);
    assert.equal(first.snapshot().claimed+second.snapshot().claimed,3,JSON.stringify({first:first.snapshot(),second:second.snapshot()}));assert.equal(first.snapshot().completed+second.snapshot().completed,3,JSON.stringify({first:first.snapshot(),second:second.snapshot()}));
    const restarted=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,attemptEvidence=(await pool.query("SELECT count(DISTINCT t.id) task_count,count(a.id) attempt_count,max(per_task.attempts) max_attempts FROM ad_task t LEFT JOIN ad_task_attempt a ON a.task_id=t.id LEFT JOIN LATERAL(SELECT count(*) attempts FROM ad_task_attempt x WHERE x.task_id=t.id)per_task ON true WHERE t.goal_id=ANY($1::uuid[])",[attached.map(item=>item.session.goal_id)])).rows[0];let reportTasks=0;
    for(const item of attached){const persisted=await restarted.getWorkItemForRunner(item.work.id),record=await restarted.getRecord(item.spec.applicationId,item.record.id,scope),report=await night.loadReport(item.session.id);assert.equal(persisted.status,"WAITING_APPROVAL");assert.equal(record.status,"WAITING_APPROVAL");assert.equal(persisted.resultSummary.resultType,"PROFESSIONAL_BUSINESS_OUTCOME");assert.equal(persisted.resultSummary.professionalOutcome.outcomeType,item.spec.outcomeType);assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.nextAction,item.spec.nextAction);assert.equal(report.sessionStatus,"SUCCEEDED");reportTasks+=Number(report.totalTasks);}
    assert.equal(Number(attemptEvidence.task_count),reportTasks);assert.equal(Number(attemptEvidence.attempt_count),reportTasks);assert.equal(Number(attemptEvidence.max_attempts),1);assert.deepEqual(await runnerStore.runnableAgentWorkItems(),[]);
  }finally{await pool.end();}
});
