import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import {
  createTestPool,
  ensurePostgresFixture,
} from "../../orchestrator-core/lib/postgres-fixture.mjs";
import { createBusinessApplicationRuntime } from "../lib/business-database.mjs";
import { migrateGrowthPlatform } from "../lib/growth-database.mjs";
import { PostgresBusinessSourceGovernance } from "../lib/postgres-business-source-governance.mjs";
import { PostgresBusinessDataConnectorStore } from "../lib/postgres-business-data-connector.mjs";

test("growth source readiness validates and bounds evidence before SQL",async()=>{let queries=0,getterCalls=0;const governance=new PostgresBusinessSourceGovernance({pool:{async query(){queries+=1;throw new Error("must not query");}},clock:()=>new Date(Number.NaN)}),scope={organizationId:"org",workspaceId:"growth",tenantId:"tenant"},getterOptions=Object.defineProperty({},'applicationId',{enumerable:true,get(){getterCalls+=1;return 'ai-growth-sales-platform';}});await assert.rejects(()=>governance.tenantReadiness(scope,getterOptions),error=>error.code==="BUSINESS_SOURCE_TENANT_READINESS_OPTIONS_INVALID");await assert.rejects(()=>governance.tenantReadiness(scope,{applicationId:"ai-growth-sales-platform"}),error=>error.code==="BUSINESS_SOURCE_TENANT_READINESS_CLOCK_INVALID");await assert.rejects(()=>governance.tenantReadiness({...scope,organizationId:123},{applicationId:"ai-growth-sales-platform"}),error=>error.code==="BUSINESS_SOURCE_TENANT_READINESS_SCOPE_REQUIRED");await assert.rejects(()=>governance.tenantReadiness(scope,{applicationId:123}),error=>error.code==="BUSINESS_SOURCE_TENANT_READINESS_SCOPE_REQUIRED");await assert.rejects(()=>governance.tenantReadiness(scope,{applicationId:"ai-growth-sales-platform",limit:"100"}),error=>error.code==="BUSINESS_SOURCE_TENANT_READINESS_LIMIT_INVALID");assert.equal(queries,0);assert.equal(getterCalls,0);let values,sql;const bounded=new PostgresBusinessSourceGovernance({pool:{async query(statement,params){sql=statement;values=params;return{rows:[]};}},clock:()=>new Date("2026-08-26T00:00:00Z")});await bounded.tenantReadiness(scope,{applicationId:"ai-growth-sales-platform",limit:999});assert.match(sql,/LIMIT \$5/);assert.equal(values[4],100);});

test("growth source approval writes validate before SQL",async()=>{let queries=0,getterCalls=0;const governance=new PostgresBusinessSourceGovernance({pool:{async query(){queries+=1;throw new Error('must not query');}},clock:()=>new Date('2026-08-26T00:00:00Z')}),actor={organizationId:'org',workspaceId:'growth',userId:'data-owner'},getterInput=Object.defineProperty({tenantId:'tenant',dataOwnerId:'data-owner',expiresAt:'2026-08-27T00:00:00Z'},'mappingVersion',{enumerable:true,get(){getterCalls+=1;return 'v1';}});await assert.rejects(()=>governance.request('connector-1',getterInput,actor),error=>error.code==='BUSINESS_SOURCE_APPROVAL_INPUT_INVALID');await assert.rejects(()=>governance.request(123,{tenantId:'tenant',dataOwnerId:'data-owner',mappingVersion:'v1',expiresAt:'2026-08-27T00:00:00Z'},actor),error=>error.code==='BUSINESS_SOURCE_APPROVAL_CONNECTOR_INVALID');await assert.rejects(()=>governance.request('connector-1',{tenantId:'tenant',dataOwnerId:'data-owner',mappingVersion:'token=secret',expiresAt:'2026-08-27T00:00:00Z'},actor),error=>error.code==='BUSINESS_SOURCE_APPROVAL_MAPPING_INVALID');await assert.rejects(()=>governance.request('connector-1',{tenantId:'tenant',dataOwnerId:'data-owner',mappingVersion:'v1',expiresAt:{valueOf:()=>Date.now()}},actor),error=>error.code==='BUSINESS_SOURCE_APPROVAL_EXPIRY_INVALID');await assert.rejects(()=>governance.decide('approval-1',{decision:'APPROVED',expectedVersion:'1'},actor),error=>error.code==='BUSINESS_SOURCE_APPROVAL_VERSION_INVALID');await assert.rejects(()=>governance.decide('approval-1',{decision:'APPROVED',expectedVersion:1,reason:'token=secret'},actor),error=>error.code==='BUSINESS_SOURCE_APPROVAL_REASON_INVALID');assert.equal(queries,0);assert.equal(getterCalls,0);});

test("growth source approval requests converge on the pending tenant row",async()=>{let calls=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},approval={id:'approval-1',connector_id:'connector-1',tenant_id:'tenant',data_owner_id:'data-owner',mapping_version:'map-v1',expires_at:new Date('2026-08-27T00:00:00Z'),status:'PENDING',requested_by:'data-owner',requested_at:now,decided_by:null,decided_at:null,decision_reason:null,version:1},pool={async query(sql){calls+=1;if(sql.startsWith('SELECT * FROM business_data_connector'))return{rows:[connector]};if(sql.startsWith('INSERT INTO business_data_source_approval'))throw Object.assign(new Error('duplicate pending'),{code:'23505',constraint:'uq_business_source_pending_approval_tenant'});return{rows:calls===2?[]:[approval]};}},governance=new PostgresBusinessSourceGovernance({pool,clock:()=>now}),result=await governance.request('connector-1',{tenantId:'tenant',dataOwnerId:'data-owner',mappingVersion:'map-v1',expiresAt:'2026-08-27T00:00:00Z'},{organizationId:'org',workspaceId:'growth',userId:'data-owner'});assert.equal(result.id,'approval-1');assert.equal(calls,4);});

test("growth source approval request verifies returned scope",async()=>{let calls=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},approval={id:'approval-1',connector_id:'connector-1',tenant_id:'tenant-b',data_owner_id:'data-owner',mapping_version:'map-v1',expires_at:new Date('2026-08-27T00:00:00Z'),status:'PENDING',requested_by:'data-owner',requested_at:now,decided_by:null,decided_at:null,decision_reason:null,version:1},governance=new PostgresBusinessSourceGovernance({clock:()=>now,pool:{async query(){calls+=1;return calls===1?{rows:[connector]}:{rows:[approval]};}}});await assert.rejects(()=>governance.request('connector-1',{tenantId:'tenant-a',dataOwnerId:'data-owner',mappingVersion:'map-v1',expiresAt:'2026-08-27T00:00:00Z'},{organizationId:'org',workspaceId:'growth',userId:'data-owner'}),error=>error.code==='BUSINESS_SOURCE_APPROVAL_SCOPE_EVIDENCE_INVALID');});

test("growth source approval decision verifies returned identity",async()=>{const now=new Date('2026-08-26T00:00:00Z'),row={id:'approval-other',connector_id:'connector-1',tenant_id:null,data_owner_id:'data-owner',mapping_version:'map-v1',expires_at:null,status:'APPROVED',requested_by:'data-owner',requested_at:now,decided_by:'data-owner',decided_at:now,decision_reason:null,version:2},governance=new PostgresBusinessSourceGovernance({clock:()=>now,pool:{async query(){return{rows:[row]};}}});await assert.rejects(()=>governance.decide('approval-1',{decision:'APPROVED',expectedVersion:1},{organizationId:'org',workspaceId:'growth',userId:'data-owner'}),error=>error.code==='BUSINESS_SOURCE_APPROVAL_DECISION_EVIDENCE_INVALID');});

test("growth source checkpoint validates reconciliation evidence before SQL",async()=>{let queries=0,getterCalls=0;const governance=new PostgresBusinessSourceGovernance({pool:{async query(){queries+=1;throw new Error('must not query');}},clock:()=>new Date('2026-08-26T00:00:00Z')}),scope={organizationId:'org',workspaceId:'growth'},base={batch:{id:'batch-1',observedAt:'2026-08-25T23:59:00Z'},sourceCursor:'cursor-1',sourceCount:1,mappedCount:1,rejectedCount:0,mappingVersion:'map-v1'},getterInput=Object.defineProperty({...base},'sourceCount',{enumerable:true,get(){getterCalls+=1;return 1;}});await assert.rejects(()=>governance.checkpoint('connector-1',getterInput,scope),error=>error.code==='BUSINESS_SOURCE_CHECKPOINT_INPUT_INVALID');await assert.rejects(()=>governance.checkpoint('connector-1',{...base,sourceCount:'1'},scope),error=>error.code==='BUSINESS_SOURCE_CHECKPOINT_COUNT_INVALID');await assert.rejects(()=>governance.checkpoint('connector-1',{...base,sourceCursor:'token=secret'},scope),error=>error.code==='BUSINESS_SOURCE_CHECKPOINT_CURSOR_INVALID');await assert.rejects(()=>governance.checkpoint('connector-1',{...base,batch:{...base.batch,observedAt:'2026-08-26T00:06:00Z'}},scope),error=>error.code==='BUSINESS_SOURCE_CHECKPOINT_OBSERVED_AT_INVALID');assert.equal(queries,0);assert.equal(getterCalls,0);});

test("growth source checkpoint preserves tenant and requires matching approval",async()=>{let calls=0,approvalParams;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},approval={id:'approval-1',connector_id:'connector-1',tenant_id:'tenant-a',data_owner_id:'owner',mapping_version:'map-other',expires_at:new Date('2026-08-27T00:00:00Z'),status:'APPROVED',requested_by:'owner',requested_at:now,decided_by:'owner',decided_at:now,decision_reason:null,version:2},governance=new PostgresBusinessSourceGovernance({clock:()=>now,pool:{async query(sql,params){calls+=1;if(calls===1)return{rows:[connector]};approvalParams=params;return{rows:[approval]};}}}),input={batch:{id:'batch-1',observedAt:'2026-08-25T23:59:00Z'},sourceCursor:'cursor-1',sourceCount:1,mappedCount:1,rejectedCount:0,mappingVersion:'map-v1'};await assert.rejects(()=>governance.checkpoint('connector-1',input,{organizationId:'org',workspaceId:'growth',tenantId:'tenant-a'}),error=>error.code==='BUSINESS_SOURCE_CHECKPOINT_APPROVAL_INVALID');assert.deepEqual(approvalParams,['connector-1','tenant-a']);assert.equal(calls,2);});

test("growth source connector reads reject coerced controls and secret values",async()=>{let queries=0,getterCalls=0;const invalid=new PostgresBusinessSourceGovernance({pool:{async query(){queries+=1;throw new Error('must not query');}}}),getterScope=Object.defineProperty({organizationId:'org'},'workspaceId',{enumerable:true,get(){getterCalls+=1;return 'growth';}}),base={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')};await assert.rejects(()=>invalid.connector('connector-1',getterScope),error=>error.code==='BUSINESS_SOURCE_SCOPE_INVALID');await assert.rejects(()=>invalid.connector(123,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SOURCE_CONNECTOR_INVALID');await assert.rejects(()=>invalid.credentialReference('connector-1',{organizationId:{toString:()=>"org"},workspaceId:'growth'}),error=>error.code==='BUSINESS_SOURCE_ORGANIZATION_INVALID');assert.equal(queries,0);assert.equal(getterCalls,0);const poisoned=new PostgresBusinessSourceGovernance({pool:{async query(){return{rows:[{...base,credential_reference_id:'token=raw-secret'}]};}}});await assert.rejects(()=>poisoned.credentialReference('connector-1',{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SOURCE_CREDENTIAL_REFERENCE_INVALID');const getterRow=Object.defineProperty({...base},'status',{enumerable:true,get(){getterCalls+=1;return 'ACTIVE';}}),coercive=new PostgresBusinessSourceGovernance({pool:{async query(){return{rows:[getterRow]};}}});await assert.rejects(()=>coercive.connector('connector-1',{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SOURCE_CONNECTOR_EVIDENCE_INVALID');assert.equal(getterCalls,0);});

test("growth source readiness rejects poisoned database evidence",async()=>{const scope={organizationId:'org',workspaceId:'growth',tenantId:'tenant'},input={applicationId:'ai-growth-sales-platform'},governanceFor=rows=>new PostgresBusinessSourceGovernance({pool:{async query(){return{rows};}},clock:()=>new Date('2026-08-26T00:00:00Z')});await assert.rejects(()=>governanceFor([{id:'connector-1',credential_reference_id:'credential/ref',mapping_version:'map-v1',expires_at:{toString:()=>"2026-08-27T00:00:00Z"}}]).tenantReadiness(scope,input),error=>error.code==='BUSINESS_SOURCE_TENANT_READINESS_EVIDENCE_INVALID');await assert.rejects(()=>governanceFor([{id:'token=raw-secret',credential_reference_id:'credential/ref',mapping_version:'map-v1',expires_at:'2026-08-27T00:00:00Z'}]).tenantReadiness(scope,input),error=>error.code==='BUSINESS_SOURCE_TENANT_READINESS_CONNECTOR_INVALID');await assert.rejects(()=>governanceFor(Array.from({length:101},(_,index)=>({id:`connector-${index}`}))).tenantReadiness(scope,{...input,limit:999}),error=>error.code==='BUSINESS_SOURCE_TENANT_READINESS_EVIDENCE_INVALID');});

test("growth source readiness rejects coercive checkpoint evidence",async()=>{let calls=0,coercions=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',status:'ACTIVE',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},checkpoint={connector_id:'connector-1',organization_id:'org',workspace_id:'growth',source_cursor:'cursor-1',last_observed_at:now,last_batch_id:'11111111-1111-4111-8111-111111111111',source_count:{valueOf(){coercions+=1;return 1;}},mapped_count:'1',rejected_count:'0',reconciliation_status:'MATCHED',reconciliation_hash:'hash',updated_at:now},governance=new PostgresBusinessSourceGovernance({pool:{async query(){calls+=1;return calls===1?{rows:[connector]}:calls===2?{rows:[]}:{rows:[checkpoint]};}}});await assert.rejects(()=>governance.readiness('connector-1',{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SOURCE_CHECKPOINT_EVIDENCE_INVALID');assert.equal(coercions,0);});

test("growth source readiness validates approval before gate evaluation",async()=>{let calls=0,getterCalls=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',status:'ACTIVE',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},approval=Object.defineProperty({id:'approval-1',connector_id:'connector-1',tenant_id:null,data_owner_id:'owner',mapping_version:'map-v1',expires_at:null,requested_by:'owner',requested_at:now,decided_by:'owner',decided_at:now,decision_reason:null,version:2},'status',{enumerable:true,get(){getterCalls+=1;return 'APPROVED';}}),governance=new PostgresBusinessSourceGovernance({pool:{async query(){calls+=1;return calls===1?{rows:[connector]}:calls===2?{rows:[approval]}:{rows:[]};}}});await assert.rejects(()=>governance.readiness('connector-1',{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SOURCE_APPROVAL_EVIDENCE_INVALID');assert.equal(getterCalls,0);});

test("growth source readiness is exact-tenant and expiry gated",async()=>{let calls=0,approvalParams;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',status:'ACTIVE',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},approval={id:'approval-1',connector_id:'connector-1',tenant_id:'tenant-a',data_owner_id:'owner',mapping_version:'map-v1',expires_at:new Date('2026-08-25T00:00:00Z'),status:'APPROVED',requested_by:'owner',requested_at:now,decided_by:'owner',decided_at:now,decision_reason:null,version:2},governance=new PostgresBusinessSourceGovernance({clock:()=>now,pool:{async query(sql,params){calls+=1;if(calls===1)return{rows:[connector]};if(calls===2){approvalParams=params;return{rows:[approval]};}return{rows:[]};}}}),readiness=await governance.readiness('connector-1',{organizationId:'org',workspaceId:'growth',tenantId:'tenant-a'});assert.deepEqual(approvalParams,['connector-1','tenant-a']);assert.equal(readiness.status,'NOT_READY');assert.equal(readiness.checks.find(item=>item.id==='AUTHORIZATION_UNEXPIRED').pass,false);});

test("growth source readiness verifies returned approval tenant",async()=>{let calls=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm',status:'ACTIVE',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},approval={id:'approval-1',connector_id:'connector-1',tenant_id:'tenant-b',data_owner_id:'owner',mapping_version:'map-v1',expires_at:new Date('2026-08-27T00:00:00Z'),status:'APPROVED',requested_by:'owner',requested_at:now,decided_by:'owner',decided_at:now,decision_reason:null,version:2},governance=new PostgresBusinessSourceGovernance({clock:()=>now,pool:{async query(){calls+=1;return calls===1?{rows:[connector]}:calls===2?{rows:[approval]}:{rows:[]};}}});await assert.rejects(()=>governance.readiness('connector-1',{organizationId:'org',workspaceId:'growth',tenantId:'tenant-a'}),error=>error.code==='BUSINESS_SOURCE_READINESS_APPROVAL_SCOPE_INVALID');});

test("growth source approval presentation rejects poisoned rows",()=>{let getterCalls=0;const governance=new PostgresBusinessSourceGovernance({pool:{}}),base={id:'approval-1',connector_id:'connector-1',tenant_id:'tenant',data_owner_id:'owner-1',mapping_version:'map-v1',expires_at:new Date('2026-08-27T00:00:00Z'),status:'APPROVED',requested_by:'owner-1',requested_at:new Date('2026-08-26T00:00:00Z'),decided_by:'owner-1',decided_at:new Date('2026-08-26T00:01:00Z'),decision_reason:'approved',version:2},getterRow=Object.defineProperty({...base},'status',{enumerable:true,get(){getterCalls+=1;return 'APPROVED';}});assert.equal(governance.present(base).requestedAt,'2026-08-26T00:00:00.000Z');assert.throws(()=>governance.present(getterRow),error=>error.code==='BUSINESS_SOURCE_APPROVAL_EVIDENCE_INVALID');assert.equal(getterCalls,0);for(const row of [{...base,requested_by:'token=raw-secret'},{...base,decision_reason:'password=raw-secret'},{...base,expires_at:{toString:()=>"2026-08-27T00:00:00Z"}},{...base,version:'2'}])assert.throws(()=>governance.present(row),error=>error.code==='BUSINESS_SOURCE_APPROVAL_EVIDENCE_INVALID');});

test("growth source ingestion validates its envelope before SQL",async()=>{let queries=0,getterCalls=0;const pool={async query(){queries+=1;throw new Error('must not query');}},store=new PostgresBusinessDataConnectorStore({pool}),scope={organizationId:'org',workspaceId:'growth'},record={sourceRecordKey:'lead-1',objectType:'lead',displayKey:'LEAD-1',title:'Lead 1',ownerId:'sales',fields:{}},base={idempotencyKey:'batch-1',evidenceRef:'source://growth/batch-1',observedAt:'2026-08-26T00:00:00Z',records:[record]},getterFields=Object.defineProperty({},'value',{enumerable:true,get(){getterCalls+=1;return 'coerced';}}),getterInput=Object.defineProperty({...base},'idempotencyKey',{enumerable:true,get(){getterCalls+=1;return 'batch-1';}}),getterAuthorization=Object.defineProperty({approvalId:'approval-1',version:2,tenantId:'tenant-a'},'mappingVersion',{enumerable:true,get(){getterCalls+=1;return 'map-v1';}});await assert.rejects(()=>store.ingest(123,base,scope),error=>error.code==='BUSINESS_SYNC_CONNECTOR_INVALID');await assert.rejects(()=>store.ingest('connector-1',{...base,idempotencyKey:{toString:()=>"batch-1"}},scope),error=>error.code==='BUSINESS_SYNC_IDEMPOTENCY_INVALID');await assert.rejects(()=>store.ingest('connector-1',getterInput,scope),error=>error.code==='BUSINESS_SYNC_INPUT_INVALID');await assert.rejects(()=>store.ingest('connector-1',{...base,authorization:getterAuthorization},{...scope,tenantId:'tenant-a'}),error=>error.code==='BUSINESS_SYNC_AUTHORIZATION_INVALID');await assert.rejects(()=>store.ingest('connector-1',{...base,authorization:{approvalId:'approval-1',version:2,mappingVersion:'map-v1',tenantId:'tenant-b'}},{...scope,tenantId:'tenant-a'}),error=>error.code==='BUSINESS_SYNC_AUTHORIZATION_INVALID');await assert.rejects(()=>store.ingest('connector-1',{...base,records:[{...record,title:{toString:()=>"Lead 1"}}]},scope),error=>error.code==='BUSINESS_SYNC_TITLE_INVALID');await assert.rejects(()=>store.ingest('connector-1',{...base,records:[{...record,fields:getterFields}]},scope),error=>error.code==='BUSINESS_SYNC_FIELDS_INVALID');await assert.rejects(()=>store.ingest('connector-1',{...base,evidenceRef:'token=raw-secret'},scope),error=>error.code==='BUSINESS_SYNC_EVIDENCE_INVALID');await assert.rejects(()=>store.ingest('connector-1',base,{...scope,userId:{toString:()=>"operator"}}),error=>error.code==='BUSINESS_SYNC_ACTOR_INVALID');const invalidClock=new PostgresBusinessDataConnectorStore({pool,clock:()=>({getTime:()=>Date.now()})});await assert.rejects(()=>invalidClock.ingest('connector-1',base,scope),error=>error.code==='BUSINESS_SYNC_CLOCK_INVALID');assert.equal(queries,0);assert.equal(getterCalls,0);});

test("growth source ingestion rolls back poisoned existing evidence",async()=>{let rolledBack=false,mutations=0,rootQueries=0;const connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr-read-model',connector_type:'API',credential_reference_id:'credential/ref',status:'ACTIVE',allowed_object_types:['position'],freshness_seconds:3600,version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT * FROM business_application_record'))return{rows:[{id:'record-1',object_type:'position',version:1,source_observed_at:{valueOf:()=>0}}]};mutations+=1;return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;return rootQueries===1?{rows:[connector]}:{rows:[]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'batch-1',evidenceRef:'source://growth/batch-1',observedAt:'2026-08-25T23:59:00Z',records:[{sourceRecordKey:'position-1',objectType:'position',displayKey:'POS-1',title:'Position 1',ownerId:'hr',fields:{positionCode:'P1',positionName:'Position 1',department:'HR',jobFamily:'Operations',grade:'M1',headcount:1}}]};await assert.rejects(()=>store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SYNC_EXISTING_EVIDENCE_INVALID');assert.equal(rolledBack,true);assert.equal(mutations,0);});

test("growth source connector history reads are native and bounded",async()=>{let calls=0,sql='',getterCalls=0;const pool={async query(statement){calls+=1;sql=statement;return{rows:[]};}},store=new PostgresBusinessDataConnectorStore({pool}),getterScope=Object.defineProperty({workspaceId:'growth'},'organizationId',{enumerable:true,get(){getterCalls+=1;return 'org';}});await assert.rejects(()=>store.list(getterScope),error=>error.code==='BUSINESS_CONNECTOR_SCOPE_INVALID');await assert.rejects(()=>store.batches(123,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_CONNECTOR_ID_INVALID');assert.equal(calls,0);assert.equal(getterCalls,0);assert.deepEqual(await store.list({organizationId:'org',workspaceId:'growth'}),[]);assert.match(sql,/LIMIT 100$/);assert.deepEqual(await store.batches('connector-1',{organizationId:'org',workspaceId:'growth'}),[]);assert.match(sql,/LIMIT 50/);});

test("growth source connector lists verify returned scope",async()=>{const connector={id:'connector-1',organization_id:'foreign-org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},store=new PostgresBusinessDataConnectorStore({pool:{async query(){return{rows:[connector]};}}});await assert.rejects(()=>store.list({organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_CONNECTOR_LIST_EVIDENCE_INVALID');await assert.rejects(()=>store.batches('connector-2',{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_CONNECTOR_BATCH_LIST_EVIDENCE_INVALID');});

test("growth source connector projections validate and redact evidence",()=>{const store=new PostgresBusinessDataConnectorStore({pool:{}}),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['lead'],freshness_seconds:3600,status:'ERROR',version:2,last_success_at:null,last_error_summary:'password=raw-secret',created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:01:00Z')},batch={id:'batch-1',connector_id:'connector-1',application_id:'ai-growth-sales-platform',idempotency_key:'sync-1',status:'FAILED',observed_at:new Date('2026-08-25T23:59:00Z'),source_cursor:null,received_count:1,applied_count:0,unchanged_count:0,error_count:1,error_summary:'token=raw-secret',created_at:new Date('2026-08-26T00:00:00Z'),completed_at:new Date('2026-08-26T00:00:01Z')};assert.equal(store.presentConnector(connector).lastErrorSummary,'BUSINESS_CONNECTOR_ERROR_REDACTED');assert.equal(store.presentBatch(batch).errorSummary,'BUSINESS_CONNECTOR_ERROR_REDACTED');assert.throws(()=>store.presentBatchForConnector({...batch,connector_id:'connector-2'},connector),error=>error.code==='BUSINESS_CONNECTOR_PROJECTION_EVIDENCE_INVALID');for(const value of [{...connector,created_at:{toString:()=>"2026-08-26T00:00:00Z"}},{...connector,allowed_object_types:['token=raw-secret']},{...batch,received_count:'1'},{...batch,status:'APPLIED',received_count:2,applied_count:1,unchanged_count:0,error_count:0}])assert.throws(()=>value.connector_id?store.presentBatch(value):store.presentConnector(value),error=>error.code==='BUSINESS_CONNECTOR_PROJECTION_EVIDENCE_INVALID');});

test("growth source connector registration validates before SQL",async()=>{let queries=0,getterCalls=0;const pool={async query(){queries+=1;throw new Error('must not query');}},base={id:'growth-source',applicationId:'ai-growth-sales-platform',sourceSystem:'crm-read-model',connectorType:'API',credentialReferenceId:'credential/ref',allowedObjectTypes:['lead'],freshnessSeconds:3600},scope={organizationId:'org',workspaceId:'growth',userId:'operator-1'},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),getterInput=Object.defineProperty({...base},'sourceSystem',{enumerable:true,get(){getterCalls+=1;return 'crm-read-model';}});await assert.rejects(()=>store.register(getterInput,scope),error=>error.code==='BUSINESS_CONNECTOR_INPUT_INVALID');await assert.rejects(()=>store.register({...base,connectorType:{toString:()=>"API"}},scope),error=>error.code==='BUSINESS_CONNECTOR_TYPE_INVALID');await assert.rejects(()=>store.register({...base,freshnessSeconds:'3600'},scope),error=>error.code==='BUSINESS_CONNECTOR_FRESHNESS_INVALID');await assert.rejects(()=>store.register({...base,allowedObjectTypes:[{toString:()=>"lead"}]},scope),error=>error.code==='BUSINESS_CONNECTOR_OBJECT_TYPE_INVALID');const invalidClock=new PostgresBusinessDataConnectorStore({pool,clock:()=>"2026-08-26T00:00:00Z"});await assert.rejects(()=>invalidClock.register(base,scope),error=>error.code==='BUSINESS_CONNECTOR_CLOCK_INVALID');assert.equal(queries,0);assert.equal(getterCalls,0);});

test("growth source ingestion validates connector evidence before batch lookup",async()=>{let queries=0;const poisoned={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'ai-growth-sales-platform',source_system:'crm-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:{[Symbol.iterator](){throw new Error('must not iterate');}},freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},pool={async query(){queries+=1;return{rows:[poisoned]};}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'batch-1',evidenceRef:'source://growth/batch-1',observedAt:'2026-08-26T00:00:00Z',records:[{sourceRecordKey:'lead-1',objectType:'lead',displayKey:'LEAD-1',title:'Lead 1',ownerId:'sales',fields:{}}]};await assert.rejects(()=>store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_CONNECTOR_PROJECTION_EVIDENCE_INVALID');assert.equal(queries,1);});

test("growth source authorization conflict rolls back before record access",async()=>{let rootQueries=0,rolledBack=false,recordQueries=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['position'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator',created_at:now,updated_at:now},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT id FROM business_data_source_approval'))return{rows:[]};recordQueries+=1;return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;return rootQueries===1?{rows:[connector]}:{rows:[{id:'unauthorized-duplicate'}]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>now}),input={idempotencyKey:'batch-1',evidenceRef:'source://growth/batch-1',observedAt:'2026-08-26T00:00:00Z',authorization:{approvalId:'approval-1',version:2,mappingVersion:'map-v1',tenantId:'tenant-a'},records:[{sourceRecordKey:'position-1',objectType:'position',displayKey:'POS-1',title:'Position 1',ownerId:'hr',fields:{positionCode:'P1',positionName:'Position 1',department:'HR',jobFamily:'Operations',grade:'M1',headcount:1}}]};await assert.rejects(()=>store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth',tenantId:'tenant-a'}),error=>error.code==='BUSINESS_SYNC_AUTHORIZATION_CONFLICT');assert.equal(rolledBack,true);assert.equal(recordQueries,0);assert.equal(rootQueries,1);});

test("growth failed managed batch authorizes before side effects",async()=>{let rolledBack=false,sideEffects=0;const now=new Date('2026-08-26T00:00:00Z'),connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform'},client={async query(sql){if(sql==='BEGIN')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT id FROM business_data_source_approval'))return{rows:[]};sideEffects+=1;return{rows:[]};},release(){}},store=new PostgresBusinessDataConnectorStore({pool:{async connect(){return client;},async query(){return{rows:[]};}}}),input={idempotencyKey:'bad-batch',evidenceRef:'source://growth/bad-batch',observedAt:now.toISOString(),sourceCursor:null,authorization:{approvalId:'approval-1',version:2,mappingVersion:'map-v1',tenantId:'tenant-a'},records:[{sourceRecordKey:'expense-1',objectType:'expense'}]};await assert.rejects(()=>store.failedBatch(connector,input,Object.assign(new Error('invalid'),{code:'BUSINESS_SYNC_OBJECT_TYPE_DENIED'}),'actor',now),error=>error.code==='BUSINESS_SYNC_AUTHORIZATION_CONFLICT');assert.equal(rolledBack,true);assert.equal(sideEffects,0);});

test("growth source ingestion rolls back poisoned mutation results",async()=>{let rootQueries=0,rolledBack=false,postMutationQueries=0;const connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['position'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT * FROM business_application_record'))return{rows:[]};if(sql.startsWith('INSERT INTO business_application_record'))return{rows:[{id:{toString:()=>"record-1"},version:1}]};postMutationQueries+=1;return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;return rootQueries===1?{rows:[connector]}:{rows:[]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'batch-1',evidenceRef:'source://growth/batch-1',observedAt:'2026-08-25T23:59:00Z',records:[{sourceRecordKey:'position-1',objectType:'position',displayKey:'POS-1',title:'Position 1',ownerId:'hr',fields:{positionCode:'P1',positionName:'Position 1',department:'HR',jobFamily:'Operations',grade:'M1',headcount:1}}]};await assert.rejects(()=>store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SYNC_MUTATION_EVIDENCE_INVALID');assert.equal(rolledBack,true);assert.equal(postMutationQueries,0);});

test("growth failed source batches update connector atomically",async()=>{let rootQueries=0,rolledBack=false;const connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['position'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT * FROM business_data_sync_batch'))return{rows:[]};if(sql.startsWith('INSERT INTO business_data_sync_batch'))return{rows:[{}]};if(sql.startsWith('UPDATE business_data_connector'))throw Object.assign(new Error('injected update failure'),{code:'INJECTED_UPDATE_FAILURE'});return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;return rootQueries===1?{rows:[connector]}:{rows:[]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'bad-batch',evidenceRef:'source://growth/bad-batch',observedAt:'2026-08-25T23:59:00Z',records:[{sourceRecordKey:'expense-1',objectType:'expense',displayKey:'EXP-1',title:'Denied object',ownerId:'finance',fields:{}}]};await assert.rejects(()=>store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='INJECTED_UPDATE_FAILURE');assert.equal(rolledBack,true);});

test("growth source ingestion cannot reactivate a revoked connector",async()=>{let rootQueries=0,rolledBack=false;const connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['position'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT * FROM business_data_sync_batch'))return{rows:[]};if(sql.startsWith('INSERT INTO business_data_sync_batch'))return{rows:[{}]};if(sql.startsWith('UPDATE business_data_connector'))return{rows:[]};return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;return rootQueries===1?{rows:[connector]}:{rows:[]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'bad-batch',evidenceRef:'source://growth/bad-batch',observedAt:'2026-08-25T23:59:00Z',records:[{sourceRecordKey:'expense-1',objectType:'expense',displayKey:'EXP-1',title:'Denied object',ownerId:'finance',fields:{}}]};await assert.rejects(()=>store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'}),error=>error.code==='BUSINESS_SYNC_CONNECTOR_TRANSITION_CONFLICT');assert.equal(rolledBack,true);});

test("growth source ingestion resolves only the batch idempotency race",async()=>{let rootQueries=0,rolledBack=false;const connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['position'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},batchRow={id:'batch-concurrent',connector_id:'connector-1',application_id:'human-resources-platform',idempotency_key:'batch-1',status:'APPLIED',observed_at:new Date('2026-08-25T23:59:00Z'),source_cursor:null,received_count:1,applied_count:1,unchanged_count:0,error_count:0,error_summary:null,created_at:new Date('2026-08-26T00:00:00Z'),completed_at:new Date('2026-08-26T00:00:00Z')},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT * FROM business_application_record'))return{rows:[]};if(sql.startsWith('INSERT INTO business_application_record'))return{rows:[{id:'record-1',version:1}]};if(sql.startsWith('INSERT INTO business_data_sync_batch'))throw Object.assign(new Error('duplicate batch'),{code:'23505',constraint:'business_data_sync_batch_connector_id_idempotency_key_key'});return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;if(rootQueries===1)return{rows:[connector]};if(rootQueries===2)return{rows:[]};return{rows:[batchRow]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'batch-1',evidenceRef:'source://growth/batch-1',observedAt:'2026-08-25T23:59:00Z',records:[{sourceRecordKey:'position-1',objectType:'position',displayKey:'POS-1',title:'Position 1',ownerId:'hr',fields:{positionCode:'P1',positionName:'Position 1',department:'HR',jobFamily:'Operations',grade:'M1',headcount:1}}]},result=await store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'});assert.equal(rolledBack,true);assert.equal(result.duplicate,true);assert.equal(result.batch.id,'batch-concurrent');});

test("growth failed source ingestion resolves its idempotency race",async()=>{let rootQueries=0,rolledBack=false;const connector={id:'connector-1',organization_id:'org',workspace_id:'growth',application_id:'human-resources-platform',source_system:'hr-read-model',connector_type:'API',credential_reference_id:'credential/ref',allowed_object_types:['position'],freshness_seconds:3600,status:'ACTIVE',version:1,last_success_at:null,last_error_summary:null,created_by:'operator-1',created_at:new Date('2026-08-26T00:00:00Z'),updated_at:new Date('2026-08-26T00:00:00Z')},batchRow={id:'failed-concurrent',connector_id:'connector-1',application_id:'human-resources-platform',idempotency_key:'bad-batch',status:'FAILED',observed_at:new Date('2026-08-25T23:59:00Z'),source_cursor:null,received_count:1,applied_count:0,unchanged_count:0,error_count:1,error_summary:'BUSINESS_SYNC_OBJECT_TYPE_DENIED',created_at:new Date('2026-08-26T00:00:00Z'),completed_at:new Date('2026-08-26T00:00:00Z')},client={async query(sql){if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql==='ROLLBACK'){rolledBack=true;return{rows:[]};}if(sql.startsWith('SELECT * FROM business_data_sync_batch'))return{rows:[]};if(sql.startsWith('INSERT INTO business_data_sync_batch'))throw Object.assign(new Error('duplicate batch'),{code:'23505',constraint:'business_data_sync_batch_connector_id_idempotency_key_key'});return{rows:[]};},release(){}},pool={async query(){rootQueries+=1;if(rootQueries===1)return{rows:[connector]};if(rootQueries===2)return{rows:[]};return{rows:[batchRow]};},async connect(){return client;}},store=new PostgresBusinessDataConnectorStore({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),input={idempotencyKey:'bad-batch',evidenceRef:'source://growth/bad-batch',observedAt:'2026-08-25T23:59:00Z',records:[{sourceRecordKey:'expense-1',objectType:'expense',displayKey:'EXP-1',title:'Denied object',ownerId:'finance',fields:{}}]},result=await store.ingest('connector-1',input,{organizationId:'org',workspaceId:'growth'});assert.equal(rolledBack,true);assert.equal(result.duplicate,true);assert.equal(result.batch.id,'failed-concurrent');});

test("growth data-owner approval is tenant scoped, expiring and credential-value free", async () => {
  await ensurePostgresFixture();
  const pool = createTestPool(),
    suffix = randomUUID(),
    scope = {
      organizationId: `source-approval-${suffix}`,
      workspaceId: "growth",
      tenantId: "tenant-a",
    },
    owner = { ...scope, userId: "growth-data-owner" };
  let now = new Date("2026-08-26T10:00:00Z");
  try {
    const runtime = await createBusinessApplicationRuntime({
      repoRoot: process.cwd(),
      pool,
    });
    await migrateGrowthPlatform(pool);
    const connector = await runtime.connectorStore.register(
        {
          id: `growth-source-${suffix}`,
          applicationId: "ai-growth-sales-platform",
          sourceSystem: "governed-growth-source",
          connectorType: "API",
          credentialReferenceId: "growth-source-credential-ref",
          allowedObjectTypes: ["lead"],
          freshnessSeconds: 3600,
        },
        owner,
      ),
      governance = new PostgresBusinessSourceGovernance({
        pool,
        clock: () => now,
      }),
      pending = await governance.request(
        connector.id,
        {
          tenantId: scope.tenantId,
          dataOwnerId: owner.userId,
          mappingVersion: "growth-map-v1",
          expiresAt: "2026-08-27T10:00:00Z",
        },
        owner,
      ),
      approved = await governance.decide(
        pending.id,
        {
          decision: "APPROVED",
          expectedVersion: pending.version,
          reason: "Approved tenant source mapping",
        },
        owner,
      );
    assert.equal(approved.status, "APPROVED");
    const ready = await governance.tenantReadiness(scope, {
      applicationId: "ai-growth-sales-platform",
    });
    assert.equal(ready.status, "READY");
    assert.deepEqual(ready.summary, { total: 1, ready: 1, blocked: 0 });
    assert.deepEqual(ready.safety, {
      credentialValuesRead: false,
      externalCallsPerformed: false,
    });
    const revoked = await governance.decide(
      approved.id,
      {
        decision: "REVOKED",
        expectedVersion: approved.version,
        reason: "Rotate the governed authorization",
      },
      owner,
    );
    assert.equal(revoked.status, "REVOKED");
    assert.equal(
      (
        await governance.tenantReadiness(scope, {
          applicationId: "ai-growth-sales-platform",
        })
      ).status,
      "NOT_READY",
    );
    const replacementPending = await governance.request(
        connector.id,
        {
          tenantId: scope.tenantId,
          dataOwnerId: owner.userId,
          mappingVersion: "growth-map-v2",
          expiresAt: "2026-08-27T10:00:00Z",
        },
        owner,
      ),
      replacement = await governance.decide(
        replacementPending.id,
        {
          decision: "APPROVED",
          expectedVersion: replacementPending.version,
          reason: "Approve replacement authorization",
        },
        owner,
      ),
      latest = await governance.tenantReadiness(scope, {
        applicationId: "ai-growth-sales-platform",
      });
    assert.equal(replacement.status, "APPROVED");
    assert.equal(latest.status, "READY");
    const sequences = (
      await pool.query(
        "SELECT sequence_id FROM business_data_source_approval WHERE connector_id=$1 ORDER BY sequence_id",
        [connector.id],
      )
    ).rows.map((row) => Number(row.sequence_id));
    assert.equal(sequences.length, 2);
    assert.ok(sequences[1] > sequences[0]);
    const otherTenant = await governance.tenantReadiness(
      { ...scope, tenantId: "tenant-b" },
      { applicationId: "ai-growth-sales-platform" },
    );
    assert.equal(otherTenant.status, "NOT_READY");
    assert.equal(otherTenant.items[0].checks.approvalGranted, false);
    now = new Date("2026-08-27T10:00:01Z");
    const expired = await governance.tenantReadiness(scope, {
      applicationId: "ai-growth-sales-platform",
    });
    assert.equal(expired.status, "NOT_READY");
    assert.equal(expired.items[0].checks.authorizationUnexpired, false);
    assert.doesNotMatch(
      JSON.stringify(ready) + JSON.stringify(otherTenant) + JSON.stringify(expired),
      /growth-source-credential-ref|Approved tenant source mapping/,
    );
  } finally {
    await pool
      .query("DELETE FROM business_data_source_approval WHERE organization_id=$1", [
        scope.organizationId,
      ])
      .catch(() => {});
    await pool
      .query("DELETE FROM business_data_connector WHERE organization_id=$1", [
        scope.organizationId,
      ])
      .catch(() => {});
    await pool.end();
  }
});
