import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {ensurePostgresFixture,createTestPool} from '../../orchestrator-core/lib/postgres-fixture.mjs';
import {createBusinessApplicationRuntime} from '../lib/business-database.mjs';
import {PostgresGrowthConnectorEvidence} from '../lib/postgres-growth-connector-evidence.mjs';

test('publishing readiness uses scoped active channel account references without reading values',async()=>{await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`growth-connector-${suffix}`,workspaceId:'growth',tenantId:'tenant-a'},other={...scope,organizationId:`other-${suffix}`};try{await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool});await pool.query(`INSERT INTO business_application_record(id,organization_id,workspace_id,application_id,object_type,display_key,title,status,owner_id,fields,source,version,created_by,created_at,updated_at) VALUES($1,$2,$3,'ai-growth-sales-platform','channel_account',$4,'KingTurf TikTok','ACTIVE','growth-owner',$5,'MANUAL',1,'test',now(),now())`,[randomUUID(),scope.organizationId,scope.workspaceId,`ACCOUNT-${suffix}`,{platform:'抖音',accountRef:'ACCOUNT-1',ownerOrganization:'KingTurf',credentialReferenceId:'tiktok-production-ref',authorizationExpiresAt:'2027-08-26',publishingScope:'approved content'}]);const evidence=new PostgresGrowthConnectorEvidence({pool,clock:()=>new Date('2026-08-26T00:00:00Z')}),ready=await evidence.publishing(scope,{platforms:['抖音']});assert.deepEqual(ready,{kind:'PUBLISHING',credentialReferenceConfigured:true,health:'CONFIGURED_NOT_PROBED',configuredAccounts:1,requiredPlatforms:['抖音'],credentialValuesRead:false,source:'AUTHORITATIVE_CHANNEL_ACCOUNT_RECORDS'});const exactExpiry=new PostgresGrowthConnectorEvidence({pool,clock:()=>new Date('2027-08-26T00:00:00Z')});assert.equal((await exactExpiry.publishing(scope,{platforms:['抖音']})).credentialReferenceConfigured,false);assert.equal((await evidence.publishing(scope,{platforms:['视频号']})).credentialReferenceConfigured,false);assert.equal((await evidence.publishing(other,{platforms:['抖音']})).credentialReferenceConfigured,false);assert.doesNotMatch(JSON.stringify(ready),/tiktok-production-ref/);}finally{await pool.query('DELETE FROM business_application_record WHERE organization_id=$1',[scope.organizationId]).catch(()=>{});await pool.end();}});

test('publishing readiness rejects unbounded inputs before SQL',async()=>{let queries=0;const scope={organizationId:'org',workspaceId:'growth',tenantId:'tenant'},evidence=new PostgresGrowthConnectorEvidence({pool:{async query(){queries+=1;throw new Error('must not query');}},clock:()=>new Date(Number.NaN)});await assert.rejects(()=>evidence.publishing(scope,{platforms:Array(21).fill('platform')}),error=>error.code==='GROWTH_PUBLISHING_PLATFORMS_INVALID');await assert.rejects(()=>evidence.publishing(scope,{platforms:['token=secret']}),error=>error.code==='GROWTH_PUBLISHING_PLATFORMS_INVALID');await assert.rejects(()=>evidence.publishing(scope,{platforms:['抖音']}),error=>error.code==='GROWTH_PUBLISHING_CLOCK_INVALID');assert.equal(queries,0);});
