import test from "node:test";
import assert from "node:assert/strict";
import { ProfessionalBusinessSkillRunner,professionalBusinessSkillContracts } from "../lib/professional-business-skill-runner.mjs";

const expense={applicationId:"finance-platform",objectType:"expense",fields:{expenseDate:"2026-07-21",department:"运营中心",category:"采购",amount:2600,currency:"CNY",budgetCode:"OPS-01"}};
const budget={applicationId:"finance-platform",objectType:"budget",displayKey:"BUD-2026-OPS",status:"ACTIVE",fields:{fiscalYear:2026,department:"运营中心",budgetCode:"OPS-01",amount:10000,currency:"CNY"}};

test("finance professional runner produces a reviewable pass from authoritative linked records",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:expense,relatedRecords:[budget]});assert.equal(result.outcomeType,"FINANCE_EXPENSE_BUDGET_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.recommendation,"SUBMIT_FOR_HUMAN_APPROVAL");assert.equal(result.facts.expenseAmount,2600);assert.equal(result.facts.budgetAmount,10000);});

test("finance professional runner blocks missing budget and does not infer remaining balance",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:expense,relatedRecords:[]});assert.equal(result.decision,"BLOCKED");assert.equal(result.checks.find(item=>item.code==="ACTIVE_BUDGET_LINKED").status,"FAIL");assert.match(result.limitations.join(" "),/remaining budget/);assert.equal(new ProfessionalBusinessSkillRunner().execute({record:{applicationId:"human-resources-platform",objectType:"employee"}}),null);});

test("professional registry binds application, object, Skill, Agent and Runner without a second scheduler",()=>{const contract=professionalBusinessSkillContracts[0];assert.deepEqual({applicationId:contract.applicationId,objectType:contract.objectType,businessSkillId:contract.businessSkillId,agentId:contract.agentId,runnerId:contract.runnerId,runtimeType:contract.runtimeType,status:contract.status},{applicationId:"finance-platform",objectType:"expense",businessSkillId:"financial_control_validation",agentId:"finance-control-agent",runnerId:"finance-expense-rule-runner-v1",runtimeType:"PROFESSIONAL_RULE_ENGINE",status:"ACTIVE"});assert.equal(contract.humanApprovalRequired,true);});

const workOrder={applicationId:"intelligent-manufacturing-erp",objectType:"work_order",displayKey:"WO-001",fields:{productCode:"P-001",quantity:10,unit:"台",dueDate:"2026-08-31",plant:"一号工厂"}};
const manufacturingEvidence=[
  {applicationId:"intelligent-manufacturing-erp",objectType:"bom",displayKey:"BOM-P001-A",status:"RELEASED",fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",componentCount:2,componentRequirements:"MAT-A:2,MAT-B:1"}},
  {applicationId:"intelligent-manufacturing-erp",objectType:"routing_sop",displayKey:"SOP-P001-A",status:"RELEASED",fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",controlledDocumentRef:"WI-P001-A"}},
  {applicationId:"intelligent-manufacturing-erp",objectType:"inventory",displayKey:"INV-A",status:"COMPLETED",updatedAt:"2026-07-21T07:00:00Z",fields:{materialCode:"MAT-A",quantity:20}},
  {applicationId:"intelligent-manufacturing-erp",objectType:"inventory",displayKey:"INV-B",status:"COMPLETED",updatedAt:"2026-07-21T07:00:00Z",fields:{materialCode:"MAT-B",quantity:10}}
];

test("manufacturing professional runner passes only with released BOM SOP and sufficient WMS evidence",()=>{const result=new ProfessionalBusinessSkillRunner({clock:()=>new Date("2026-07-21T08:00:00Z")}).execute({record:workOrder,relatedRecords:manufacturingEvidence});assert.equal(result.outcomeType,"MANUFACTURING_WORK_ORDER_READINESS_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.runnerId,"manufacturing-work-order-readiness-runner-v1");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.facts.requiredMaterials.length,2);assert.equal(result.recommendation,"SUBMIT_WORK_ORDER_RELEASE_FOR_HUMAN_APPROVAL");});

test("manufacturing professional runner blocks shortages and never releases production itself",()=>{const evidence=manufacturingEvidence.map(item=>item.displayKey==="INV-A"?{...item,fields:{...item.fields,quantity:19}}:item),result=new ProfessionalBusinessSkillRunner({clock:()=>new Date("2026-07-21T08:00:00Z")}).execute({record:workOrder,relatedRecords:evidence});assert.equal(result.decision,"BLOCKED");assert.equal(result.checks.find(item=>item.code==="MATERIALS_AVAILABLE").status,"FAIL");assert.deepEqual(result.facts.shortages,[{materialCode:"MAT-A",quantity:2}]);assert.match(result.limitations.join(" "),/does not reserve stock/i);});

test("manufacturing contract is active in the shared professional runner registry",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="intelligent-manufacturing-erp");assert.deepEqual(contract.requiredRelations,["USED_BY","GOVERNS","ALLOCATED_TO"]);assert.equal(contract.businessSkillId,"production_release_readiness");assert.equal(contract.agentId,"manufacturing-readiness-agent");assert.equal(contract.humanApprovalRequired,true);});

const onboarding={applicationId:"human-resources-platform",objectType:"onboarding_case",displayKey:"ONB-001",fields:{employeeName:"候选人甲",candidateRef:"CAND-001",department:"经营中心",positionName:"经营分析负责人",employmentType:"全职",startDate:"2026-08-01",manager:"经营中心负责人",identityVerificationRef:"IDV-001",contractDocumentRef:"CONTRACT-001",equipmentRequestRef:"EQUIP-001",accessProfileRef:"ACCESS-MIN-001"}};
const hrEvidence=[
  {id:"position-1",applicationId:"human-resources-platform",objectType:"position",displayKey:"POS-001",status:"ACTIVE",fields:{positionName:"经营分析负责人",department:"经营中心",headcount:1}},
  {id:"recruitment-1",applicationId:"human-resources-platform",objectType:"recruitment_case",displayKey:"REC-001",status:"COMPLETED",fields:{department:"经营中心",positionName:"经营分析负责人",employmentType:"全职"}},
  {id:"candidate-1",applicationId:"human-resources-platform",objectType:"candidate_application",displayKey:"CAND-APP-001",status:"SELECTED",fields:{candidateRef:"CAND-001",consentStatus:"已授权",humanSelectionDecisionRef:"HUMAN-DECISION-001"}},
  {id:"offer-1",applicationId:"human-resources-platform",objectType:"employment_offer",displayKey:"OFFER-001",status:"ACCEPTED",fields:{candidateRef:"CAND-001",department:"经营中心",positionName:"经营分析负责人",employmentType:"全职",proposedStartDate:"2026-08-01",offerDocumentRef:"OFFER-DOC-001"}}
];
const hrRelatedEvidence=[{recordId:"position-1",paths:[["AUTHORIZES"]]},{recordId:"recruitment-1",paths:[["RESULTS_IN"]]},{recordId:"candidate-1",paths:[["RESULTS_IN","CONSIDERS"],["INITIATES","RECEIVES"]]},{recordId:"offer-1",paths:[["INITIATES"],["RESULTS_IN","CONSIDERS","RECEIVES"]]}];

test("HR professional runner verifies administrative onboarding evidence without making a hiring decision",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:hrEvidence,relatedEvidence:hrRelatedEvidence});assert.equal(result.outcomeType,"HR_ONBOARDING_ADMINISTRATIVE_READINESS_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.runnerId,"hr-onboarding-readiness-runner-v1");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.recommendation,"SUBMIT_ONBOARDING_READINESS_FOR_HUMAN_APPROVAL");assert.match(result.limitations.join(" "),/does not rank candidates/i);});

test("HR professional runner blocks absent human-selected evidence and withdrawn consent",()=>{const evidence=hrEvidence.filter(item=>item.objectType!=="candidate_application"),missing=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:evidence,relatedEvidence:hrRelatedEvidence});assert.equal(missing.decision,"BLOCKED");assert.equal(missing.checks.find(item=>item.code==="HUMAN_SELECTED_CANDIDATE_LINKED").status,"FAIL");const withdrawn=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:hrEvidence.map(item=>item.objectType==="candidate_application"?{...item,fields:{...item.fields,consentStatus:"已撤回"}}:item),relatedEvidence:hrRelatedEvidence});assert.equal(withdrawn.decision,"REVIEW_REQUIRED");assert.equal(withdrawn.checks.find(item=>item.code==="CANDIDATE_PRIVACY_CONSENT").status,"FAIL");});

test("HR professional runner rejects correct-looking records without the governed relation paths",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:hrEvidence,relatedEvidence:[]});assert.equal(result.decision,"BLOCKED");assert.equal(result.checks.find(item=>item.code==="CANDIDATE_EVIDENCE_PATH").status,"FAIL");});

test("HR contract binds onboarding to the shared professional Runner and requires human approval",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="human-resources-platform");assert.equal(contract.objectType,"onboarding_case");assert.equal(contract.businessSkillId,"onboarding_administrative_readiness");assert.equal(contract.agentId,"hr-onboarding-control-agent");assert.equal(contract.humanApprovalRequired,true);assert.ok(contract.requiredRelations.includes("INITIATES"));});
