import test from "node:test";
import assert from "node:assert/strict";
import { ProfessionalBusinessSkillRunner,professionalBusinessSkillContracts } from "../lib/professional-business-skill-runner.mjs";

const expense={applicationId:"finance-platform",objectType:"expense",fields:{expenseDate:"2026-07-21",department:"运营中心",category:"采购",amount:2600,currency:"CNY",budgetCode:"OPS-01"}};
const budget={applicationId:"finance-platform",objectType:"budget",displayKey:"BUD-2026-OPS",status:"ACTIVE",fields:{fiscalYear:2026,department:"运营中心",budgetCode:"OPS-01",amount:10000,currency:"CNY"}};

test("finance professional runner produces a reviewable pass from authoritative linked records",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:expense,relatedRecords:[budget]});assert.equal(result.outcomeType,"FINANCE_EXPENSE_BUDGET_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.recommendation,"SUBMIT_FOR_HUMAN_APPROVAL");assert.equal(result.facts.expenseAmount,2600);assert.equal(result.facts.budgetAmount,10000);});

test("finance professional runner blocks missing budget and does not infer remaining balance",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:expense,relatedRecords:[]});assert.equal(result.decision,"BLOCKED");assert.equal(result.checks.find(item=>item.code==="ACTIVE_BUDGET_LINKED").status,"FAIL");assert.match(result.limitations.join(" "),/remaining budget/);assert.equal(new ProfessionalBusinessSkillRunner().execute({record:{applicationId:"human-resources-platform",objectType:"employee"}}),null);});

test("professional registry binds application, object, Skill, Agent and Runner without a second scheduler",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="finance-platform");assert.deepEqual({applicationId:contract.applicationId,objectType:contract.objectType,businessSkillId:contract.businessSkillId,agentId:contract.agentId,runnerId:contract.runnerId,runtimeType:contract.runtimeType,status:contract.status},{applicationId:"finance-platform",objectType:"expense",businessSkillId:"financial_control_validation",agentId:"finance-control-agent",runnerId:"finance-expense-rule-runner-v1",runtimeType:"PROFESSIONAL_RULE_ENGINE",status:"ACTIVE"});assert.equal(contract.humanApprovalRequired,true);});

const workOrder={applicationId:"intelligent-manufacturing-erp",objectType:"work_order",displayKey:"WO-001",fields:{productCode:"P-001",quantity:10,unit:"台",dueDate:"2026-08-31",plant:"一号工厂"}};
const manufacturingEvidence=[
  {applicationId:"intelligent-manufacturing-erp",objectType:"bom",displayKey:"BOM-P001-A",status:"RELEASED",fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",componentCount:2,componentRequirements:"MAT-A:2,MAT-B:1"}},
  {applicationId:"intelligent-manufacturing-erp",objectType:"routing_sop",displayKey:"SOP-P001-A",status:"RELEASED",fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",controlledDocumentRef:"WI-P001-A"}},
  {applicationId:"intelligent-manufacturing-erp",objectType:"inventory",displayKey:"INV-A",status:"COMPLETED",updatedAt:"2026-07-21T07:00:00Z",fields:{materialCode:"MAT-A",quantity:20}},
  {applicationId:"intelligent-manufacturing-erp",objectType:"inventory",displayKey:"INV-B",status:"COMPLETED",updatedAt:"2026-07-21T07:00:00Z",fields:{materialCode:"MAT-B",quantity:10}}
];

test("manufacturing professional runner passes only with released BOM SOP and sufficient WMS evidence",()=>{const result=new ProfessionalBusinessSkillRunner({clock:()=>new Date("2026-07-21T08:00:00Z")}).execute({record:workOrder,relatedRecords:manufacturingEvidence});assert.equal(result.outcomeType,"MANUFACTURING_WORK_ORDER_READINESS_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.runnerId,"manufacturing-work-order-readiness-runner-v1");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.facts.requiredMaterials.length,2);assert.equal(result.recommendation,"SUBMIT_WORK_ORDER_RELEASE_FOR_HUMAN_APPROVAL");});

test("manufacturing professional runner blocks shortages and never releases production itself",()=>{const evidence=manufacturingEvidence.map(item=>item.displayKey==="INV-A"?{...item,fields:{...item.fields,quantity:19}}:item),result=new ProfessionalBusinessSkillRunner({clock:()=>new Date("2026-07-21T08:00:00Z")}).execute({record:workOrder,relatedRecords:evidence});assert.equal(result.decision,"BLOCKED");assert.equal(result.checks.find(item=>item.code==="MATERIALS_AVAILABLE").status,"FAIL");assert.deepEqual(result.facts.shortages,[{materialCode:"MAT-A",quantity:2}]);assert.match(result.limitations.join(" "),/does not reserve stock/i);});

test("manufacturing contract is active in the shared professional runner registry",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="intelligent-manufacturing-erp");assert.deepEqual(contract.requiredRelations,["USED_BY","GOVERNS","ALLOCATED_TO"]);assert.equal(contract.businessSkillId,"production_release_readiness");assert.equal(contract.agentId,"manufacturing-readiness-agent");assert.equal(contract.humanApprovalRequired,true);});

const onboarding={applicationId:"human-resources-platform",objectType:"onboarding_case",displayKey:"ONB-001",fields:{employeeName:"候选人甲",candidateRef:"CAND-001",department:"经营中心",positionName:"经营分析负责人",employmentType:"全职",startDate:"2026-08-01",manager:"经营中心负责人",identityVerificationRef:"IDV-001",contractDocumentRef:"CONTRACT-001",equipmentRequestRef:"EQUIP-001",accessProfileRef:"ACCESS-MIN-001"}};
const hrEvidence=[
  {id:"position-1",applicationId:"human-resources-platform",objectType:"position",displayKey:"POS-001",status:"ACTIVE",fields:{positionName:"经营分析负责人",department:"经营中心",headcount:1}},
  {id:"recruitment-1",applicationId:"human-resources-platform",objectType:"recruitment_case",displayKey:"REC-001",status:"COMPLETED",fields:{department:"经营中心",positionName:"经营分析负责人",employmentType:"全职"}},
  {id:"candidate-1",applicationId:"human-resources-platform",objectType:"candidate_application",displayKey:"CAND-APP-001",status:"SELECTED",fields:{candidateRef:"CAND-001",consentStatus:"已授权",humanSelectionDecisionRef:"HUMAN-DECISION-001"}},
  {id:"offer-1",applicationId:"human-resources-platform",objectType:"employment_offer",displayKey:"OFFER-001",status:"ACCEPTED",fields:{candidateRef:"CAND-001",department:"经营中心",positionName:"经营分析负责人",employmentType:"全职",proposedStartDate:"2026-08-01",offerDocumentRef:"OFFER-DOC-001"}}
];
const hrRelatedEvidence=[{recordId:"position-1",paths:[["AUTHORIZES"]]},{recordId:"recruitment-1",paths:[["RESULTS_IN"]]},{recordId:"candidate-1",paths:[["RESULTS_IN","CONSIDERS"],["INITIATES","RECEIVES"]]},{recordId:"offer-1",paths:[["INITIATES"],["RESULTS_IN","CONSIDERS","RECEIVES"]]}];

test("HR professional runner verifies administrative onboarding evidence without making a hiring decision",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:hrEvidence,relatedEvidence:hrRelatedEvidence});assert.equal(result.outcomeType,"HR_ONBOARDING_ADMINISTRATIVE_READINESS_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.runnerId,"hr-onboarding-readiness-runner-v1");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.recommendation,"SUBMIT_ONBOARDING_READINESS_FOR_HUMAN_APPROVAL");assert.match(result.limitations.join(" "),/does not rank candidates/i);});

test("HR professional runner blocks absent human-selected evidence and withdrawn consent",()=>{const evidence=hrEvidence.filter(item=>item.objectType!=="candidate_application"),missing=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:evidence,relatedEvidence:hrRelatedEvidence});assert.equal(missing.decision,"BLOCKED");assert.equal(missing.checks.find(item=>item.code==="HUMAN_SELECTED_CANDIDATE_LINKED").status,"FAIL");const withdrawn=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:hrEvidence.map(item=>item.objectType==="candidate_application"?{...item,fields:{...item.fields,consentStatus:"已撤回"}}:item),relatedEvidence:hrRelatedEvidence});assert.equal(withdrawn.decision,"REVIEW_REQUIRED");assert.equal(withdrawn.checks.find(item=>item.code==="CANDIDATE_PRIVACY_CONSENT").status,"FAIL");});

test("HR professional runner rejects correct-looking records without the governed relation paths",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:onboarding,relatedRecords:hrEvidence,relatedEvidence:[]});assert.equal(result.decision,"BLOCKED");assert.equal(result.checks.find(item=>item.code==="CANDIDATE_EVIDENCE_PATH").status,"FAIL");});

test("HR contract binds onboarding to the shared professional Runner and requires human approval",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="human-resources-platform");assert.equal(contract.objectType,"onboarding_case");assert.equal(contract.businessSkillId,"onboarding_administrative_readiness");assert.equal(contract.agentId,"hr-onboarding-control-agent");assert.equal(contract.humanApprovalRequired,true);assert.ok(contract.requiredRelations.includes("INITIATES"));});

const publishPlan={applicationId:"ai-growth-sales-platform",objectType:"publish_plan",displayKey:"PUB-001",fields:{campaignRef:"CAM-001",productCode:"PROD-001",channel:"视频号",accountRef:"ACCOUNT-001",scheduledAt:"2026-08-15",expectedAssetCount:1,publishMode:"人工确认后自动发布"}};
const growthEvidence=[
  {id:"product-1",applicationId:"ai-growth-sales-platform",objectType:"product",displayKey:"PROD-001",status:"ACTIVE",fields:{productCode:"PROD-001",evidence:"受控产品规格书 SPEC-001"}},
  {id:"campaign-1",applicationId:"ai-growth-sales-platform",objectType:"campaign",displayKey:"CAM-001",status:"PLANNING",fields:{productCode:"PROD-001",channel:"视频号",startDate:"2026-08-01",endDate:"2026-08-31"}},
  {id:"asset-1",applicationId:"ai-growth-sales-platform",objectType:"content_asset",displayKey:"ASSET-001",status:"APPROVED",fields:{productCode:"PROD-001",channel:"视频号",claimEvidenceRef:"CLAIM-001",rightsClearanceRef:"RIGHTS-001",contentHash:"sha256:abc"}},
  {id:"account-1",applicationId:"ai-growth-sales-platform",objectType:"channel_account",displayKey:"ACCOUNT-RECORD-001",status:"ACTIVE",fields:{platform:"视频号",accountRef:"ACCOUNT-001",authorizationExpiresAt:"2026-12-31",credentialReferenceId:"video-channel-ref"}}
];
const growthRelatedEvidence=[{recordId:"campaign-1",paths:[["SCHEDULES"]]},{recordId:"product-1",paths:[["SCHEDULES","PROMOTED_BY"],["INCLUDES","GROUNDS"]]},{recordId:"asset-1",paths:[["INCLUDES"],["SCHEDULES","PRODUCES"],["SCHEDULES","PROMOTED_BY","GROUNDS"]]},{recordId:"account-1",paths:[["AUTHORIZES"]]}];

test("growth professional runner produces a human-gated publish readiness pass",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:publishPlan,relatedRecords:growthEvidence,relatedEvidence:growthRelatedEvidence});assert.equal(result.outcomeType,"GROWTH_CONTROLLED_PUBLISH_READINESS_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.runnerId,"growth-publish-readiness-runner-v1");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.recommendation,"SUBMIT_PUBLISH_PLAN_FOR_HUMAN_APPROVAL");assert.match(result.limitations.join(" "),/does not register accounts/i);});

test("growth professional runner blocks expired channel authorization and unrelated assets",()=>{const expired=new ProfessionalBusinessSkillRunner().execute({record:publishPlan,relatedRecords:growthEvidence.map(item=>item.id==="account-1"?{...item,fields:{...item.fields,authorizationExpiresAt:"2026-08-01"}}:item),relatedEvidence:growthRelatedEvidence});assert.equal(expired.decision,"BLOCKED");assert.equal(expired.checks.find(item=>item.code==="ACCOUNT_AUTHORIZATION_VALID").status,"FAIL");const unrelated=new ProfessionalBusinessSkillRunner().execute({record:publishPlan,relatedRecords:growthEvidence,relatedEvidence:growthRelatedEvidence.filter(item=>item.recordId!=="asset-1")});assert.equal(unrelated.decision,"BLOCKED");assert.equal(unrelated.checks.find(item=>item.code==="APPROVED_ASSETS_LINKED").status,"FAIL");});

test("growth contract binds publish plans to the shared Runner without enabling publication",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="ai-growth-sales-platform");assert.equal(contract.objectType,"publish_plan");assert.equal(contract.businessSkillId,"controlled_publish_readiness");assert.equal(contract.agentId,"growth-publishing-control-agent");assert.equal(contract.humanApprovalRequired,true);assert.deepEqual(contract.requiredRelations,["PROMOTED_BY","GROUNDS","PRODUCES","SCHEDULES","INCLUDES","AUTHORIZES"]);});

const strategyReview={applicationId:"enterprise-strategy-platform",objectType:"strategy_review",displayKey:"REVIEW-2026-Q2",fields:{period:"2026-Q2",scope:"集团经营质量",reviewDate:"2026-07-21",evidenceCutoffDate:"2026-07-20",actualResult:"经营质量指标低于目标",varianceReason:"重点举措延期"}};
const strategyEvidence=[
  {id:"objective-1",applicationId:"enterprise-strategy-platform",objectType:"objective",displayKey:"OBJ-001",status:"AT_RISK",fields:{period:"2026-2028",responsibleCenter:"集团经营中心"}},
  {id:"kpi-1",applicationId:"enterprise-strategy-platform",objectType:"kpi",displayKey:"KPI-001",status:"AT_RISK",fields:{targetValue:90,actualValue:80,direction:"越高越好",unit:"%",actualAsOf:"2026-07-15",actualEvidenceRef:"KPI-SOURCE-001"}},
  {id:"initiative-1",applicationId:"enterprise-strategy-platform",objectType:"initiative",displayKey:"INIT-001",status:"AT_RISK",fields:{dueDate:"2026-06-30",progressPercent:80,progressAsOf:"2026-07-15",progressEvidenceRef:"INIT-SOURCE-001"}},
  {id:"action-1",applicationId:"enterprise-strategy-platform",objectType:"corrective_action",displayKey:"ACTION-001",status:"ACTIVE",fields:{ownerCenter:"集团经营中心",dueDate:"2026-08-31",evidenceRequirement:"验收报告"}}
];
const strategyRelatedEvidence=[{recordId:"objective-1",paths:[["REVIEWED_IN"]]},{recordId:"kpi-1",paths:[["EVIDENCED_IN"],["REVIEWED_IN","MEASURED_BY"]]},{recordId:"initiative-1",paths:[["ASSESSED_IN"],["REVIEWED_IN","DELIVERED_BY"]]},{recordId:"action-1",paths:[["RESULTS_IN"],["REVIEWED_IN","CORRECTED_BY"]]}];

test("strategy professional runner calculates evidence-backed gaps without inventing metrics",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:strategyReview,relatedRecords:strategyEvidence,relatedEvidence:strategyRelatedEvidence});assert.equal(result.outcomeType,"STRATEGY_REVIEW_EVIDENCE_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.runnerId,"strategy-review-evidence-runner-v1");assert.equal(result.checks.every(item=>item.status==="PASS"),true);assert.equal(result.facts.kpiGapCount,1);assert.equal(result.facts.overdueInitiativeCount,1);assert.equal(result.recommendation,"SUBMIT_STRATEGY_REVIEW_FOR_HUMAN_APPROVAL");assert.match(result.limitations.join(" "),/does not verify the external source/i);});

test("strategy professional runner blocks stale evidence and missing corrective actions",()=>{const stale=new ProfessionalBusinessSkillRunner().execute({record:strategyReview,relatedRecords:strategyEvidence.map(item=>item.id==="kpi-1"?{...item,fields:{...item.fields,actualAsOf:"2026-01-01"}}:item),relatedEvidence:strategyRelatedEvidence});assert.equal(stale.decision,"BLOCKED");assert.equal(stale.checks.find(item=>item.code==="EVIDENCE_DATES_VALID").status,"FAIL");const noActions=new ProfessionalBusinessSkillRunner().execute({record:strategyReview,relatedRecords:strategyEvidence.filter(item=>item.objectType!=="corrective_action"),relatedEvidence:strategyRelatedEvidence});assert.equal(noActions.decision,"BLOCKED");assert.equal(noActions.checks.find(item=>item.code==="CORRECTIVE_ACTIONS_READY").status,"FAIL");});

test("strategy contract binds review evidence to the shared Runner and human approval",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="enterprise-strategy-platform");assert.equal(contract.objectType,"strategy_review");assert.equal(contract.businessSkillId,"strategy_review_evidence_validation");assert.equal(contract.agentId,"strategy-review-control-agent");assert.equal(contract.humanApprovalRequired,true);assert.ok(contract.requiredRelations.includes("CORRECTED_BY"));});

const parkOrder={applicationId:"smart-park-platform",objectType:"service_order",displayKey:"SVC-001",fields:{enterpriseName:"示例制造企业",serviceType:"报修",location:"A1 厂房",requestedAt:"2026-07-21T08:00:00Z",slaHours:4,priority:"紧急",assignedTeam:"设施服务班组",description:"空调无法启动",resolutionSummary:"更换控制器并完成复测",completionEvidenceRef:"SERVICE-EVIDENCE-001",resolvedAt:"2026-07-21T10:30:00Z"}};
const parkEnterprise={id:"enterprise-1",applicationId:"smart-park-platform",objectType:"enterprise",displayKey:"ENT-001",title:"示例制造企业",status:"ACTIVE",fields:{creditCode:"91330000EXAMPLE"}},parkEvidence=[{recordId:"enterprise-1",paths:[["REQUESTS"]]}];

test("Smart Park professional runner verifies linked tenant, SLA and completion evidence",()=>{const result=new ProfessionalBusinessSkillRunner().execute({record:parkOrder,relatedRecords:[parkEnterprise],relatedEvidence:parkEvidence});assert.equal(result.outcomeType,"PARK_SERVICE_COMPLETION_CHECK");assert.equal(result.decision,"PASS");assert.equal(result.facts.slaMet,true);assert.equal(result.recommendation,"SUBMIT_SERVICE_COMPLETION_FOR_HUMAN_APPROVAL");assert.match(result.limitations.join(" "),/does not verify external evidence content/i);});

test("Smart Park professional runner blocks unlinked tenants and flags SLA breaches for review",()=>{const missing=new ProfessionalBusinessSkillRunner().execute({record:parkOrder,relatedRecords:[parkEnterprise],relatedEvidence:[]});assert.equal(missing.decision,"BLOCKED");assert.equal(missing.checks.find(item=>item.code==="ACTIVE_ENTERPRISE_LINKED").status,"FAIL");const late=new ProfessionalBusinessSkillRunner().execute({record:{...parkOrder,fields:{...parkOrder.fields,resolvedAt:"2026-07-21T13:00:00Z"}},relatedRecords:[parkEnterprise],relatedEvidence:parkEvidence});assert.equal(late.decision,"REVIEW_REQUIRED");assert.equal(late.checks.find(item=>item.code==="SLA_MET").status,"FAIL");});

test("Smart Park contract uses the shared professional Runner and requires human acceptance",()=>{const contract=professionalBusinessSkillContracts.find(item=>item.applicationId==="smart-park-platform");assert.equal(contract.objectType,"service_order");assert.equal(contract.businessSkillId,"park_service_completion_validation");assert.equal(contract.agentId,"park-service-control-agent");assert.equal(contract.humanApprovalRequired,true);assert.deepEqual(contract.requiredRelations,["REQUESTS"]);});
