import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { ensurePostgresFixture,createTestPool } from "../../orchestrator-core/lib/postgres-fixture.mjs";
import { PersistentNightShiftService } from "../../orchestrator-core/lib/persistent-night-shift.mjs";
import { createBusinessApplicationRuntime } from "../lib/business-database.mjs";
import { loadDomainRuntimeRegistry } from "../lib/domain-center.mjs";
import { PersistentBusinessWorkExecutor } from "../lib/persistent-business-work-executor.mjs";
import { ResidentBusinessWorkRunner } from "../lib/resident-business-work-runner.mjs";

const expenseFields={expenseDate:"2026-07-21",department:"运营中心",category:"采购",amount:2600,currency:"CNY",budgetCode:"OPS-01",description:"常驻 Runner 验收"};

test("resident business runner resumes persisted work and isolates item failures",async()=>{
  let pending=[{id:"work-1"},{id:"work-2"}],completed=[];const errors=[],store={runnableAgentWorkItems:async()=>pending};
  const runner=new ResidentBusinessWorkRunner({store,pollMs:50,executeWork:async item=>{if(item.id==="work-1")throw Object.assign(new Error("controlled"),{code:"CONTROLLED_FAILURE"});pending=pending.filter(value=>value.id!==item.id);completed.push(item.id);},onError:(error,item)=>errors.push([error.code,item.id])});
  await runner.tick();await runner.tick();assert.deepEqual(completed,["work-2"]);assert.deepEqual(errors,[["CONTROLLED_FAILURE","work-1"]]);assert.equal(runner.snapshot().failed,1);assert.equal(runner.snapshot().completed,1);assert.equal(runner.snapshot().active,0);assert.equal(runner.snapshot().deferred,1);
});

test("resident runner fails closed and honors persistent drain control",async()=>{
  let desiredState="DRAINING",scans=0,executions=0,stopped=0;const registry={register:async()=>({status:"DRAINING",desiredState,version:1,lastHeartbeatAt:new Date().toISOString()}),heartbeat:async()=>({status:desiredState,desiredState,version:2,lastHeartbeatAt:new Date().toISOString()}),stop:async()=>{stopped+=1;return{status:"OFFLINE",desiredState,version:3};}},store={runnableAgentWorkItems:async()=>{scans+=1;return[{id:"governed-work"}];}};
  const runner=new ResidentBusinessWorkRunner({store,executeWork:async()=>{executions+=1;},nodeRegistry:registry,nodeKey:"runner:test"});
  await runner.tick();assert.equal(scans,0);assert.equal(executions,0);assert.equal(runner.snapshot().desiredState,"DRAINING");desiredState="ONLINE";await runner.tick();assert.equal(scans,1);assert.equal(executions,1);await runner.stop();assert.equal(stopped,1);
  const denied=new ResidentBusinessWorkRunner({store,executeWork:async()=>{executions+=1;},nodeRegistry:{register:async()=>{throw Object.assign(new Error("database unavailable"),{code:"REGISTRY_DOWN"});}},nodeKey:"runner:down"});await denied.tick();assert.equal(scans,1);assert.equal(denied.snapshot().lastError.code,"REGISTRY_DOWN");
});

test("two resident runners execute one persisted business session exactly once after restart",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`resident-org-${suffix}`,workspaceId:`resident-workspace-${suffix}`,projectId:"resident-project",userId:"finance-user"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,record=await store.createRecord("finance-platform",{objectType:"expense",title:"常驻业务执行",displayKey:`RESIDENT-${suffix}`,fields:expenseFields},scope),work=await store.createWorkItem({applicationId:"finance-platform",businessObjectId:record.id,assignmentType:"AGENT",assigneeId:"agent-finance"},scope),night=new PersistentNightShiftService(pool),sessionKey=`resident-business-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"生成财务检查报告",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})}),runnerStore={runnableAgentWorkItems:async()=>{const item=await store.getWorkItemForRunner(attached.id);return item?.status==="RUNNING"?[item]:[];}},first=new ResidentBusinessWorkRunner({store:runnerStore,pool,executeWork:item=>executor.execute(item)}),second=new ResidentBusinessWorkRunner({store:runnerStore,pool,executeWork:item=>executor.execute(item)});
    assert.equal((await store.getWorkItemForRunner(attached.id)).status,"RUNNING");assert.equal((await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version})).version,attached.version);await assert.rejects(()=>store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:randomUUID(),report:null,status:"RUNNING",expectedWorkVersion:work.version}),error=>error.code==="BUSINESS_WORK_VERSION_CONFLICT");await Promise.all([first.tick(),second.tick()]);const persisted=await store.getWorkItemForRunner(attached.id),report=await night.loadReport(session.id),attempts=Number((await pool.query("SELECT count(*) count FROM ad_task_attempt a JOIN ad_task t ON t.id=a.task_id WHERE t.goal_id=$1",[session.goal_id])).rows[0].count);assert.equal(persisted.status,"BLOCKED",JSON.stringify({first:first.snapshot(),second:second.snapshot()}));assert.equal(persisted.resultSummary.resultType,"PROFESSIONAL_BUSINESS_OUTCOME");assert.equal(persisted.resultSummary.businessOutcomeProduced,true);assert.equal(persisted.resultSummary.professionalOutcome.decision,"BLOCKED");assert.equal(persisted.resultSummary.stages.length,report.totalTasks);assert.equal(report.sessionStatus,"SUCCEEDED");assert.equal(attempts,report.totalTasks);assert.equal(first.snapshot().claimed+second.snapshot().claimed,1);assert.equal(first.snapshot().completed+second.snapshot().completed,1);assert.deepEqual(await runnerStore.runnableAgentWorkItems(),[]);
  }finally{await pool.end();}
});

test("finance expense workflow produces a persisted professional pass from an approved active budget",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`finance-runner-org-${suffix}`,workspaceId:`finance-runner-workspace-${suffix}`,projectId:"finance-runner-project",userId:"finance-user"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,budget0=await store.createRecord("finance-platform",{objectType:"budget",title:"运营预算",displayKey:`BUD-${suffix}`,fields:{fiscalYear:2026,department:"运营中心",budgetCode:"OPS-01",amount:10000,currency:"CNY"}},scope),budget1=await store.transitionRecord("finance-platform",budget0.id,{expectedVersion:1,status:"SUBMITTED"},scope),budget2=await store.transitionRecord("finance-platform",budget0.id,{expectedVersion:2,status:"WAITING_APPROVAL"},scope),approval=await store.requestApproval("finance-platform",budget0.id,{expectedVersion:budget2.version,requestedStatus:"APPROVED"},scope),approved=(await store.decideApproval("finance-platform",approval.id,{decision:"APPROVED"},{...scope,userId:"finance-reviewer"})).record,budget=await store.transitionRecord("finance-platform",budget0.id,{expectedVersion:approved.version,status:"ACTIVE"},scope),expense=await store.createRecord("finance-platform",{objectType:"expense",title:"受控采购费用",displayKey:`EXP-${suffix}`,fields:expenseFields},scope);assert.equal(budget.status,"ACTIVE");await store.createRelation("finance-platform",budget.id,{targetRecordId:expense.id,relationType:"CONTROLS"},scope);
    const work=await store.createWorkItem({applicationId:"finance-platform",businessObjectId:expense.id,assignmentType:"AGENT",assigneeId:"finance-control-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`finance-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"审核费用预算合规",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"COMPLETED");assert.equal(persisted.resultSummary.businessOutcomeProduced,true);assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.budgetDisplayKey,budget.displayKey);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_FOR_HUMAN_APPROVAL");
  }finally{await pool.end();}
});

test("manufacturing work-order workflow persists a professional release-readiness pass",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`manufacturing-runner-org-${suffix}`,workspaceId:`manufacturing-runner-workspace-${suffix}`,projectId:"manufacturing-runner-project",userId:"manufacturing-planner"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store;
    const release=async(objectType,input,reviewStatus)=>{const draft=await store.createRecord("intelligent-manufacturing-erp",{objectType,...input},scope),review=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:draft.version,status:reviewStatus},scope),waiting=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:review.version,status:"WAITING_APPROVAL"},scope),approval=await store.requestApproval("intelligent-manufacturing-erp",draft.id,{expectedVersion:waiting.version,requestedStatus:"RELEASED"},scope);return(await store.decideApproval("intelligent-manufacturing-erp",approval.id,{decision:"APPROVED"},{...scope,userId:"manufacturing-reviewer"})).record;};
    const bom=await release("bom",{title:"P-001 制造 BOM",displayKey:`BOM-${suffix}`,fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",componentCount:2,componentRequirements:"MAT-A:2,MAT-B:1"}},"ENGINEERING_REVIEW"),sop=await release("routing_sop",{title:"P-001 工艺路线",displayKey:`SOP-${suffix}`,fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",operationCount:5,controlledDocumentRef:"WI-P001-A"}},"PROCESS_REVIEW"),createInventory=async(code,quantity)=>{const draft=await store.createRecord("intelligent-manufacturing-erp",{objectType:"inventory",title:`${code} 可用库存`,displayKey:`INV-${code}-${suffix}`,fields:{materialCode:code,warehouse:"原料仓",location:"A-01",batch:"202607",quantity,unit:"件"}},scope),counting=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:draft.version,status:"COUNTING"},scope),matched=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:counting.version,status:"MATCHED"},scope);return store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:matched.version,status:"COMPLETED"},scope);},inventoryA=await createInventory("MAT-A",20),inventoryB=await createInventory("MAT-B",10),order=await store.createRecord("intelligent-manufacturing-erp",{objectType:"work_order",title:"P-001 生产工单",displayKey:`WO-${suffix}`,fields:{productCode:"P-001",quantity:10,unit:"台",dueDate:"2026-08-31",plant:"一号工厂",priority:"关键"}},scope);
    await store.createRelation("intelligent-manufacturing-erp",bom.id,{targetRecordId:order.id,relationType:"USED_BY"},scope);await store.createRelation("intelligent-manufacturing-erp",sop.id,{targetRecordId:order.id,relationType:"GOVERNS"},scope);await store.createRelation("intelligent-manufacturing-erp",inventoryA.id,{targetRecordId:order.id,relationType:"ALLOCATED_TO"},scope);await store.createRelation("intelligent-manufacturing-erp",inventoryB.id,{targetRecordId:order.id,relationType:"ALLOCATED_TO"},scope);const fulfillment=await store.manufacturingFulfillmentReport(scope),foreignFulfillment=await store.manufacturingFulfillmentReport({organizationId:`foreign-${suffix}`,workspaceId:scope.workspaceId});assert.equal(fulfillment.source,"POSTGRESQL_BUSINESS_APPLICATION_STORE");assert.equal(fulfillment.summary.workOrders,1);assert.equal(fulfillment.summary.controlIssues,0);assert.equal(foreignFulfillment.summary.workOrders,0);
    const work=await store.createWorkItem({applicationId:"intelligent-manufacturing-erp",businessObjectId:order.id,assignmentType:"AGENT",assigneeId:"manufacturing-readiness-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`manufacturing-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"检查生产工单开工就绪条件",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"COMPLETED");assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.bomDisplayKey,bom.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.sopDisplayKey,sop.displayKey);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_WORK_ORDER_RELEASE_FOR_HUMAN_APPROVAL");
  }finally{await pool.end();}
});

test("HR onboarding workflow persists a professional administrative-readiness pass across the evidence chain",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`hr-runner-org-${suffix}`,workspaceId:`hr-runner-workspace-${suffix}`,projectId:"hr-runner-project",userId:"hr-operator"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,advance=async(record,statuses)=>{let current=record;for(const status of statuses)current=await store.transitionRecord("human-resources-platform",record.id,{expectedVersion:current.version,status},scope);return current;},approve=async(record,requestedStatus)=>{const approval=await store.requestApproval("human-resources-platform",record.id,{expectedVersion:record.version,requestedStatus},scope);return(await store.decideApproval("human-resources-platform",approval.id,{decision:"APPROVED"},{...scope,userId:"hr-reviewer"})).record;};
    const positionDraft=await store.createRecord("human-resources-platform",{objectType:"position",title:"经营分析负责人",displayKey:`POS-${suffix}`,fields:{positionCode:"POS-OA-01",positionName:"经营分析负责人",department:"经营中心",jobFamily:"经营管理",grade:"M2",headcount:1}},scope),position=await approve(await advance(positionDraft,["REVIEWING","WAITING_APPROVAL"]),"ACTIVE"),recruitmentDraft=await store.createRecord("human-resources-platform",{objectType:"recruitment_case",title:"招聘经营分析负责人",displayKey:`REC-${suffix}`,fields:{department:"经营中心",positionName:"经营分析负责人",headcount:1,targetDate:"2026-08-01",employmentType:"全职",reason:"经批准的关键岗位补充"}},scope),recruitment=await approve(await advance(recruitmentDraft,["OPEN","SCREENING","INTERVIEWING","OFFER","WAITING_APPROVAL"]),"COMPLETED"),candidateDraft=await store.createRecord("human-resources-platform",{objectType:"candidate_application",title:"候选申请 CAND-001",displayKey:`CAND-${suffix}`,fields:{candidateRef:"CAND-001",positionName:"经营分析负责人",source:"内推",consentStatus:"已授权",privacyNoticeVersion:"PRIVACY-2026-01",humanSelectionDecisionRef:"HUMAN-PANEL-DECISION-001"}},scope),candidate=await approve(await advance(candidateDraft,["SCREENING","INTERVIEWING","WAITING_APPROVAL"]),"SELECTED"),offerDraft=await store.createRecord("human-resources-platform",{objectType:"employment_offer",title:"经营分析负责人录用通知",displayKey:`OFFER-${suffix}`,fields:{candidateRef:"CAND-001",department:"经营中心",positionName:"经营分析负责人",employmentType:"全职",proposedStartDate:"2026-08-01",offerDocumentRef:"OFFER-DOC-001"}},scope),offerApproved=await approve(await advance(offerDraft,["REVIEWING","WAITING_APPROVAL"]),"APPROVED"),offer=await store.transitionRecord("human-resources-platform",offerApproved.id,{expectedVersion:offerApproved.version,status:"ACCEPTED"},scope),onboarding=await store.createRecord("human-resources-platform",{objectType:"onboarding_case",title:"候选人甲入职准备",displayKey:`ONB-${suffix}`,fields:{employeeName:"候选人甲",candidateRef:"CAND-001",department:"经营中心",positionName:"经营分析负责人",employmentType:"全职",startDate:"2026-08-01",manager:"经营中心负责人",identityVerificationRef:"IDV-001",contractDocumentRef:"CONTRACT-001",equipmentRequestRef:"EQUIP-001",accessProfileRef:"ACCESS-MIN-001"}},scope);
    await store.createRelation("human-resources-platform",position.id,{targetRecordId:recruitment.id,relationType:"STAFFED_BY"},scope);await store.createRelation("human-resources-platform",recruitment.id,{targetRecordId:candidate.id,relationType:"CONSIDERS"},scope);await store.createRelation("human-resources-platform",candidate.id,{targetRecordId:offer.id,relationType:"RECEIVES"},scope);await store.createRelation("human-resources-platform",offer.id,{targetRecordId:onboarding.id,relationType:"INITIATES"},scope);await store.createRelation("human-resources-platform",position.id,{targetRecordId:onboarding.id,relationType:"AUTHORIZES"},scope);await store.createRelation("human-resources-platform",recruitment.id,{targetRecordId:onboarding.id,relationType:"RESULTS_IN"},scope);const pipeline=await store.hrWorkforcePipeline(scope),foreignPipeline=await store.hrWorkforcePipeline({organizationId:`foreign-${suffix}`,workspaceId:scope.workspaceId});assert.equal(pipeline.source,"POSTGRESQL_BUSINESS_APPLICATION_STORE");assert.equal(pipeline.summary.activePositions,1);assert.equal(pipeline.summary.selectedCandidates,1);assert.equal(pipeline.summary.acceptedOffers,1);assert.equal(pipeline.summary.controlIssues,0);assert.equal(foreignPipeline.summary.positions,0);assert.doesNotMatch(JSON.stringify(pipeline),/候选人甲|IDV-001|CONTRACT-001/);
    const work=await store.createWorkItem({applicationId:"human-resources-platform",businessObjectId:onboarding.id,assignmentType:"AGENT",assigneeId:"hr-onboarding-control-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`hr-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"检查入职行政准备和人工决策证据",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"COMPLETED");assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.positionDisplayKey,position.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.candidateApplicationDisplayKey,candidate.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.offerDisplayKey,offer.displayKey);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_ONBOARDING_READINESS_FOR_HUMAN_APPROVAL");
  }finally{await pool.end();}
});

test("growth publish-plan workflow persists a professional human-gated readiness pass",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`growth-runner-org-${suffix}`,workspaceId:`growth-runner-workspace-${suffix}`,projectId:"growth-runner-project",userId:"sales-operator"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,advance=async(record,statuses)=>{let current=record;for(const status of statuses)current=await store.transitionRecord("ai-growth-sales-platform",record.id,{expectedVersion:current.version,status},scope);return current;},approve=async(record,requestedStatus)=>{const approval=await store.requestApproval("ai-growth-sales-platform",record.id,{expectedVersion:record.version,requestedStatus},scope);return(await store.decideApproval("ai-growth-sales-platform",approval.id,{decision:"APPROVED"},{...scope,userId:"sales-reviewer"})).record;};
    const productDraft=await store.createRecord("ai-growth-sales-platform",{objectType:"product",title:"智能能源网关",displayKey:`PROD-${suffix}`,fields:{productCode:"PROD-001",category:"工业物联网",targetAudience:"制造企业能源管理负责人",price:6800,evidence:"受控产品规格书 SPEC-001"}},scope),product=await approve(await advance(productDraft,["REVIEWING","WAITING_APPROVAL"]),"ACTIVE"),campaignDraft=await store.createRecord("ai-growth-sales-platform",{objectType:"campaign",title:"能源网关视频号 Campaign",displayKey:`CAM-${suffix}`,fields:{productCode:"PROD-001",channel:"视频号",startDate:"2026-08-01",endDate:"2026-08-31",budget:10000,conversionGoal:"获取经授权的产品咨询"}},scope),campaign=await advance(campaignDraft,["PLANNING"]),assetDraft=await store.createRecord("ai-growth-sales-platform",{objectType:"content_asset",title:"能源网关短视频",displayKey:`ASSET-${suffix}`,fields:{productCode:"PROD-001",assetType:"短视频",channel:"视频号",language:"zh-CN",claimEvidenceRef:"CLAIM-SPEC-001",rightsClearanceRef:"RIGHTS-001",contentHash:"sha256:controlled-content"}},scope),asset=await approve(await advance(assetDraft,["GENERATING","REVIEWING","WAITING_APPROVAL"]),"APPROVED"),accountDraft=await store.createRecord("ai-growth-sales-platform",{objectType:"channel_account",title:"集团视频号",displayKey:`ACCOUNT-${suffix}`,fields:{platform:"视频号",accountRef:"ACCOUNT-001",ownerOrganization:"金湖集团",credentialReferenceId:"video-channel-ref",authorizationExpiresAt:"2026-12-31",publishingScope:"仅限已审批的产品内容"}},scope),account=await approve(await advance(accountDraft,["VERIFYING","WAITING_APPROVAL"]),"ACTIVE"),plan=await store.createRecord("ai-growth-sales-platform",{objectType:"publish_plan",title:"能源网关视频号发布计划",displayKey:`PUB-${suffix}`,fields:{campaignRef:campaign.displayKey,productCode:"PROD-001",channel:"视频号",accountRef:"ACCOUNT-001",scheduledAt:"2026-08-15",expectedAssetCount:1,publishMode:"人工确认后自动发布"}},scope);
    await store.createRelation("ai-growth-sales-platform",product.id,{targetRecordId:campaign.id,relationType:"PROMOTED_BY"},scope);await store.createRelation("ai-growth-sales-platform",product.id,{targetRecordId:asset.id,relationType:"GROUNDS"},scope);await store.createRelation("ai-growth-sales-platform",campaign.id,{targetRecordId:asset.id,relationType:"PRODUCES"},scope);await store.createRelation("ai-growth-sales-platform",campaign.id,{targetRecordId:plan.id,relationType:"SCHEDULES"},scope);await store.createRelation("ai-growth-sales-platform",asset.id,{targetRecordId:plan.id,relationType:"INCLUDES"},scope);await store.createRelation("ai-growth-sales-platform",account.id,{targetRecordId:plan.id,relationType:"AUTHORIZES"},scope);
    const work=await store.createWorkItem({applicationId:"ai-growth-sales-platform",businessObjectId:plan.id,assignmentType:"AGENT",assigneeId:"growth-publishing-control-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`growth-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"检查产品内容和渠道发布就绪条件",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"COMPLETED");assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.campaignDisplayKey,campaign.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.approvedAssetCount,1);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_PUBLISH_PLAN_FOR_HUMAN_APPROVAL");assert.equal(persisted.resultSummary.professionalOutcome.facts.credentialReferenceId,undefined);
  }finally{await pool.end();}
});

test("strategy review workflow persists evidence-backed gaps and governed corrective actions",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`strategy-runner-org-${suffix}`,workspaceId:`strategy-runner-workspace-${suffix}`,projectId:"strategy-runner-project",userId:"strategy-operator"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,advance=async(record,statuses)=>{let current=record;for(const status of statuses)current=await store.transitionRecord("enterprise-strategy-platform",record.id,{expectedVersion:current.version,status},scope);return current;};
    const objective=await advance(await store.createRecord("enterprise-strategy-platform",{objectType:"objective",title:"提升集团经营质量",displayKey:`OBJ-${suffix}`,fields:{period:"2026-2028",perspective:"运营",targetValue:90,unit:"%",responsibleCenter:"集团经营中心"}},scope),["ACTIVE","AT_RISK"]),kpi=await advance(await store.createRecord("enterprise-strategy-platform",{objectType:"kpi",title:"经营质量指数",displayKey:`KPI-${suffix}`,fields:{period:"2026-Q2",baseline:75,targetValue:90,actualValue:80,direction:"越高越好",unit:"%",ownerDepartment:"集团经营中心",actualAsOf:"2026-07-15",actualEvidenceRef:"KPI-SOURCE-001"}},scope),["ACTIVE","AT_RISK"]),initiative=await advance(await store.createRecord("enterprise-strategy-platform",{objectType:"initiative",title:"经营质量提升专项",displayKey:`INIT-${suffix}`,fields:{objectiveCode:objective.displayKey,ownerCenter:"集团经营中心",startDate:"2026-01-01",dueDate:"2026-06-30",milestone:"完成经营诊断与整改",progressPercent:80,progressAsOf:"2026-07-15",progressEvidenceRef:"INIT-SOURCE-001"}},scope),["ACTIVE","AT_RISK"]),review=await advance(await store.createRecord("enterprise-strategy-platform",{objectType:"strategy_review",title:"2026 年二季度经营复盘",displayKey:`REVIEW-${suffix}`,fields:{period:"2026-Q2",scope:"集团经营质量",reviewDate:"2026-07-21",evidenceCutoffDate:"2026-07-20",actualResult:"经营质量指标低于目标",varianceReason:"重点举措延期"}},scope),["ANALYZING"]),action=await advance(await store.createRecord("enterprise-strategy-platform",{objectType:"corrective_action",title:"经营质量纠偏",displayKey:`ACTION-${suffix}`,fields:{actionCode:"ACTION-001",ownerCenter:"集团经营中心",dueDate:"2026-08-31",actionDescription:"完成延期事项并复核经营指标",expectedImpact:"经营质量指数恢复至目标区间",evidenceRequirement:"验收报告"}},scope),["ACTIVE"]);
    await store.createRelation("enterprise-strategy-platform",objective.id,{targetRecordId:kpi.id,relationType:"MEASURED_BY"},scope);await store.createRelation("enterprise-strategy-platform",objective.id,{targetRecordId:initiative.id,relationType:"DELIVERED_BY"},scope);await store.createRelation("enterprise-strategy-platform",objective.id,{targetRecordId:review.id,relationType:"REVIEWED_IN"},scope);await store.createRelation("enterprise-strategy-platform",kpi.id,{targetRecordId:review.id,relationType:"EVIDENCED_IN"},scope);await store.createRelation("enterprise-strategy-platform",initiative.id,{targetRecordId:review.id,relationType:"ASSESSED_IN"},scope);await store.createRelation("enterprise-strategy-platform",review.id,{targetRecordId:action.id,relationType:"RESULTS_IN"},scope);await store.createRelation("enterprise-strategy-platform",objective.id,{targetRecordId:action.id,relationType:"CORRECTED_BY"},scope);
    const work=await store.createWorkItem({applicationId:"enterprise-strategy-platform",businessObjectId:review.id,assignmentType:"AGENT",assigneeId:"strategy-review-control-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`strategy-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"核验战略复盘证据和纠偏闭环",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"WAITING_REVIEW");assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.objectiveDisplayKey,objective.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.kpiGapCount,1);assert.equal(persisted.resultSummary.professionalOutcome.facts.overdueInitiativeCount,1);assert.equal(persisted.resultSummary.professionalOutcome.facts.correctiveActionCount,1);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_STRATEGY_REVIEW_FOR_HUMAN_APPROVAL");assert.equal(persisted.resultSummary.professionalOutcome.facts.actualEvidenceRef,undefined);
  }finally{await pool.end();}
});

test("Smart Park service workflow persists an SLA-backed completion recommendation",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`park-runner-org-${suffix}`,workspaceId:`park-runner-workspace-${suffix}`,projectId:"park-runner-project",userId:"park-operator"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,enterpriseDraft=await store.createRecord("smart-park-platform",{objectType:"enterprise",title:"示例制造企业",displayKey:`ENT-${suffix}`,fields:{creditCode:"91330000EXAMPLE",industry:"智能制造",contactName:"王经理",contactPhone:"authorized-contact-ref",requestedArea:2000}},scope),prospect=await store.transitionRecord("smart-park-platform",enterpriseDraft.id,{expectedVersion:enterpriseDraft.version,status:"PROSPECT"},scope),qualifying=await store.transitionRecord("smart-park-platform",enterpriseDraft.id,{expectedVersion:prospect.version,status:"QUALIFYING"},scope),waiting=await store.transitionRecord("smart-park-platform",enterpriseDraft.id,{expectedVersion:qualifying.version,status:"WAITING_APPROVAL"},scope),approval=await store.requestApproval("smart-park-platform",enterpriseDraft.id,{expectedVersion:waiting.version,requestedStatus:"ADMITTED"},scope),admitted=(await store.decideApproval("smart-park-platform",approval.id,{decision:"APPROVED"},{...scope,userId:"park-reviewer"})).record,enterprise=await store.transitionRecord("smart-park-platform",enterpriseDraft.id,{expectedVersion:admitted.version,status:"ACTIVE"},scope),orderDraft=await store.createRecord("smart-park-platform",{objectType:"service_order",title:"厂房空调报修",displayKey:`SVC-${suffix}`,fields:{enterpriseName:enterprise.title,serviceType:"报修",location:"A1 厂房",requestedAt:"2026-07-21T08:00:00Z",slaHours:4,priority:"紧急",assignedTeam:"设施服务班组",description:"空调无法启动",resolutionSummary:"更换控制器并完成复测",completionEvidenceRef:"SERVICE-EVIDENCE-001",resolvedAt:"2026-07-21T10:30:00Z"}},scope),open=await store.transitionRecord("smart-park-platform",orderDraft.id,{expectedVersion:orderDraft.version,status:"OPEN"},scope),dispatched=await store.transitionRecord("smart-park-platform",orderDraft.id,{expectedVersion:open.version,status:"DISPATCHED"},scope),order=await store.transitionRecord("smart-park-platform",orderDraft.id,{expectedVersion:dispatched.version,status:"IN_PROGRESS"},scope);await store.createRelation("smart-park-platform",enterprise.id,{targetRecordId:order.id,relationType:"REQUESTS"},scope);
    const work=await store.createWorkItem({applicationId:"smart-park-platform",businessObjectId:order.id,assignmentType:"AGENT",assigneeId:"park-service-control-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`park-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"核验园区服务工单 SLA 和完工证据",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"WAITING_APPROVAL");assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.enterpriseDisplayKey,enterprise.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.slaMet,true);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_SERVICE_COMPLETION_FOR_HUMAN_APPROVAL");assert.equal(persisted.resultSummary.professionalOutcome.facts.completionEvidenceRef,undefined);
  }finally{await pool.end();}
});
