import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { ensurePostgresFixture,createTestPool } from "../../orchestrator-core/lib/postgres-fixture.mjs";
import { PersistentNightShiftService } from "../../orchestrator-core/lib/persistent-night-shift.mjs";
import { createBusinessApplicationRuntime } from "../lib/business-database.mjs";
import { loadDomainRuntimeRegistry } from "../lib/domain-center.mjs";
import { PersistentBusinessWorkExecutor } from "../lib/persistent-business-work-executor.mjs";
import { ResidentBusinessWorkRunner } from "../lib/resident-business-work-runner.mjs";

const expenseFields={expenseDate:"2026-07-21",department:"运营中心",category:"采购",amount:2600,currency:"CNY",budgetCode:"OPS-01",description:"常驻 Runner 验收"};

test("resident business runner resumes persisted work and isolates item failures",async()=>{
  let pending=[{id:"work-1"},{id:"work-2"}],completed=[];const errors=[],store={runnableAgentWorkItems:async()=>pending};
  const runner=new ResidentBusinessWorkRunner({store,pollMs:50,executeWork:async item=>{if(item.id==="work-1")throw Object.assign(new Error("controlled"),{code:"CONTROLLED_FAILURE"});pending=pending.filter(value=>value.id!==item.id);completed.push(item.id);},onError:(error,item)=>errors.push([error.code,item.id])});
  await runner.tick();await runner.tick();assert.deepEqual(completed,["work-2"]);assert.deepEqual(errors,[["CONTROLLED_FAILURE","work-1"]]);assert.equal(runner.snapshot().failed,1);assert.equal(runner.snapshot().completed,1);assert.equal(runner.snapshot().active,0);assert.equal(runner.snapshot().deferred,1);
});

test("resident runner fails closed and honors persistent drain control",async()=>{
  let desiredState="DRAINING",scans=0,executions=0,stopped=0;const registry={register:async()=>({status:"DRAINING",desiredState,version:1,lastHeartbeatAt:new Date().toISOString()}),heartbeat:async()=>({status:desiredState,desiredState,version:2,lastHeartbeatAt:new Date().toISOString()}),stop:async()=>{stopped+=1;return{status:"OFFLINE",desiredState,version:3};}},store={runnableAgentWorkItems:async()=>{scans+=1;return[{id:"governed-work"}];}};
  const runner=new ResidentBusinessWorkRunner({store,executeWork:async()=>{executions+=1;},nodeRegistry:registry,nodeKey:"runner:test"});
  await runner.tick();assert.equal(scans,0);assert.equal(executions,0);assert.equal(runner.snapshot().desiredState,"DRAINING");desiredState="ONLINE";await runner.tick();assert.equal(scans,1);assert.equal(executions,1);await runner.stop();assert.equal(stopped,1);
  const denied=new ResidentBusinessWorkRunner({store,executeWork:async()=>{executions+=1;},nodeRegistry:{register:async()=>{throw Object.assign(new Error("database unavailable"),{code:"REGISTRY_DOWN"});}},nodeKey:"runner:down"});await denied.tick();assert.equal(scans,1);assert.equal(denied.snapshot().lastError.code,"REGISTRY_DOWN");
});

test("two resident runners execute one persisted business session exactly once after restart",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`resident-org-${suffix}`,workspaceId:`resident-workspace-${suffix}`,projectId:"resident-project",userId:"finance-user"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,record=await store.createRecord("finance-platform",{objectType:"expense",title:"常驻业务执行",displayKey:`RESIDENT-${suffix}`,fields:expenseFields},scope),work=await store.createWorkItem({applicationId:"finance-platform",businessObjectId:record.id,assignmentType:"AGENT",assigneeId:"agent-finance"},scope),night=new PersistentNightShiftService(pool),sessionKey=`resident-business-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"生成财务检查报告",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})}),runnerStore={runnableAgentWorkItems:async()=>{const item=await store.getWorkItemForRunner(attached.id);return item?.status==="RUNNING"?[item]:[];}},first=new ResidentBusinessWorkRunner({store:runnerStore,pool,executeWork:item=>executor.execute(item)}),second=new ResidentBusinessWorkRunner({store:runnerStore,pool,executeWork:item=>executor.execute(item)});
    assert.equal((await store.getWorkItemForRunner(attached.id)).status,"RUNNING");assert.equal((await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version})).version,attached.version);await assert.rejects(()=>store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:randomUUID(),report:null,status:"RUNNING",expectedWorkVersion:work.version}),error=>error.code==="BUSINESS_WORK_VERSION_CONFLICT");await Promise.all([first.tick(),second.tick()]);const persisted=await store.getWorkItemForRunner(attached.id),report=await night.loadReport(session.id),attempts=Number((await pool.query("SELECT count(*) count FROM ad_task_attempt a JOIN ad_task t ON t.id=a.task_id WHERE t.goal_id=$1",[session.goal_id])).rows[0].count);assert.equal(persisted.status,"BLOCKED",JSON.stringify({first:first.snapshot(),second:second.snapshot()}));assert.equal(persisted.resultSummary.resultType,"PROFESSIONAL_BUSINESS_OUTCOME");assert.equal(persisted.resultSummary.businessOutcomeProduced,true);assert.equal(persisted.resultSummary.professionalOutcome.decision,"BLOCKED");assert.equal(persisted.resultSummary.stages.length,report.totalTasks);assert.equal(report.sessionStatus,"SUCCEEDED");assert.equal(attempts,report.totalTasks);assert.equal(first.snapshot().claimed+second.snapshot().claimed,1);assert.equal(first.snapshot().completed+second.snapshot().completed,1);assert.deepEqual(await runnerStore.runnableAgentWorkItems(),[]);
  }finally{await pool.end();}
});

test("finance expense workflow produces a persisted professional pass from an approved active budget",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`finance-runner-org-${suffix}`,workspaceId:`finance-runner-workspace-${suffix}`,projectId:"finance-runner-project",userId:"finance-user"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store,budget0=await store.createRecord("finance-platform",{objectType:"budget",title:"运营预算",displayKey:`BUD-${suffix}`,fields:{fiscalYear:2026,department:"运营中心",budgetCode:"OPS-01",amount:10000,currency:"CNY"}},scope),budget1=await store.transitionRecord("finance-platform",budget0.id,{expectedVersion:1,status:"SUBMITTED"},scope),budget2=await store.transitionRecord("finance-platform",budget0.id,{expectedVersion:2,status:"WAITING_APPROVAL"},scope),approval=await store.requestApproval("finance-platform",budget0.id,{expectedVersion:budget2.version,requestedStatus:"APPROVED"},scope),approved=(await store.decideApproval("finance-platform",approval.id,{decision:"APPROVED"},{...scope,userId:"finance-reviewer"})).record,budget=await store.transitionRecord("finance-platform",budget0.id,{expectedVersion:approved.version,status:"ACTIVE"},scope),expense=await store.createRecord("finance-platform",{objectType:"expense",title:"受控采购费用",displayKey:`EXP-${suffix}`,fields:expenseFields},scope);assert.equal(budget.status,"ACTIVE");await store.createRelation("finance-platform",budget.id,{targetRecordId:expense.id,relationType:"CONTROLS"},scope);
    const work=await store.createWorkItem({applicationId:"finance-platform",businessObjectId:expense.id,assignmentType:"AGENT",assigneeId:"finance-control-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`finance-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"审核费用预算合规",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"COMPLETED");assert.equal(persisted.resultSummary.businessOutcomeProduced,true);assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.budgetDisplayKey,budget.displayKey);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_FOR_HUMAN_APPROVAL");
  }finally{await pool.end();}
});

test("manufacturing work-order workflow persists a professional release-readiness pass",async()=>{
  await ensurePostgresFixture();const pool=createTestPool(),suffix=randomUUID(),scope={organizationId:`manufacturing-runner-org-${suffix}`,workspaceId:`manufacturing-runner-workspace-${suffix}`,projectId:"manufacturing-runner-project",userId:"manufacturing-planner"};
  try{
    const store=(await createBusinessApplicationRuntime({repoRoot:process.cwd(),pool})).store;
    const release=async(objectType,input,reviewStatus)=>{const draft=await store.createRecord("intelligent-manufacturing-erp",{objectType,...input},scope),review=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:draft.version,status:reviewStatus},scope),waiting=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:review.version,status:"WAITING_APPROVAL"},scope),approval=await store.requestApproval("intelligent-manufacturing-erp",draft.id,{expectedVersion:waiting.version,requestedStatus:"RELEASED"},scope);return(await store.decideApproval("intelligent-manufacturing-erp",approval.id,{decision:"APPROVED"},{...scope,userId:"manufacturing-reviewer"})).record;};
    const bom=await release("bom",{title:"P-001 制造 BOM",displayKey:`BOM-${suffix}`,fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",componentCount:2,componentRequirements:"MAT-A:2,MAT-B:1"}},"ENGINEERING_REVIEW"),sop=await release("routing_sop",{title:"P-001 工艺路线",displayKey:`SOP-${suffix}`,fields:{productCode:"P-001",revision:"A",plant:"一号工厂",effectiveDate:"2026-07-01",operationCount:5,controlledDocumentRef:"WI-P001-A"}},"PROCESS_REVIEW"),createInventory=async(code,quantity)=>{const draft=await store.createRecord("intelligent-manufacturing-erp",{objectType:"inventory",title:`${code} 可用库存`,displayKey:`INV-${code}-${suffix}`,fields:{materialCode:code,warehouse:"原料仓",location:"A-01",batch:"202607",quantity,unit:"件"}},scope),counting=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:draft.version,status:"COUNTING"},scope),matched=await store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:counting.version,status:"MATCHED"},scope);return store.transitionRecord("intelligent-manufacturing-erp",draft.id,{expectedVersion:matched.version,status:"COMPLETED"},scope);},inventoryA=await createInventory("MAT-A",20),inventoryB=await createInventory("MAT-B",10),order=await store.createRecord("intelligent-manufacturing-erp",{objectType:"work_order",title:"P-001 生产工单",displayKey:`WO-${suffix}`,fields:{productCode:"P-001",quantity:10,unit:"台",dueDate:"2026-08-31",plant:"一号工厂",priority:"关键"}},scope);
    await store.createRelation("intelligent-manufacturing-erp",bom.id,{targetRecordId:order.id,relationType:"USED_BY"},scope);await store.createRelation("intelligent-manufacturing-erp",sop.id,{targetRecordId:order.id,relationType:"GOVERNS"},scope);await store.createRelation("intelligent-manufacturing-erp",inventoryA.id,{targetRecordId:order.id,relationType:"ALLOCATED_TO"},scope);await store.createRelation("intelligent-manufacturing-erp",inventoryB.id,{targetRecordId:order.id,relationType:"ALLOCATED_TO"},scope);
    const work=await store.createWorkItem({applicationId:"intelligent-manufacturing-erp",businessObjectId:order.id,assignmentType:"AGENT",assigneeId:"manufacturing-readiness-agent"},scope),night=new PersistentNightShiftService(pool),sessionKey=`manufacturing-professional-${suffix}`,session=await night.acceptGoal(sessionKey,{id:sessionKey,title:"检查生产工单开工就绪条件",scope}),attached=await store.attachWorkflow(work.id,{goalId:session.goal_id,sessionId:session.id,report:null,status:"RUNNING",expectedWorkVersion:work.version}),executor=new PersistentBusinessWorkExecutor({store,registry:await loadDomainRuntimeRegistry(),acquirePool:async()=>({pool,ownsPool:false})});await executor.execute(attached);const persisted=await store.getWorkItemForRunner(attached.id);assert.equal(persisted.status,"COMPLETED");assert.equal(persisted.resultSummary.professionalOutcome.decision,"PASS");assert.equal(persisted.resultSummary.professionalOutcome.facts.bomDisplayKey,bom.displayKey);assert.equal(persisted.resultSummary.professionalOutcome.facts.sopDisplayKey,sop.displayKey);assert.equal(persisted.resultSummary.nextAction,"SUBMIT_WORK_ORDER_RELEASE_FOR_HUMAN_APPROVAL");
  }finally{await pool.end();}
});
