import { assertTenantScope } from './domain-model.mjs';

const MODELS=new Set(['FIRST_TOUCH','LAST_TOUCH','LINEAR','POSITION_BASED']);
export function createAttributionEngine({scope:rawScope,model='POSITION_BASED',windowDays=90,clock=()=>new Date().toISOString()}={}){
  const scope=assertTenantScope(rawScope);if(!MODELS.has(model))throw new TypeError(`unsupported attribution model: ${model}`);const touches=[];const conversions=[];
  function recordTouch(input){if(!input.leadId||!input.channel)throw new TypeError('leadId and channel are required');const touch=Object.freeze({touchId:input.touchId??`touch_${crypto.randomUUID()}`,...scope,leadId:input.leadId,channel:input.channel,campaignId:input.campaignId??null,contentId:input.contentId??null,sourceRef:input.sourceRef??null,occurredAt:input.occurredAt??clock()});touches.push(touch);return touch;}
  function attribute({leadId,conversionId=`conversion_${crypto.randomUUID()}`,amount,currency='USD',convertedAt=clock()}={}){if(!leadId||!Number.isFinite(Number(amount)))throw new TypeError('leadId and numeric amount are required');const end=new Date(convertedAt).getTime(),start=end-windowDays*86400000;const eligible=touches.filter(t=>t.leadId===leadId&&new Date(t.occurredAt).getTime()>=start&&new Date(t.occurredAt).getTime()<=end).sort((a,b)=>new Date(a.occurredAt)-new Date(b.occurredAt));if(!eligible.length)return{conversionId,leadId,amount:Number(amount),currency,model,allocations:[],unattributed:Number(amount)};let weights=[];if(model==='FIRST_TOUCH')weights=eligible.map((_,i)=>i===0?1:0);else if(model==='LAST_TOUCH')weights=eligible.map((_,i)=>i===eligible.length-1?1:0);else if(model==='LINEAR')weights=eligible.map(()=>1/eligible.length);else if(eligible.length===1)weights=[1];else if(eligible.length===2)weights=[0.5,0.5];else weights=eligible.map((_,i)=>i===0||i===eligible.length-1?0.4:0.2/(eligible.length-2));const total=Number(amount);const allocations=eligible.map((touch,i)=>Object.freeze({...touch,weight:weights[i],attributedAmount:Math.round(total*weights[i]*100)/100}));const row=Object.freeze({conversionId,...scope,leadId,amount:total,currency,model,windowDays,convertedAt,allocations:Object.freeze(allocations),unattributed:0});conversions.push(row);return row;}
  function summarize(){const byChannel={};for(const c of conversions)for(const a of c.allocations){byChannel[a.channel]=(byChannel[a.channel]??0)+a.attributedAmount;}return{...scope,model,conversions:conversions.length,attributedRevenue:conversions.reduce((s,c)=>s+c.amount-c.unattributed,0),byChannel};}
  return{recordTouch,attribute,summarize,touches,conversions};
}
