import { spawn, spawnSync } from "node:child_process";
import { realpathSync } from "node:fs";
import { resolve, relative, isAbsolute } from "node:path";
import { once } from "node:events";

export class RuntimePolicyError extends Error { constructor(code,message){super(message);this.name="RuntimePolicyError";this.code=code;} }
const forbiddenEnv=/^(HOME|USERPROFILE|SSH_|AWS_|AZURE_|GOOGLE_|.*TOKEN.*|.*SECRET.*|.*PASSWORD.*|.*KEY.*)$/i;
const dangerous=/[;&|`\n]|\$\(|\bgit\s+(push|merge)\b|\b(kubectl|helm|terraform)\s+(apply|destroy)\b|\b(?:rm|find)\b[^\n]*(?:-rf|-delete)|\b(?:deploy|release)\b/i;
const within=(child,parent)=>{const r=relative(parent,child);return r===""||(!r.startsWith("..")&&!isAbsolute(r));};
export function redact(value,secrets=[]){let text=String(value);for(const secret of secrets.filter(Boolean))text=text.split(secret).join("[REDACTED]");return text.replace(/\b(?:sk-[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9]{12,})\b/g,"[REDACTED]");}
export function validateRuntimeRequest(request,context){
  for(const key of ["executionId","goalId","taskId","attemptId","workerId","sessionId","leaseId","runtimeType","instruction","workingDirectory"])if(!request[key])throw new RuntimePolicyError("INVALID_REQUEST",`Missing ${key}`);
  if(!Number.isSafeInteger(request.fencingToken)||request.fencingToken<1)throw new RuntimePolicyError("INVALID_REQUEST","Invalid fencingToken");
  if(!Number.isFinite(request.timeoutSeconds)||request.timeoutSeconds<=0||request.timeoutSeconds>context.maxRuntimeSeconds)throw new RuntimePolicyError("POLICY_DENIED","Runtime timeout exceeds policy");
  const root=realpathSync(context.projectRoot),cwd=realpathSync(request.workingDirectory);if(!within(cwd,root))throw new RuntimePolicyError("POLICY_DENIED","Working directory is outside registered project root");
  const allowed=(request.allowedPaths??[]).map(p=>resolve(root,p));if(!allowed.length||!allowed.some(p=>within(cwd,p)))throw new RuntimePolicyError("POLICY_DENIED","Working directory is outside allowedPaths");
  for(const p of request.blockedPaths??[]){const blocked=resolve(root,p);if(within(cwd,blocked))throw new RuntimePolicyError("POLICY_DENIED","Working directory is inside blockedPaths");}
  for(const p of [...request.allowedPaths,...request.blockedPaths])if(p.includes(".."))throw new RuntimePolicyError("POLICY_DENIED","Path traversal is forbidden");
  if(dangerous.test(request.instruction))throw new RuntimePolicyError("POLICY_DENIED","Instruction contains a forbidden command or shell metacharacter");
  for(const key of Object.keys(request.environment??{}))if(!context.environmentAllowlist.includes(key)||forbiddenEnv.test(key))throw new RuntimePolicyError("POLICY_DENIED",`Environment variable is not allowed: ${key}`);
  for(const p of request.blockedPaths??[])if(/(?:^|\/)(?:\.ssh|\.env(?:\.|$)|Library\/Keychains)(?:\/|$)/i.test(p))continue;
  return true;
}
export class MemoryRuntimeLogStore{#events=[];async appendBatch(events){this.#events.push(...events);}async list(id){return this.#events.filter(e=>e.executionId===id);}}
export class ProcessSupervisor{
  constructor({logStore=new MemoryRuntimeLogStore(),fencingPort={assertCurrent:async()=>{}},graceMs=250,maxLogBytes=1024*1024}={}){this.logStore=logStore;this.fencingPort=fencingPort;this.graceMs=graceMs;this.maxLogBytes=maxLogBytes;this.records=new Map();}
  start(request,{command,args=[],env={},secrets=[]}){if(this.records.has(request.executionId))throw new RuntimePolicyError("INVALID_REQUEST","Duplicate executionId");const startedAt=new Date();const child=spawn(command,args,{cwd:request.workingDirectory,env,shell:false,detached:process.platform!=="win32",stdio:["ignore","pipe","pipe"]});const rec={request,child,status:"RUNNING",startedAt,finishedAt:null,exitCode:null,signal:null,logs:[],sequence:0,bytes:0,errorCode:null,errorMessage:null,cancelPromise:null,timer:null,secrets};this.records.set(request.executionId,rec);
    const capture=(stream,chunk)=>{let message=redact(chunk.toString(),secrets);const remaining=this.maxLogBytes-rec.bytes;if(remaining<=0)return;message=message.slice(0,remaining);rec.bytes+=Buffer.byteLength(message);rec.logs.push({executionId:request.executionId,taskId:request.taskId,attemptId:request.attemptId,leaseId:request.leaseId,sequence:++rec.sequence,stream,level:stream==="stderr"?"ERROR":"INFO",message,timestamp:new Date().toISOString(),fencingToken:request.fencingToken});if(rec.logs.length>=20)this.flush(rec).catch(e=>{rec.flushError=e;});};child.stdout.on("data",c=>capture("stdout",c));child.stderr.on("data",c=>capture("stderr",c));
    child.once("error",e=>{rec.errorCode="SPAWN_FAILED";rec.errorMessage=redact(e.message,secrets);});child.once("exit",(code,signal)=>{clearTimeout(rec.timer);rec.exitCode=code;rec.signal=signal;rec.finishedAt=new Date();if(rec.status==="CANCELLING")rec.status="CANCELLED";else if(rec.status!=="TIMED_OUT")rec.status=code===0?"SUCCEEDED":"FAILED";if(code!==0&&!rec.errorCode)rec.errorCode="NON_ZERO_EXIT";this.flush(rec);});rec.timer=setTimeout(()=>this.cancel(request.executionId,{source:"TIMEOUT",requestedAt:new Date().toISOString()}),request.timeoutSeconds*1000);return {executionId:request.executionId,attemptId:request.attemptId,leaseId:request.leaseId,fencingToken:request.fencingToken,status:"RUNNING",pid:child.pid??null,startedAt:startedAt.toISOString(),finishedAt:null};}
  async flush(rec){if(!rec.logs.length)return;await this.fencingPort.assertCurrent(rec.request);const batch=rec.logs.splice(0);await this.logStore.appendBatch(batch);}
  signal(rec,signal){if(rec.child.exitCode!==null)return;try{process.kill(process.platform==="win32"?rec.child.pid:-rec.child.pid,signal);}catch(e){if(e.code!=="ESRCH")throw e;}}
  async cancel(id,cancellation){const rec=this.records.get(id);if(!rec)throw new RuntimePolicyError("INVALID_REQUEST","Unknown execution");if(rec.finishedAt)return;if(rec.cancelPromise)return rec.cancelPromise;rec.status=cancellation.source==="TIMEOUT"?"TIMED_OUT":"CANCELLING";rec.errorCode=cancellation.source==="TIMEOUT"?"TIMEOUT":"CANCELLED";rec.cancelPromise=(async()=>{this.signal(rec,"SIGTERM");await Promise.race([once(rec.child,"exit"),new Promise(r=>setTimeout(r,this.graceMs))]);if(rec.child.exitCode===null)this.signal(rec,"SIGKILL");})();return rec.cancelPromise;}
  async forceTerminate(id){const rec=this.records.get(id);if(!rec||rec.finishedAt)return;if(!rec.errorCode)rec.errorCode="CANCELLED";rec.status="CANCELLING";this.signal(rec,"SIGKILL");}
  async result(id){const rec=this.records.get(id);if(!rec)throw new RuntimePolicyError("INVALID_REQUEST","Unknown execution");if(!rec.finishedAt)await once(rec.child,"exit");await this.flush(rec);if(rec.flushError)throw rec.flushError;const finished=rec.finishedAt??new Date();return {executionId:id,status:rec.status,exitCode:rec.exitCode,signal:rec.signal,startedAt:rec.startedAt.toISOString(),finishedAt:finished.toISOString(),durationMs:finished-rec.startedAt,stdoutRef:`memory://${id}/stdout`,stderrRef:`memory://${id}/stderr`,logRef:`memory://${id}/logs`,artifactRefs:[],commitHash:null,errorCode:rec.errorCode,errorMessage:rec.errorMessage,metadata:{pid:rec.child.pid},taskId:rec.request.taskId,attemptId:rec.request.attemptId,leaseId:rec.request.leaseId,fencingToken:rec.request.fencingToken};}
  async cleanup(id){const rec=this.records.get(id);if(!rec)return;if(!rec.finishedAt)await this.forceTerminate(id);this.records.delete(id);}
  async cleanupOrphans(activeIds=[]){for(const [id,rec] of this.records)if(!activeIds.includes(id)&&!rec.finishedAt)await this.forceTerminate(id);}
}
class BaseAdapter{constructor(type,{supervisor,context,fencingPort}){this.runtimeType=type;this.supervisor=supervisor;this.context=context;this.fencingPort=fencingPort;this.supervisor.fencingPort=fencingPort;}validateRequest(r,c=this.context){return validateRuntimeRequest(r,c);}getCapabilities(){return{runtimeType:this.runtimeType,configured:true,supportsStreaming:true,supportsCancel:true,supportsForceKill:true,supportsArtifacts:false,maxRuntimeSeconds:this.context.maxRuntimeSeconds};}async prepare(r,c=this.context){this.validateRequest(r,c);await this.fencingPort.assertCurrent(r);}async *streamLogs(id){for(const event of await this.supervisor.logStore.list(id))yield event;}async cancel(id,c){return this.supervisor.cancel(id,c);}async forceTerminate(id){return this.supervisor.forceTerminate(id);}async collectResult(id){const result=await this.supervisor.result(id);await this.fencingPort.assertCurrent(result);return result;}async cleanup(id){return this.supervisor.cleanup(id);}}
export class GenericProcessAdapter extends BaseAdapter{constructor(options){super("GENERIC_PROCESS",options);this.command=options.command;this.argsFactory=options.argsFactory??(r=>[r.instruction]);this.baseEnvironment=options.baseEnvironment??{};}async healthCheck(){return{status:this.command?"HEALTHY":"NOT_CONFIGURED"};}async start(r,c=this.context){await this.prepare(r,c);if(r.dryRun)return dryExecution(r);return this.supervisor.start(r,{command:this.command,args:this.argsFactory(r),env:{...this.baseEnvironment,...r.environment},secrets:c.secrets});}}
export class CodexCliAdapter extends GenericProcessAdapter{constructor(options){super({...options,command:options.cliPath??"codex",argsFactory:r=>["exec",r.instruction]});this.runtimeType="CODEX";this.enabled=options.enabled??process.env.AUTONOMOUS_RUNTIME_CODEX_ENABLED==="true";this.cliPath=options.cliPath??"codex";}async healthCheck(){if(!this.enabled)return{status:"DISABLED",message:"AUTONOMOUS_RUNTIME_CODEX_ENABLED=false"};const out=spawnSync(this.cliPath,["--version"],{encoding:"utf8",shell:false,timeout:3000});return out.status===0?{status:"HEALTHY",version:(out.stdout||out.stderr).trim()}:{status:"NOT_CONFIGURED",message:"Codex CLI unavailable"};}async start(r,c=this.context){if(!this.enabled)throw new RuntimePolicyError("NOT_CONFIGURED","Codex execution is disabled by default");return super.start(r,c);}}
export class ControlledStubAdapter extends BaseAdapter{constructor(options={}){super("CONTROLLED_STUB",options);this.behavior=options.behavior??"success";this.results=new Map();}async healthCheck(){return{status:"HEALTHY"};}async start(r,c=this.context){await this.prepare(r,c);const now=new Date().toISOString(),status=this.behavior==="success"?"SUCCEEDED":"FAILED";this.results.set(r.executionId,{executionId:r.executionId,status,exitCode:status==="SUCCEEDED"?0:1,signal:null,startedAt:now,finishedAt:now,durationMs:0,stdoutRef:null,stderrRef:null,logRef:null,artifactRefs:[],commitHash:null,errorCode:status==="FAILED"?"NON_ZERO_EXIT":null,errorMessage:null,metadata:{controlledStub:true,dryRun:!!r.dryRun},taskId:r.taskId,attemptId:r.attemptId,leaseId:r.leaseId,fencingToken:r.fencingToken});return{executionId:r.executionId,attemptId:r.attemptId,leaseId:r.leaseId,fencingToken:r.fencingToken,status,pid:null,startedAt:now,finishedAt:now};}async *streamLogs(){}async collectResult(id){const result=this.results.get(id);if(!result)throw new RuntimePolicyError("INVALID_REQUEST","Unknown execution");await this.fencingPort.assertCurrent(result);return result;}async cancel(){}async forceTerminate(){}async cleanup(id){this.results.delete(id);}}
export class UnsupportedAdapter{constructor(type){this.runtimeType=type;}getCapabilities(){return{runtimeType:this.runtimeType,configured:false,supportsStreaming:false,supportsCancel:false,supportsForceKill:false,supportsArtifacts:false,maxRuntimeSeconds:0};}async healthCheck(){return{status:"UNSUPPORTED"};}async start(){throw new RuntimePolicyError("UNSUPPORTED",`${this.runtimeType} is not configured`);}}
const dryExecution=r=>({executionId:r.executionId,attemptId:r.attemptId,leaseId:r.leaseId,fencingToken:r.fencingToken,status:"SUCCEEDED",pid:null,startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),dryRun:true});
export class RuntimeRegistry{constructor(){this.adapters=new Map();}registerAdapter(adapter){if(this.adapters.has(adapter.runtimeType))throw new RuntimePolicyError("INVALID_REQUEST",`Duplicate adapter: ${adapter.runtimeType}`);this.adapters.set(adapter.runtimeType,adapter);return adapter;}get(type){const adapter=this.adapters.get(type);if(!adapter)throw new RuntimePolicyError("NOT_CONFIGURED",`Adapter not registered: ${type}`);return adapter;}listAdapters(){return [...this.adapters.values()].map(a=>a.getCapabilities());}async adapterHealth(type){return this.get(type).healthCheck();}}
export class RuntimeService{constructor({registry,fencingPort}){this.registry=registry;this.fencingPort=fencingPort;this.executions=new Map();}registerAdapter(a){return this.registry.registerAdapter(a);}listAdapters(){return this.registry.listAdapters();}adapterHealth(t){return this.registry.adapterHealth(t);}async startExecution(r,c){await this.fencingPort.assertCurrent(r);const e=await this.registry.get(r.runtimeType).start(r,c);this.executions.set(r.executionId,{...e,runtimeType:r.runtimeType});return e;}getExecution(id){return this.executions.get(id)??null;}cancelExecution(id,c){const e=this.executions.get(id);if(!e)throw new RuntimePolicyError("INVALID_REQUEST","Unknown execution");return this.registry.get(e.runtimeType).cancel(id,c);}getExecutionLogs(id){const e=this.executions.get(id);if(!e)throw new RuntimePolicyError("INVALID_REQUEST","Unknown execution");return this.registry.get(e.runtimeType).streamLogs(id);}collectExecutionResult(id){const e=this.executions.get(id);if(!e)throw new RuntimePolicyError("INVALID_REQUEST","Unknown execution");return this.registry.get(e.runtimeType).collectResult(id);}}
