import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const repoRoot=resolve(packageRoot,"../..");
const paths={
  skills:resolve(repoRoot,"packages/skill-router/registry/skill-registry.json"),
  skillRules:resolve(repoRoot,"packages/skill-router/registry/skill-router-rules.json"),
  agents:resolve(repoRoot,"packages/orchestrator-core/schemas/agent-registry/agent-registry.example.json"),
  workers:resolve(repoRoot,"packages/worker-pool/examples/worker-registry.example.json")
};

export const studioDomains=Object.freeze([
  {id:"asset-docs-portal",name:"资产、门户与文档",nameEn:"Assets, Portal & Documentation",agentId:"agent-1",icon:"DOC",summary:"资产空间、租户门户、Runtime 文档、产品说明和内容索引。",skillTypes:["document_generation","code_development"],keywords:["资产","空间","租户","门户","文档","手册","索引","docs","portal"],maturity:"RUNTIME_BOUND",nextMilestone:"通过文档 Worker 生成可验证产物。"},
  {id:"validation-finance",name:"验证、兼容与财务",nameEn:"Validation, Compatibility & Finance",agentId:"agent-2",icon:"QA",summary:"验证矩阵、兼容性、财务合同、收款发票和审计 Runbook。",skillTypes:["validation_testing","spreadsheet_analysis","code_development"],keywords:["验证","测试","审计","兼容","财务","合同","收款","发票","validation","finance"],maturity:"PARTIAL",nextMilestone:"补齐 spreadsheet 在线 Worker 后形成完整闭环。"},
  {id:"iot-operations",name:"IoT、安全、工单与能耗",nameEn:"IoT, Safety, Work Orders & Energy",agentId:"agent-3",icon:"IoT",summary:"设备、传感器、安全隐患、告警、工单、巡检、能耗和运行数据。",skillTypes:["data_integration","code_development","validation_testing"],keywords:["设备","传感器","安全","隐患","告警","工单","能耗","巡检","iot","work order"],maturity:"RUNTIME_BOUND",nextMilestone:"接入授权数据 Fixture 和领域验收合同。"},
  {id:"experience-access",name:"前端、体验、移动与权限",nameEn:"Frontend, UX, Mobile & RBAC",agentId:"agent-4",icon:"UI",summary:"页面、样式、Dashboard、移动端、菜单、RBAC 和智能选择器。",skillTypes:["code_development","image_generation","slide_generation"],keywords:["前端","页面","样式","仪表盘","移动端","菜单","权限","ui","ux","rbac"],maturity:"PARTIAL",nextMilestone:"将视觉和移动专用 Runtime 纳入统一 Worker 协议。"},
  {id:"planning-platform",name:"规划、发布与平台",nameEn:"Planning, Release & Platform",agentId:"agent-5",icon:"PLAN",summary:"Goal Engine、架构、发布门、生产准备、恢复和跨领域兜底。",skillTypes:["code_development","evolution_observer","web_research","validation_testing"],keywords:["规划","目标","发布","平台","架构","部署","恢复","goal","release","platform"],maturity:"PARTIAL",nextMilestone:"补齐 research 和 observer 常驻 Runner。"}
]);

const normalize=value=>String(value??"").toLowerCase();
const matches=(text,keywords)=>(keywords??[]).filter(keyword=>normalize(text).includes(normalize(keyword)));
const readJson=async path=>JSON.parse(await readFile(path,"utf8"));
export function getStudioDomain(id){return studioDomains.find(domain=>domain.id===id)??null;}
export function routeStudioDomain(goal,{explicitDomainId=null}={}){if(explicitDomainId){const explicit=getStudioDomain(explicitDomainId);if(!explicit)throw Object.assign(new Error("DOMAIN_NOT_FOUND"),{code:"DOMAIN_NOT_FOUND"});return{domainId:explicit.id,confidence:1,source:"EXPLICIT",alternatives:[]};}const scored=studioDomains.map(domain=>({domainId:domain.id,score:matches(goal,domain.keywords).length})).sort((a,b)=>b.score-a.score||a.domainId.localeCompare(b.domainId));if(scored[0].score===0)return{domainId:"planning-platform",confidence:.35,source:"FALLBACK",alternatives:[]};const best=scored[0],total=scored.reduce((sum,item)=>sum+item.score,0);return{domainId:best.domainId,confidence:Number(Math.min(.98,.55+best.score/Math.max(total,1)*.4).toFixed(2)),source:"KEYWORD",alternatives:scored.slice(1,4).filter(item=>item.score>0)};}

export async function loadDomainRuntimeRegistry(){const[skillRegistry,skillRules,agentRegistry,workerRegistry]=await Promise.all([readJson(paths.skills),readJson(paths.skillRules),readJson(paths.agents),readJson(paths.workers)]);return{skillRegistry,skillRules,agentRegistry,workerRegistry,paths};}

export function routeSkill(text,registry){const skills=new Map((registry.skillRegistry.skills??[]).map(skill=>[skill.skill_type,skill]));const scored=(registry.skillRules.rules??[]).map(rule=>({rule,skill:skills.get(rule.skill_type),keywords:matches(text,rule.keywords),score:matches(text,rule.keywords).length*10+(matches(text,rule.keywords).length?Number(rule.confidence_boost??0):0)})).filter(item=>item.skill).sort((a,b)=>b.score-a.score||String(a.rule.rule_id).localeCompare(String(b.rule.rule_id)));const selected=scored.find(item=>item.score>0);const fallbackType=registry.skillRules.routing_policy?.fallback_skill_type??"code_development",fallback=skills.get(fallbackType);const final=selected??{rule:{skill_type:fallbackType,selected_agent:"agent-5",runtime:"codex-cli",reason:"No skill keyword matched."},skill:fallback,keywords:[],score:0};return{skillType:final.rule.skill_type,skillId:final.skill?.skill_id??final.rule.skill_type,agentId:final.rule.selected_agent??final.skill?.default_agent??"agent-5",runtimeId:final.rule.runtime??final.skill?.default_runtime??"codex-cli",riskLevel:final.skill?.risk_level??"MEDIUM",validationCommands:final.skill?.validation_commands??[],confidence:selected?Math.min(.95,.55+final.score/100):.35,matchedKeywords:final.keywords};}

function agentForSkill(registry,preferredAgentId,skillType){const agents=registry.agentRegistry.agents??[];const preferred=agents.find(agent=>agent.agent_id===preferredAgentId&&agent.status==="ACTIVE"&&(agent.supported_skills??[]).includes(skillType));return preferred??agents.filter(agent=>agent.status==="ACTIVE"&&(agent.supported_skills??[]).includes(skillType)).sort((a,b)=>Number(a.priority??99)-Number(b.priority??99))[0]??null;}
function workerForSkill(registry,skillType,runtimeId=null){return(registry.workerRegistry.workers??[]).filter(worker=>worker.status==="available"&&(worker.supported_skills??[]).includes(skillType)&&(!runtimeId||worker.runtime_id===runtimeId)).sort((a,b)=>Number(a.risk==="LOW"?0:1)-Number(b.risk==="LOW"?0:1)||String(a.worker_id).localeCompare(String(b.worker_id)))[0]??(registry.workerRegistry.workers??[]).find(worker=>worker.status==="available"&&(worker.supported_skills??[]).includes(skillType))??null;}

export function compileDomainWorkflow(goal,registry,{explicitDomainId=null,goalId="domain-goal"}={}){const domainRoute=routeStudioDomain(goal,{explicitDomainId}),domain=getStudioDomain(domainRoute.domainId),primary=routeSkill(goal,registry);const stages=[{key:"PLAN",title:"Plan goal and constraints",skillType:"code_development",preferredAgentId:"agent-5",dependsOn:null},{key:"EXECUTE",title:"Execute professional work",skillType:primary.skillType,preferredAgentId:domain.agentId,dependsOn:"PLAN"},{key:"VALIDATE",title:"Validate outputs and safety",skillType:"validation_testing",preferredAgentId:"agent-2",dependsOn:"EXECUTE"},{key:"REPORT",title:"Produce durable result report",skillType:"document_generation",preferredAgentId:"agent-1",dependsOn:"VALIDATE"}];const assignments=stages.map(stage=>{const agent=agentForSkill(registry,stage.preferredAgentId,stage.skillType),skill=(registry.skillRegistry.skills??[]).find(item=>item.skill_type===stage.skillType),preferredRuntimeId=stage.key==="EXECUTE"?primary.runtimeId:(skill?.default_runtime??null),worker=workerForSkill(registry,stage.skillType,preferredRuntimeId);return{...stage,agentId:agent?.agent_id??null,preferredRuntimeId,runtimeId:worker?.runtime_id??preferredRuntimeId,workerKey:worker?.worker_id??null,workerMode:worker?.process_probe?.on_demand_ok?"ON_DEMAND":worker?"REGISTERED":"MISSING",status:agent&&worker?"READY":"BLOCKED",blockedReasons:[...(!agent?[`NO_AGENT_FOR_SKILL:${stage.skillType}`]:[]),...(!worker?[`NO_WORKER_FOR_SKILL:${stage.skillType}`]:[])]};});const tasks=assignments.map(stage=>({taskKey:`${goalId.toUpperCase().replace(/[^A-Z0-9]+/g,"_")}_${stage.key}`,title:stage.title,description:`${stage.title}: ${goal}`,priority:stage.key==="EXECUTE"?"P1":"P2",riskLevel:stage.key==="EXECUTE"?primary.riskLevel:"LOW",requiredCapabilities:[stage.skillType],maxAttempts:1,metadata:{domainId:domain.id,skillType:stage.skillType,agentId:stage.agentId,preferredRuntimeId:stage.preferredRuntimeId,runtimeId:stage.runtimeId,workerKey:stage.workerKey,workerMode:stage.workerMode,assignmentStatus:stage.status,blockedReasons:stage.blockedReasons}}));const dependencies=assignments.filter(stage=>stage.dependsOn).map(stage=>({taskKey:`${goalId.toUpperCase().replace(/[^A-Z0-9]+/g,"_")}_${stage.key}`,dependsOnTaskKey:`${goalId.toUpperCase().replace(/[^A-Z0-9]+/g,"_")}_${stage.dependsOn}`,dependencyType:"SUCCESS_REQUIRED",requiredStatus:"SUCCEEDED"}));return{schemaVersion:1,goalId,goal,domainRoute,domain:{id:domain.id,name:domain.name,agentId:domain.agentId},primarySkill:primary,assignments,tasks,dependencies,status:assignments.every(item=>item.status==="READY")?"READY":"BLOCKED",blockedReasons:assignments.flatMap(item=>item.blockedReasons),longRunning:true,persistentKernelRequired:true,onlineRunnerRequired:true};}

export class DomainWorkflowService{constructor({kernel,registry}){if(!kernel?.submitPlan)throw Object.assign(new Error("KERNEL_REQUIRED"),{code:"KERNEL_REQUIRED"});this.kernel=kernel;this.registry=registry;}compile(goal,options){return compileDomainWorkflow(goal,this.registry,options);}async compileAndSubmit(goal,options){const workflow=this.compile(goal,options);if(workflow.status!=="READY")throw Object.assign(new Error(`WORKFLOW_BLOCKED:${workflow.blockedReasons.join(",")}`),{code:"WORKFLOW_BLOCKED",workflow});const submission=await this.kernel.submitPlan(workflow.goalId,{plannerVersion:`domain-workflow-v1-${workflow.domain.id}`,sourceArtifactRef:`domain:${workflow.domain.id}`,tasks:workflow.tasks,dependencies:workflow.dependencies});return{workflow,submission};}}

export function domainCenterSummary(){return{schemaVersion:2,total:studioDomains.length,runtimeBound:studioDomains.filter(item=>item.maturity==="RUNTIME_BOUND").length,partial:studioDomains.filter(item=>item.maturity==="PARTIAL").length,singleControlPlane:true,sourceOfTruth:"agent-registry",domains:studioDomains};}
