import test from"node:test";import assert from"node:assert/strict";import{NightShiftSessionService,SmokeKernelFixture,smokeGoal}from"../lib/night-shift-smoke.mjs";
test("once mode completes the full Planner to controlled Runtime loop",async()=>{const service=new NightShiftSessionService(),session=service.createSession({mode:"once",maxTasks:10});const{graph}=await service.acceptGoal(session.id,smokeGoal);const report=await service.run(session.id);assert.equal(graph.templateId,"DOCUMENTATION");assert.deepEqual(report,{sessionId:session.id,sessionStatus:"SUCCEEDED",goalId:smokeGoal.id,goalStatus:"SUCCEEDED",totalTasks:3,succeededTasks:3,failedTasks:0,blockedTasks:0,attemptCount:3,schedulerTickCount:6,workerClaimCount:3,runtimeExecutionCount:3,startedAt:report.startedAt,finishedAt:report.finishedAt,errorSummary:[]});assert.ok(report.finishedAt>=report.startedAt);});
test("daemon mode also terminates normally without scheduler spin",async()=>{const service=new NightShiftSessionService({idlePollMs:1}),session=service.createSession({mode:"daemon",idleTimeoutMs:50});await service.acceptGoal(session.id,{...smokeGoal,id:"daemon-goal"});const report=await service.run(session.id);assert.equal(report.sessionStatus,"SUCCEEDED");assert.ok(report.schedulerTickCount<=report.totalTasks*2);});
test("Goal, plan and Tasks are idempotent",async()=>{const service=new NightShiftSessionService(),session=service.createSession();await service.acceptGoal(session.id,smokeGoal);await service.acceptGoal(session.id,smokeGoal);assert.equal(service.kernel.goals.size,1);assert.equal(service.kernel.plans.size,1);assert.equal(service.kernel.tasks.size,3);});
test("claim is exclusive and creates one active lease",async()=>{const kernel=new SmokeKernelFixture();kernel.createGoal({id:"G",title:"G"});await kernel.submitPlan("G",{plannerVersion:"P",tasks:[{taskKey:"T",title:"T"}],dependencies:[]});kernel.schedulerTick("G");kernel.schedulerTick("G");const first=kernel.claimNext("G"),second=kernel.claimNext("G");assert.ok(first);assert.equal(second,null);assert.equal([...kernel.leases.values()].filter(l=>l.status==="ACTIVE").length,1);assert.equal(kernel.claimCount,1);});
test("released or stale fencing cannot write completion",async()=>{const kernel=new SmokeKernelFixture();kernel.createGoal({id:"G",title:"G"});await kernel.submitPlan("G",{plannerVersion:"P",tasks:[{taskKey:"T",title:"T"}],dependencies:[]});kernel.schedulerTick("G");kernel.schedulerTick("G");const claim=kernel.claimNext("G");await kernel.markRunning(claim);await kernel.complete(claim,{status:"SUCCEEDED",fencingToken:claim.lease.fencingToken});await assert.rejects(kernel.complete(claim,{status:"SUCCEEDED",fencingToken:claim.lease.fencingToken}),e=>e.code==="FENCING_REJECTED");await assert.rejects(kernel.assertCurrent({taskId:claim.task.id,attemptId:claim.attempt.id,leaseId:claim.lease.id,fencingToken:claim.lease.fencingToken-1}),e=>e.code==="FENCING_REJECTED");});
test("controlled failure is reported and no Task is lost",async()=>{const service=new NightShiftSessionService({runtimeBehavior:"failure"}),session=service.createSession();await service.acceptGoal(session.id,{...smokeGoal,id:"failure-goal"});const report=await service.run(session.id);assert.equal(report.sessionStatus,"FAILED");assert.equal(report.goalStatus,"FAILED");assert.equal(report.failedTasks,1);assert.equal(report.totalTasks,report.succeededTasks+report.failedTasks+report.blockedTasks);assert.equal(report.attemptCount,report.workerClaimCount);});
test("maximum tasks and graceful shutdown are enforced",async()=>{const limited=new NightShiftSessionService(),a=limited.createSession({maxTasks:2});await assert.rejects(limited.acceptGoal(a.id,smokeGoal),/MAX_TASKS_EXCEEDED/);assert.equal(limited.kernel.tasks.size,0);const service=new NightShiftSessionService(),b=service.createSession({mode:"daemon"});await service.acceptGoal(b.id,{...smokeGoal,id:"shutdown-goal"});service.requestShutdown();const report=await service.run(b.id);assert.equal(report.sessionStatus,"CANCELLED");assert.equal(report.runtimeExecutionCount,0);});
test("maximum runtime and daemon idle timeout terminate safely",async()=>{const timed=new NightShiftSessionService(),a=timed.createSession({maxRuntimeMs:0});await timed.acceptGoal(a.id,{...smokeGoal,id:"runtime-limit"});assert.deepEqual((await timed.run(a.id)).errorSummary,["MAX_RUNTIME_EXCEEDED"]);const idle=new NightShiftSessionService({idlePollMs:1}),b=idle.createSession({mode:"daemon",idleTimeoutMs:3});await idle.acceptGoal(b.id,{...smokeGoal,id:"idle-limit"});idle.kernel.schedulerTick=()=>0;idle.kernel.claimNext=()=>null;assert.deepEqual((await idle.run(b.id)).errorSummary,["IDLE_TIMEOUT"]);});
