import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{assertTestDatabaseUrl,fixture}from"../lib/postgres-fixture.mjs";
test("PostgreSQL fixture rejects production and remote URLs",()=>{assert.equal(assertTestDatabaseUrl(fixture.url),fixture.url);for(const url of ["postgresql://localhost/production","postgresql://db.example.com/night_shift_test",""])assert.throws(()=>assertTestDatabaseUrl(url),/(UNSAFE|REQUIRED)/);});
test("persistent migration is reversible and covers every session fact",async()=>{const up=await readFile(new URL("../migrations/002_persistent_night_shift.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/002_persistent_night_shift.down.sql",import.meta.url),"utf8");for(const table of ["ad_night_shift_session","ad_scheduler_tick","ad_worker_claim","ad_session_error"])assert.match(up,new RegExp(`CREATE TABLE ${table}`));assert.match(up,/report jsonb/);assert.match(down,/DROP TABLE IF EXISTS ad_night_shift_session/);});
test("activation migration enforces replay and dangerous-operation boundaries",async()=>{const up=await readFile(new URL("../migrations/003_codex_activation_gate.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/003_codex_activation_gate.down.sql",import.meta.url),"utf8");for(const table of ["ad_project_runtime_policy","ad_runtime_approval","ad_credential_reference_binding","ad_outbox_consumption","ad_session_projection"])assert.match(up,new RegExp(`CREATE TABLE ${table}`));assert.match(up,/CHECK\(allow_push=false\)/);assert.match(up,/CHECK\(used_count<=max_uses\)/);assert.match(down,/DROP TABLE IF EXISTS ad_project_runtime_policy/);assert.notEqual(process.env.AUTONOMOUS_RUNTIME_CODEX_ENABLED,"true");});
test("business application migration persists scoped records, work and audit",async()=>{const up=await readFile(new URL("../migrations/004_business_applications.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/004_business_applications.down.sql",import.meta.url),"utf8");for(const table of ["business_application_record","business_work_item","business_application_event"])assert.match(up,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(up,/organization_id text NOT NULL/);assert.match(up,/workspace_id text NOT NULL/);assert.match(up,/idempotency_key text NOT NULL/);assert.match(up,/version integer NOT NULL/);assert.match(down,/DROP TABLE IF EXISTS business_application_record/);});
test("business approvals are scoped, single-pending and decision-auditable",async()=>{const up=await readFile(new URL("../migrations/005_business_approvals.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/005_business_approvals.down.sql",import.meta.url),"utf8");assert.match(up,/CREATE TABLE IF NOT EXISTS business_approval/);assert.match(up,/organization_id text NOT NULL/);assert.match(up,/uq_business_approval_pending_record/);assert.match(up,/status IN \('PENDING','APPROVED','REJECTED','CANCELLED'\)/);assert.match(down,/DROP TABLE IF EXISTS business_approval/);});
test("business work control adds version CAS without exposing leases",async()=>{const up=await readFile(new URL("../migrations/006_business_work_control.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/006_business_work_control.down.sql",import.meta.url),"utf8");assert.match(up,/ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1/);assert.match(up,/idx_business_work_kernel_goal/);assert.match(down,/DROP COLUMN IF EXISTS version/);});
test("business record relations are scoped, constrained and reversible",async()=>{const up=await readFile(new URL("../migrations/007_business_record_relations.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/007_business_record_relations.down.sql",import.meta.url),"utf8");assert.match(up,/CREATE TABLE IF NOT EXISTS business_record_relation/);assert.match(up,/CHECK\(source_record_id <> target_record_id\)/);assert.match(up,/UNIQUE\(organization_id,workspace_id,source_record_id,target_record_id,relation_type\)/);assert.match(down,/DROP TABLE IF EXISTS business_record_relation/);});

test("business runner nodes persist lifecycle, capacity and immutable control evidence",async()=>{const up=await readFile(new URL("../migrations/008_business_runner_nodes.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/008_business_runner_nodes.down.sql",import.meta.url),"utf8");for(const value of ["business_runner_node","business_runner_event","last_heartbeat_at","desired_state","CHECK(status IN ('ONLINE','DRAINING','OFFLINE'))","CHECK(capacity > 0)"])assert.match(up,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(down,/DROP TABLE IF EXISTS business_runner_event/);assert.match(down,/DROP TABLE IF EXISTS business_runner_node/);});

test("business work result summary is structured and exactly reversible",async()=>{const up=await readFile(new URL("../migrations/009_business_work_results.up.sql",import.meta.url),"utf8"),down=await readFile(new URL("../migrations/009_business_work_results.down.sql",import.meta.url),"utf8");assert.match(up,/ADD COLUMN IF NOT EXISTS result_summary jsonb/);assert.match(up,/jsonb_typeof\(result_summary\)='object'/);assert.match(down,/DROP COLUMN IF EXISTS result_summary/);});
